const candidateSeed = [
  [
    "candidate-linhao",
    "林昊",
    "拓界机器人",
    "机器人学习负责人",
    "上海",
    "博士",
    "12 年",
    "91",
    "推进中",
  ],
  [
    "candidate-zhaoxingyu",
    "赵星羽",
    "星澜机器人",
    "VLA 算法负责人",
    "北京",
    "硕士",
    "9 年",
    "94",
    "储备",
  ],
  [
    "candidate-chenchuning",
    "陈楚宁",
    "灵跃科技",
    "灵巧操作算法负责人",
    "深圳",
    "博士",
    "8 年",
    "89",
    "推进中",
  ],
  [
    "candidate-zhoumingyuan",
    "周明远",
    "穹顶智能",
    "具身智能算法总监",
    "上海",
    "博士",
    "13 年",
    "86",
    "储备",
  ],
  [
    "candidate-hewenting",
    "何文婷",
    "上海人工智能实验室",
    "机器人学习研究员",
    "上海",
    "博士",
    "6 年",
    "84",
    "储备",
  ],
  [
    "candidate-wangyi",
    "王奕",
    "星澜机器人",
    "机器人学习研究员",
    "北京",
    "硕士",
    "5 年",
    "78",
    "待核实",
  ],
  [
    "candidate-jiangyifan",
    "蒋一帆",
    "智源研究院",
    "多模态算法研究员",
    "北京",
    "博士",
    "7 年",
    "82",
    "储备",
  ],
  [
    "candidate-sunran",
    "孙然",
    "达摩院",
    "强化学习专家",
    "杭州",
    "博士",
    "10 年",
    "80",
    "失败",
  ],
  [
    "candidate-gaoyuan",
    "高远",
    "腾讯 Robotics X",
    "机器人控制专家",
    "深圳",
    "硕士",
    "11 年",
    "77",
    "储备",
  ],
  [
    "candidate-liangchen",
    "梁辰",
    "银河通用",
    "仿真平台负责人",
    "北京",
    "硕士",
    "9 年",
    "75",
    "已入职",
  ],
  [
    "candidate-yangfan",
    "杨帆",
    "小鹏机器人",
    "运动控制工程师",
    "广州",
    "本科",
    "6 年",
    "73",
    "储备",
  ],
  [
    "candidate-tangwen",
    "唐雯",
    "北京大学",
    "助理研究员",
    "北京",
    "博士",
    "4 年",
    "69",
    "储备",
  ],
];

export const candidates = candidateSeed.map((item, index) => ({
  id: item[0],
  name: item[1],
  company: item[2],
  title: item[3],
  location: item[4],
  education: item[5],
  experience: item[6],
  score: Number(item[7]),
  pipeline: item[8],
  industries: index % 2 ? ["人工智能", "机器人"] : ["机器人", "企业服务"],
  skills:
    index < 4
      ? ["VLA", "强化学习", "真机部署"]
      : ["机器人学习", "PyTorch", "数据闭环"],
  updatedAt: index < 3 ? "今天" : `${index + 1} 天前`,
  folders:
    index < 3 ? ["VLA 重点人才", "本周联系"] : index < 7 ? ["长期观察"] : [],
}));

export const candidateDetail = {
  ...candidates[0],
  englishName: "Hao Lin",
  birthYear: "1989",
  gender: "男",
  phone: "138 **** 6217",
  email: "hao.lin@example.com",
  preference: "愿意了解机会",
  summary:
    "12 年机器人学习与具身智能经验，长期负责从算法研究到真机部署的数据闭环。近三年带领 14 人团队完成模仿学习和强化学习平台建设，适合承担 VLA 算法负责人或机器人学习负责人岗位。",
  links: [
    ["LinkedIn", "linkedin.com/in/hao-lin-robotics", "已验证"],
    ["GitHub", "github.com/haolin-robotics", "可访问"],
    ["Google Scholar", "scholar.google.com/citations?user=HL2026", "已验证"],
  ],
  experiences: [
    {
      company: "拓界机器人",
      formalCompany: "拓界机器人",
      title: "机器人学习负责人",
      period: "2022.03 - 至今",
      department: "智能操作部 / 机器人学习团队",
      detail:
        "负责 14 人机器人学习团队，建设模仿学习、强化学习与真机数据闭环；主导三代操作策略上线，将新任务数据准备周期缩短 45%。",
    },
    {
      company: "上海人工智能实验室",
      formalCompany: "上海人工智能实验室",
      title: "高级研究员",
      period: "2018.07 - 2022.02",
      department: "具身智能中心",
      detail:
        "负责视觉运动策略和仿真到真机迁移研究，参与两项国家重点课题，发表 8 篇机器人学习论文。",
    },
  ],
  educationHistory: [
    ["香港科技大学", "计算机科学 · 博士", "2013 - 2018"],
    ["浙江大学", "自动化 · 本科", "2009 - 2013"],
  ],
  projects: [
    [
      "多任务机器人操作策略平台",
      "项目负责人",
      "2023 - 至今",
      "统一 26 类操作任务的数据、训练和评测流程，真实场景成功率提升 18%。",
    ],
    [
      "Sim2Real 数据闭环",
      "算法负责人",
      "2020 - 2022",
      "建立仿真数据生成和真机失败样本回流链路，支持每周稳定迭代。",
    ],
  ],
  resumes: [
    [
      "林昊_机器人学习负责人_2026.pdf",
      "当前简历",
      "2026-08-18 10:23",
      "解析成功",
      "2.8 MB",
    ],
    [
      "Hao_Lin_CV_2025.pdf",
      "历史简历",
      "2025-11-03 16:40",
      "解析成功",
      "1.9 MB",
    ],
  ],
  files: [
    ["林昊_项目作品集.pdf", "作品集", "2026-08-18", "6.4 MB"],
    ["机器人学习负责人推荐说明.docx", "推荐材料", "2026-08-19", "126 KB"],
  ],
  timeline: [
    [
      "今天 10:36",
      "人工备注",
      "候选人希望岗位有明确的数据闭环和真机落地资源。",
      "沈岚",
    ],
    [
      "昨天 18:20",
      "资料更新",
      "通过新简历补充团队规模和两项项目成果。",
      "候选人信息补全",
    ],
    [
      "08-18 15:42",
      "邮件回复",
      "愿意下周二下午沟通岗位细节。",
      "hao.lin@example.com",
    ],
  ],
};

export const positions = [
  {
    id: "position-vla",
    name: "具身智能 VLA 算法负责人",
    company: "星澜机器人",
    location: "北京 / 上海",
    status: "招聘中",
    skills: ["VLA", "强化学习", "真机部署"],
    matches: 18,
    reserve: 12,
    progress: 6,
    hired: 0,
    failed: 2,
    updatedAt: "今天 09:40",
  },
  {
    id: "position-hand",
    name: "灵巧手结构工程师",
    company: "灵跃科技",
    location: "深圳",
    status: "招聘中",
    skills: ["结构设计", "精密传动", "量产"],
    matches: 24,
    reserve: 9,
    progress: 8,
    hired: 1,
    failed: 6,
    updatedAt: "今天 08:20",
  },
  {
    id: "position-platform",
    name: "机器人数据平台负责人",
    company: "拓界机器人",
    location: "上海",
    status: "招聘中",
    skills: ["数据平台", "MLOps", "团队管理"],
    matches: 11,
    reserve: 6,
    progress: 3,
    hired: 0,
    failed: 2,
    updatedAt: "昨天",
  },
  {
    id: "position-control",
    name: "运动控制算法专家",
    company: "穹顶智能",
    location: "北京",
    status: "已暂停",
    skills: ["运动控制", "优化", "C++"],
    matches: 16,
    reserve: 7,
    progress: 4,
    hired: 0,
    failed: 5,
    updatedAt: "3 天前",
  },
  {
    id: "position-simulation",
    name: "仿真平台高级工程师",
    company: "星澜机器人",
    location: "北京",
    status: "已关闭",
    skills: ["仿真", "Isaac Sim", "Python"],
    matches: 31,
    reserve: 0,
    progress: 0,
    hired: 1,
    failed: 30,
    updatedAt: "08-12",
  },
];

export const positionDetail = {
  ...positions[0],
  salary: "80 - 120 万 / 年",
  experience: "8 年及以上",
  education: "硕士及以上，能力突出可放宽",
  sourceOpportunity: "星澜机器人具身智能团队扩张",
  jdVersion: "v3 · 2026-08-19",
  jd: `岗位职责\n1. 负责 VLA 模型、机器人学习策略和真机数据闭环的技术路线与团队交付。\n2. 推动视觉、语言、动作统一建模在复杂操作任务中的落地。\n3. 建设数据采集、训练、评测和部署平台，与硬件、产品和工程团队协作。\n4. 带领算法团队完成关键项目并培养核心骨干。\n\n任职要求\n1. 计算机、自动化、机器人等相关专业硕士及以上学历。\n2. 具备 8 年以上机器人学习、强化学习或多模态模型经验。\n3. 有真实机器人部署、团队管理和跨部门交付经验。`,
  confirmedRequirements: [
    "必须有真实机器人策略部署经验，不能只有仿真或纯研究经历。",
    "能够管理 8 人以上算法团队，并对工程交付结果负责。",
    "工作地点优先北京，可接受每月短期往返上海。",
  ],
  analysis: [
    [
      "岗位定位",
      "连接 VLA 研究、机器人学习平台与真机产品交付的算法负责人，不是纯研究岗位。",
    ],
    [
      "上下游关系",
      "上游承接产品任务和硬件能力，下游负责数据、训练、评测、部署与线上问题闭环。",
    ],
    [
      "可迁移背景",
      "机器人操作、自动驾驶决策、多模态具身模型和强化学习平台负责人可以迁移。",
    ],
    [
      "对标企业",
      "银河通用、智元机器人、灵跃科技、上海人工智能实验室、腾讯 Robotics X。",
    ],
    ["目标职级", "成熟创业公司算法负责人；大厂 P8 / P9 或同等技术管理岗位。"],
    [
      "文化偏好",
      "重视结果、快速验证和跨团队协作，能够在研究完整性与产品节奏之间取舍。",
    ],
    [
      "软性和隐性要求",
      "需要主动建立跨硬件、产品和数据团队的协作机制。当前数据基础仍在扩建，候选人需要接受较高的不确定性，并能亲自下场解决关键问题。",
    ],
  ],
  keywordGroups: [
    ["VLA", "机器人学习"],
    ["模仿学习", "真机部署"],
    ["强化学习", "机器人操作"],
    ["多模态", "具身智能"],
    ["数据闭环", "操作策略"],
  ],
  stages: [
    "储备",
    "推荐",
    "一面",
    "二面",
    "谈薪",
    "已入职",
    "候选人放弃",
    "已落选",
    "不合适",
  ],
};

export const companies = [
  {
    id: "company-xinglan",
    name: "星澜机器人",
    industries: ["机器人", "人工智能"],
    location: "北京、上海",
    contacts: 4,
    opportunities: 2,
    positions: 3,
    talents: 16,
    progress: 8,
    updatedAt: "今天",
  },
  {
    id: "company-tuojie",
    name: "拓界机器人",
    industries: ["机器人", "智能制造"],
    location: "上海",
    contacts: 3,
    opportunities: 1,
    positions: 2,
    talents: 13,
    progress: 5,
    updatedAt: "昨天",
  },
  {
    id: "company-lingyue",
    name: "灵跃科技",
    industries: ["机器人", "硬件"],
    location: "深圳、东莞",
    contacts: 2,
    opportunities: 1,
    positions: 4,
    talents: 10,
    progress: 9,
    updatedAt: "2 天前",
  },
  {
    id: "company-qiongding",
    name: "穹顶智能",
    industries: ["机器人", "企业服务"],
    location: "北京",
    contacts: 1,
    opportunities: 1,
    positions: 2,
    talents: 7,
    progress: 4,
    updatedAt: "4 天前",
  },
  {
    id: "company-ailab",
    name: "上海人工智能实验室",
    industries: ["科研", "人工智能"],
    location: "上海",
    contacts: 2,
    opportunities: 0,
    positions: 1,
    talents: 21,
    progress: 0,
    updatedAt: "08-10",
  },
];

export const companyDetail = {
  ...companies[0],
  aliases: ["Xinglan Robotics", "星澜智能机器人"],
  website: "www.xinglan-robotics.com",
  intro:
    "星澜机器人是一家具身智能创业公司，聚焦通用机器人操作策略、VLA 模型与真机数据闭环。公司 2024 年完成 B+ 轮融资，研发团队主要位于北京和上海。",
  financing:
    "2024 年完成 B+ 轮融资，融资额约 4 亿元；投资方包括启程资本、远望创投和产业资本。",
  advantages:
    "核心团队来自头部机器人公司和研究机构，算法岗位可以直接接触规模化真机数据；研发决策链路短，技术负责人对产品路线有较大影响力。",
  benefits:
    "算法岗位通常采用 14 - 16 薪，核心岗位另有期权；提供补充医疗、年度体检和搬迁支持。",
  interview:
    "简历评估后进行技术初面、专题技术面、交叉面和创始人终面，通常 3 - 4 周。",
  bases:
    "北京：算法、产品和总部职能。\n上海：机器人学习、数据平台和硬件联调。\n苏州：小批量制造与测试。",
  requirements:
    "对核心岗位的工程交付经历要求高；部分岗位需要每月在北京和上海之间短期出差。",
  note: "客户更关注候选人是否真正做过真机闭环，推荐前需要核实项目中的个人贡献。",
};

export const contacts = [
  {
    id: "contact-chenyu",
    name: "陈雨",
    categories: ["招聘负责人", "客户 HR"],
    company: "星澜机器人",
    role: "招聘负责人",
    phone: "138 **** 6217",
    email: "yu.chen@xinglan-robotics.com",
    region: "北京",
    lastContact: "昨天 18:20",
  },
  {
    id: "contact-zhouqi",
    name: "周琪",
    categories: ["客户 HR"],
    company: "星澜机器人",
    role: "机器人算法 HRBP",
    phone: "",
    email: "qi.zhou@xinglan-robotics.com",
    region: "上海",
    lastContact: "3 天前",
  },
  {
    id: "contact-liujian",
    name: "刘健",
    categories: ["投资人", "中间介绍人"],
    company: "启程资本",
    role: "投资经理",
    phone: "186 **** 0921",
    email: "jian.liu@qichengcap.com",
    region: "北京",
    lastContact: "08-11",
  },
  {
    id: "contact-zhangmin",
    name: "张敏",
    categories: ["招聘负责人"],
    company: "拓界机器人",
    role: "人才招聘总监",
    phone: "139 **** 4803",
    email: "min.zhang@tuojie.ai",
    region: "上海",
    lastContact: "08-09",
  },
  {
    id: "contact-lijie",
    name: "李洁",
    categories: ["顾问"],
    company: "灵跃科技",
    role: "外部人才顾问",
    phone: "137 **** 6832",
    email: "",
    region: "深圳",
    lastContact: "07-28",
  },
];

export const opportunities = [
  {
    id: "opportunity-xinglan",
    title: "星澜机器人具身智能团队扩张",
    company: "星澜机器人",
    summary: "计划在北京和上海扩充 VLA、机器人学习与数据平台团队。",
    evidence: "招聘负责人确认 2026 下半年新增核心岗位",
    directions: 4,
    positions: 2,
    status: "跟进中",
    updatedAt: "今天",
  },
  {
    id: "opportunity-tuojie",
    title: "拓界机器人操作策略团队补强",
    company: "拓界机器人",
    summary: "补充机器人学习负责人和数据平台骨干。",
    evidence: "客户会议纪要与公开招聘页",
    directions: 2,
    positions: 1,
    status: "跟进中",
    updatedAt: "昨天",
  },
  {
    id: "opportunity-lingyue",
    title: "灵跃科技灵巧手量产团队",
    company: "灵跃科技",
    summary: "结构、驱动和量产工程岗位集中招聘。",
    evidence: "客户 HR 邮件确认",
    directions: 3,
    positions: 3,
    status: "已完成",
    updatedAt: "08-15",
  },
  {
    id: "opportunity-qiongding",
    title: "穹顶智能新产品线准备",
    company: "穹顶智能",
    summary: "多模态决策团队可能扩编，具体 HC 待确认。",
    evidence: "业务负责人确认方向，人数待定",
    directions: 2,
    positions: 0,
    status: "跟进中",
    updatedAt: "08-12",
  },
];

export const landscapes = [
  {
    id: "mapping-embodied",
    name: "具身智能 VLA 核心人才版图",
    goal: "摸清 VLA、机器人学习与真机数据闭环团队及关键人才",
    companies: 8,
    organizations: 19,
    people: 37,
    relations: 64,
    gaps: 5,
    updatedAt: "今天 11:20",
  },
  {
    id: "mapping-hand",
    name: "灵巧手结构与驱动人才版图",
    goal: "覆盖灵巧手结构、传动、驱动和量产方向",
    companies: 11,
    organizations: 22,
    people: 49,
    relations: 71,
    gaps: 8,
    updatedAt: "昨天",
  },
  {
    id: "mapping-autodrive",
    name: "自动驾驶决策算法人才版图",
    goal: "梳理决策规划团队和可迁移到具身智能的人才",
    companies: 14,
    organizations: 31,
    people: 68,
    relations: 108,
    gaps: 4,
    updatedAt: "3 天前",
  },
];

export const papers = [
  {
    id: "paper-vla-survey",
    title: "Vision-Language-Action Models for Robotics: A Survey",
    titleZh: "机器人视觉语言动作模型综述",
    year: 2026,
    venue: "IEEE T-PAMI",
    authors: ["Hao Lin", "Mingyuan Zhou", "Yifan Jiang"],
    institutions: ["Tuojie Robotics", "Qiongding AI"],
    citations: 42,
    tags: ["VLA", "机器人学习"],
    relation: "2 位已关联",
    source: "OpenAlex",
  },
  {
    id: "paper-diffusion",
    title: "Diffusion Policies for Generalizable Robot Manipulation",
    titleZh: "面向泛化机器人操作的扩散策略",
    year: 2025,
    venue: "CoRL",
    authors: ["Xingyu Zhao", "Chuning Chen"],
    institutions: ["Xinglan Robotics", "Lingyue AI"],
    citations: 68,
    tags: ["扩散策略", "机器人操作"],
    relation: "1 位待确认",
    source: "OpenAlex / Crossref",
  },
  {
    id: "paper-dataclosed",
    title: "Closing the Data Loop for Large-Scale Robot Learning",
    titleZh: "大规模机器人学习的数据闭环",
    year: 2025,
    venue: "RSS",
    authors: ["Wenting He", "Hao Lin"],
    institutions: ["Shanghai AI Laboratory", "Tuojie Robotics"],
    citations: 31,
    tags: ["数据闭环", "真机部署"],
    relation: "2 位已关联",
    source: "arXiv",
  },
  {
    id: "paper-sim2real",
    title: "Scalable Sim-to-Real Transfer with Action Priors",
    titleZh: "基于动作先验的可扩展仿真到现实迁移",
    year: 2024,
    venue: "ICRA",
    authors: ["Chen Liang", "Yuan Gao"],
    institutions: ["Galbot", "Tencent Robotics X"],
    citations: 97,
    tags: ["Sim2Real", "强化学习"],
    relation: "未关联",
    source: "Crossref",
  },
];

export const patents = [
  {
    id: "patent-manipulation",
    title: "一种面向多任务机器人的操作策略训练方法",
    type: "发明专利",
    applicant: "星澜机器人（北京）有限公司",
    inventors: ["赵星羽", "王奕", "陈雨"],
    applicationNo: "CN202610234567.8",
    publicationNo: "CN118765432A",
    applicationDate: "2026-03-18",
    grantDate: "—",
    tags: ["操作策略", "VLA"],
    relation: "1 位已关联",
  },
  {
    id: "patent-hand",
    title: "灵巧手关节传动机构及机器人",
    type: "发明专利",
    applicant: "深圳灵跃科技有限公司",
    inventors: ["陈楚宁", "李博", "许佳"],
    applicationNo: "CN202510987654.2",
    publicationNo: "CN117654321A",
    applicationDate: "2025-08-09",
    grantDate: "2026-06-20",
    tags: ["灵巧手", "精密传动"],
    relation: "1 位已关联",
  },
  {
    id: "patent-data",
    title: "机器人训练数据的自动筛选与回流系统",
    type: "发明专利",
    applicant: "拓界机器人（上海）有限公司",
    inventors: ["林昊", "张敏"],
    applicationNo: "CN202511345678.0",
    publicationNo: "CN117998877A",
    applicationDate: "2025-10-11",
    grantDate: "—",
    tags: ["数据闭环", "机器人学习"],
    relation: "1 位已关联",
  },
];

export const matchResults = candidates.slice(0, 8).map((candidate, index) => ({
  ...candidate,
  score: [94, 91, 89, 86, 84, 78, 82, 80][index],
  roleGate: index === 3 ? "有条件" : index === 5 ? "拒绝" : "通过",
  reason:
    index === 0
      ? "机器人学习与真机数据闭环经历完整，团队规模和岗位要求高度一致。"
      : index === 1
        ? "VLA 技术方向高度匹配，已承担算法负责人职责。"
        : "核心技术方向匹配，仍需核实团队管理和复杂产品交付经历。",
  risk:
    index === 3
      ? "当前职级偏高，需要确认是否接受缩小管理范围。"
      : index === 5
        ? "公开资料中的当前角色与论文单位时间线存在冲突。"
        : "需要核实最近两年真机部署的个人贡献。",
}));

export const recycleItems = [
  [
    "candidate-old",
    "候选人",
    "沈明哲",
    "删除了重复档案",
    "沈岚",
    "今天 10:02",
    "剩余 29 天",
  ],
  [
    "position-old",
    "岗位",
    "机器人感知算法工程师",
    "客户暂停招聘后误删",
    "沈岚",
    "昨天 16:30",
    "剩余 28 天",
  ],
  [
    "company-old",
    "公司",
    "极光机器人",
    "资料重复",
    "沈岚",
    "08-12 11:20",
    "剩余 21 天",
  ],
  [
    "paper-old",
    "论文",
    "Learning Dexterous Manipulation from Human Videos",
    "重复导入",
    "系统",
    "08-08 09:12",
    "剩余 17 天",
  ],
].map(([id, type, name, reason, operator, deletedAt, remaining]) => ({
  id,
  type,
  name,
  reason,
  operator,
  deletedAt,
  remaining,
}));

export const importTasks = [
  {
    id: "import-resumes",
    name: "8 月候选人简历批量导入",
    type: "候选人",
    file: "候选人简历_20260820.zip",
    progress: 100,
    result: "新建 18 · 更新 7 · 待确认 2 · 失败 1",
    status: "已完成",
    time: "今天 09:42",
  },
  {
    id: "import-papers",
    name: "星澜机器人论文结果导入",
    type: "论文",
    file: "academic-search-20260820.xlsx",
    progress: 68,
    result: "已处理 340 / 500",
    status: "处理中",
    time: "今天 10:18",
  },
  {
    id: "import-mapping",
    name: "灵巧手人才版图导入",
    type: "人才版图",
    file: "灵巧手人才图谱.xlsx",
    progress: 0,
    result: "第 3 行组织层级不连续",
    status: "需要处理",
    time: "昨天 19:07",
  },
];

export const exportTasks = [
  {
    id: "export-candidates",
    name: "VLA 岗位储备候选人",
    scope: "12 位候选人及匹配摘要",
    format: "Excel",
    status: "可下载",
    time: "今天 11:02",
    expires: "6 天后失效",
  },
  {
    id: "export-mapping",
    name: "具身智能 VLA 核心人才版图",
    scope: "当前版图 · 37 人 · 64 条关系",
    format: "Excel",
    status: "可下载",
    time: "昨天 17:28",
    expires: "5 天后失效",
  },
  {
    id: "export-company",
    name: "星澜机器人完整资料",
    scope: "公司资料与关联摘要",
    format: "PDF",
    status: "生成中",
    time: "今天 11:26",
    expires: "—",
  },
];

export const assetMeta = {
  candidates: {
    label: "候选人",
    singular: "候选人",
    icon: "users",
    route: "/candidates",
  },
  positions: {
    label: "岗位",
    singular: "岗位",
    icon: "briefcase",
    route: "/positions",
  },
  companies: {
    label: "公司",
    singular: "公司",
    icon: "building",
    route: "/companies",
  },
  contacts: {
    label: "联系人",
    singular: "联系人",
    icon: "user",
    route: "/contacts",
  },
  opportunities: {
    label: "招聘机会",
    singular: "招聘机会",
    icon: "signal",
    route: "/opportunities",
  },
  mappings: {
    label: "人才版图",
    singular: "人才版图",
    icon: "route",
    route: "/mappings",
  },
  papers: { label: "论文", singular: "论文", icon: "paper", route: "/papers" },
  patents: {
    label: "专利",
    singular: "专利",
    icon: "patent",
    route: "/patents",
  },
};
