export const clientEvidence = [
  {
    source: "星澜机器人官网",
    finding: "过去 14 天新增 9 个机器人算法、平台研发和硬件岗位",
    freshness: "今天 09:12",
    confidence: "高可信",
    stance: "支持",
  },
  {
    source: "融资公告",
    finding: "完成 B+ 轮融资，公开用途包含北京研发团队扩张",
    freshness: "6 天前",
    confidence: "高可信",
    stance: "支持",
  },
  {
    source: "行业关系备注",
    finding: "原合作方反馈算法团队仍在扩充，但尚未确认外部猎头预算",
    freshness: "3 天前",
    confidence: "待确认",
    stance: "不确定",
  },
];

export const contactReviewRows = [
  {
    id: "contact-chenyu",
    name: "陈雨",
    role: "招聘负责人",
    company: "星澜机器人",
    category: "招聘负责人",
    phone: "138 **** 6217",
    email: "yu.chen@xinglan-robotics.com",
    source: "官网招聘邮箱、脉脉身份与用户关系备注交叉确认",
    confidence: "身份已确认",
    tone: "success",
    preferred: true,
  },
  {
    id: "contact-zhouqi",
    name: "周琪",
    role: "机器人算法 HRBP",
    company: "星澜机器人",
    category: "客户 HR",
    phone: "",
    email: "qi.zhou@xinglan-robotics.com",
    source: "官网招聘页面与公开职业资料",
    confidence: "身份已确认",
    tone: "success",
  },
  {
    id: "lead-vp-hr",
    name: "人力资源副总裁线索",
    role: "具体姓名尚未确认",
    company: "星澜机器人",
    category: "联系人线索",
    phone: "",
    email: "",
    source: "融资报道提到本轮招聘由人力资源负责人统筹",
    confidence: "身份待确认",
    tone: "warning",
  },
  {
    id: "contact-liujian",
    name: "刘健",
    role: "投资经理",
    company: "启程资本",
    category: "中间介绍人",
    phone: "",
    email: "",
    source: "用户已有联系人",
    confidence: "关系已确认",
    tone: "success",
  },
];

export const mappingCompanies = [
  {
    company: "星澜机器人",
    direction: "VLA 与机器人学习",
    organization: "具身智能中心 / 机器人学习组",
    people: 11,
    status: "核心团队已定位",
    tone: "success",
  },
  {
    company: "拓界机器人",
    direction: "操作策略与真机部署",
    organization: "智能操作部 / 策略学习团队",
    people: 8,
    status: "缺 1 位技术负责人",
    tone: "warning",
  },
  {
    company: "穹顶智能",
    direction: "多模态决策与数据闭环",
    organization: "具身算法平台",
    people: 6,
    status: "组织关系待确认",
    tone: "warning",
  },
  {
    company: "灵跃科技",
    direction: "灵巧操作与模仿学习",
    organization: "灵巧手算法组",
    people: 5,
    status: "本轮范围已覆盖",
    tone: "success",
  },
];

export const mappingPeople = [
  {
    id: "map-linhao",
    name: "林昊",
    role: "机器人学习负责人",
    company: "拓界机器人",
    identity: "已关联候选人",
    relation: "与周明远有共同论文及前同事关系",
    source: "论文、公开履历、Hunter 候选人档案",
    confidence: "已确认",
  },
  {
    id: "map-zhoumingyuan",
    name: "周明远",
    role: "具身智能算法总监",
    company: "穹顶智能",
    identity: "人物线索",
    relation: "曾与星澜机器人技术顾问共同申请专利",
    source: "专利、会议演讲与公司公开资料",
    confidence: "较高",
  },
  {
    id: "map-chenchuning",
    name: "陈楚宁",
    role: "VLA 算法负责人",
    company: "灵跃科技",
    identity: "已关联候选人",
    relation: "灵巧操作方向关键角色",
    source: "Hunter 候选人档案、GitHub 与论文",
    confidence: "已确认",
  },
  {
    id: "map-wangyi",
    name: "王奕（待确认）",
    role: "机器人学习研究员",
    company: "星澜机器人",
    identity: "身份需要确认",
    relation: "同名作者与公开职位信息可能属于同一人",
    source: "论文作者与公开招聘活动名单",
    confidence: "存在冲突",
  },
];

export const careerMatches = [
  {
    id: "match-xinglan-vla",
    title: "具身智能 VLA 算法负责人",
    company: "星澜机器人",
    location: "北京",
    status: "招聘中",
    score: 92,
    recommendation: "优先沟通",
    tone: "success",
    reason: "VLA 产品落地、机器人学习和 8 人团队管理经历与岗位高度重合。",
    risk: "林昊当前总包可能高于岗位已知区间，且尚未确认北京长期意愿。",
    gaps: "需核实到岗时间、薪酬预期和是否接受从平台团队转入业务团队。",
    talkingPoint:
      "先确认其下一阶段是否希望继续带团队，再介绍星澜的真机数据闭环和团队空间。",
  },
  {
    id: "match-tuoji-policy",
    title: "机器人策略学习技术总监",
    company: "拓界机器人",
    location: "上海",
    status: "招聘中",
    score: 84,
    recommendation: "可以了解",
    tone: "info",
    reason: "策略学习与仿真到真机经验匹配，且熟悉现有团队技术栈。",
    risk: "岗位更偏跨团队平台建设，管理范围和决策权尚未完全确认。",
    gaps: "需确认异地意愿和岗位是否允许北京办公。",
    talkingPoint: "可先询问他对平台型岗位和上海工作安排的接受度。",
  },
  {
    id: "match-lingyue-head",
    title: "灵巧操作算法负责人",
    company: "灵跃科技",
    location: "深圳",
    status: "已暂停",
    score: 77,
    recommendation: "暂不优先",
    tone: "warning",
    reason: "机器人学习能力可迁移，但灵巧手专项经历不是其最强方向。",
    risk: "岗位目前暂停，且地点与候选人已知偏好差异较大。",
    gaps: "等待岗位恢复并补充团队职责后再判断。",
    talkingPoint: "不建议本轮主动推荐，只可作为后续备选方向。",
  },
];

export const businessScenarios = {
  "client-xinglan": {
    id: "client-xinglan",
    type: "客户开发",
    title: "星澜机器人招聘合作",
    object: "星澜机器人 · 具身智能与机器人研发",
    prompt:
      "星澜机器人刚完成新一轮融资，最近也在扩机器人团队。帮我判断这家公司值不值得跟进，找到合适的招聘负责人和可用联系方式；如果确实有招聘需求，先整理成招聘机会，不要直接创建岗位。",
    autoStopPhase: 3,
    maxPhase: 6,
    defaultAuth: "confirm",
    plan: [
      {
        id: "verify",
        title: "核验公司与招聘信号",
        detail: "交叉检查融资、招聘变化、组织扩张和反向证据。",
        requirement: "先判断是否值得开发，不把融资新闻直接当成招聘需求。",
        doneAt: 2,
      },
      {
        id: "contacts",
        title: "查找联系人与可用联系路径",
        detail: "识别招聘负责人、HRBP 和已有关系，并核验手机或邮箱。",
        requirement:
          "必须说明联系人数量、具备手机或邮箱的人数、首选对象和待补充信息。",
        doneAt: 3,
      },
      {
        id: "assets",
        title: "确认公司与联系人结果",
        detail: "用户审核后才形成正式公司和联系人资产。",
        requirement: "联系人业务确认与对外联系授权分开。",
        doneAt: 4,
        waitAt: 3,
      },
      {
        id: "outreach",
        title: "联系并等待外部回复",
        detail: "发送前检查对象、身份、渠道和正文；等待期间不持续运行。",
        requirement: "产生外部影响前必须得到本次授权。",
        doneAt: 6,
        waitAt: 4,
        externalAt: 5,
      },
      {
        id: "opportunity",
        title: "形成招聘机会与后续工作",
        detail: "收到回复后整理需求；完整 JD 先形成岗位草稿。",
        requirement: "信息不完整时不能伪造正式岗位。",
        doneAt: 7,
      },
    ],
    tasks: [
      {
        id: "client-company",
        title: "公司与融资信号核验",
        status: "完成",
        tone: "success",
        action: "3 类来源相互印证，仍有猎头预算待确认",
        duration: "1 分 18 秒",
      },
      {
        id: "client-contacts",
        title: "联系人与联系方式核验",
        status: "等待用户",
        tone: "warning",
        action: "2 位正式联系人、1 条身份线索和 1 条引荐路径待审核",
        duration: "3 分 42 秒",
      },
      {
        id: "client-outreach",
        title: "客户联系与回复跟进",
        status: "未开始",
        tone: "neutral",
        action: "等待联系人审核和对外联系授权",
        duration: "—",
      },
    ],
  },
  "mapping-embodied": {
    id: "mapping-embodied",
    type: "人才摸排",
    title: "具身智能核心人才版图",
    object: "VLA、机器人学习与灵巧操作",
    prompt:
      "把国内具身智能方向做一次人才摸排，先覆盖 VLA、机器人学习和灵巧操作。重点看星澜、拓界、穹顶和灵跃四家公司，整理组织方向、关键角色、人物关系和能够联系到人的路径。",
    autoStopPhase: 4,
    maxPhase: 5,
    defaultAuth: "confirm",
    plan: [
      {
        id: "scope",
        title: "确认摸排目标与范围清单",
        detail: "拆分公司、方向、角色和关系目标，保留未知项。",
        requirement: "围绕四家公司和三个方向，不计算未知市场覆盖率。",
        doneAt: 2,
      },
      {
        id: "ecosystem",
        title: "梳理公司、组织与方向",
        detail: "形成公司生态、组织结构和关键方向的第一批结果。",
        requirement: "组织关系必须有来源和观察时间。",
        doneAt: 3,
      },
      {
        id: "people",
        title: "定位人物、角色与联系路径",
        detail: "结合候选人、论文、专利和公开资料识别人和关系。",
        requirement: "身份与关系不确定时进入待确认，不允许猜测。",
        doneAt: 4,
      },
      {
        id: "update",
        title: "审核并增量更新人才版图",
        detail: "按批次写入通过门禁的结果，冲突内容等待用户判断。",
        requirement: "每批更新说明新增、冲突、缺口和下一步动作。",
        doneAt: 5,
        waitAt: 4,
      },
      {
        id: "gaps",
        title: "确认待补充信息与下一步",
        detail: "明确还缺什么、能做什么和执行后的预期结果。",
        requirement: "不使用无法指导行动的抽象完成百分比。",
        doneAt: 6,
      },
    ],
    tasks: [
      {
        id: "mapping-org",
        title: "公司与组织方向研究",
        status: "完成",
        tone: "success",
        action: "4 家公司、7 个团队方向已形成可核验结构",
        duration: "4 分 26 秒",
      },
      {
        id: "mapping-people",
        title: "关键人物与身份检查",
        status: "完成",
        tone: "success",
        action: "30 位人物中 18 位已确认，11 位为线索，1 位身份冲突",
        duration: "6 分 11 秒",
      },
      {
        id: "mapping-relations",
        title: "人物关系与联系路径",
        status: "等待用户",
        tone: "warning",
        action: "9 条关系可写入，1 条冲突需要审核",
        duration: "2 分 48 秒",
      },
    ],
  },
  "career-linhao": {
    id: "career-linhao",
    type: "候选人求职",
    title: "林昊职业机会",
    object: "林昊 · 机器人学习负责人",
    prompt:
      "我确认要跟进林昊最近可能看机会这条信号。先看看他和系统里哪些岗位匹配，告诉我联系时应该重点确认什么；不要替我发消息，我会自己通过微信联系。",
    autoStopPhase: 3,
    maxPhase: 6,
    defaultAuth: "analysis",
    plan: [
      {
        id: "signal",
        title: "核验动向信号与资料新鲜度",
        detail: "说明触发依据、证据强弱、联系方式和待核实信息。",
        requirement: "信号只说明可能性，不把公开动态当成求职事实。",
        doneAt: 2,
      },
      {
        id: "match",
        title: "匹配系统内有效岗位",
        detail: "使用候选人和岗位最新版本执行角色门禁与匹配。",
        requirement: "不搜索公开市场职位，只判断 Hunter 中的有效岗位。",
        doneAt: 3,
      },
      {
        id: "review",
        title: "查看岗位建议与联系要点",
        detail: "比较分数、理由、风险、缺口和建议沟通重点。",
        requirement: "Hunter 不自动联系候选人。",
        doneAt: 4,
        waitAt: 3,
      },
      {
        id: "contact",
        title: "记录猎头联系结果",
        detail: "用户通过微信、电话或已有关系联系后补充结果。",
        requirement: "文字、文件和新简历均可作为补充信息。",
        doneAt: 6,
        waitAt: 4,
        externalAt: 5,
      },
      {
        id: "rematch",
        title: "更新档案并局部重新匹配",
        detail: "先显示档案变化与合并摘要，再重做受影响岗位。",
        requirement: "有合适岗位时由用户确认交给岗位招聘主线。",
        doneAt: 7,
      },
    ],
    tasks: [
      {
        id: "career-signal",
        title: "候选人动向信号核验",
        status: "完成",
        tone: "success",
        action: "2 条中等证据，求职意愿仍需猎头本人核实",
        duration: "36 秒",
      },
      {
        id: "career-match",
        title: "系统内岗位增量匹配",
        status: "完成",
        tone: "success",
        action: "7 个有效岗位中 3 个值得查看",
        duration: "1 分 22 秒",
      },
      {
        id: "career-contact",
        title: "等待猎头补充联系结果",
        status: "等待用户",
        tone: "warning",
        action: "Hunter 不自动发送消息，等待用户记录微信或电话结果",
        duration: "—",
      },
    ],
  },
};
