export const clientEvidence = [
  {
    source: "星澜机器人官网",
    finding: "过去 14 天新增 9 个机器人算法、平台研发和硬件岗位",
    freshness: "今天 09:12",
    confidence: "高可信",
    stance: "支持",
  },
  {
    source: "融资公告",
    finding: "完成 B+ 轮融资，公开用途包含北京研发团队扩张",
    freshness: "6 天前",
    confidence: "高可信",
    stance: "支持",
  },
  {
    source: "行业关系备注",
    finding: "原合作方反馈算法团队仍在扩充，但尚未确认外部猎头预算",
    freshness: "3 天前",
    confidence: "待确认",
    stance: "不确定",
  },
];

export const contactReviewRows = [
  {
    id: "contact-chenyu",
    name: "陈雨",
    role: "招聘负责人",
    company: "星澜机器人",
    category: "招聘负责人",
    phone: "138 **** 6217",
    email: "yu.chen@xinglan-robotics.com",
    source: "官网招聘邮箱、脉脉身份与用户关系备注交叉确认",
    confidence: "身份已确认",
    tone: "success",
    preferred: true,
  },
  {
    id: "contact-zhouqi",
    name: "周琪",
    role: "机器人算法 HRBP",
    company: "星澜机器人",
    category: "客户 HR",
    phone: "",
    email: "qi.zhou@xinglan-robotics.com",
    source: "官网招聘页面与公开职业资料",
    confidence: "身份已确认",
    tone: "success",
  },
  {
    id: "lead-vp-hr",
    name: "人力资源副总裁线索",
    role: "具体姓名尚未确认",
    company: "星澜机器人",
    category: "联系人线索",
    phone: "",
    email: "",
    source: "融资报道提到本轮招聘由人力资源负责人统筹",
    confidence: "身份待确认",
    tone: "warning",
  },
  {
    id: "contact-liujian",
    name: "刘健",
    role: "投资经理",
    company: "启程资本",
    category: "中间介绍人",
    phone: "",
    email: "",
    source: "用户已有联系人",
    confidence: "关系已确认",
    tone: "success",
  },
];

export const mappingCompanies = [
  {
    company: "星澜机器人",
    direction: "VLA 与机器人学习",
    organization: "具身智能中心 / 机器人学习组",
    people: 11,
    status: "核心团队已定位",
    tone: "success",
  },
  {
    company: "拓界机器人",
    direction: "操作策略与真机部署",
    organization: "智能操作部 / 策略学习团队",
    people: 8,
    status: "缺 1 位技术负责人",
    tone: "warning",
  },
  {
    company: "穹顶智能",
    direction: "多模态决策与数据闭环",
    organization: "具身算法平台",
    people: 6,
    status: "组织关系待确认",
    tone: "warning",
  },
  {
    company: "灵跃科技",
    direction: "灵巧操作与模仿学习",
    organization: "灵巧手算法组",
    people: 5,
    status: "本轮范围已覆盖",
    tone: "success",
  },
];

export const mappingPeople = [
  {
    id: "map-linhao",
    name: "林昊",
    role: "机器人学习负责人",
    company: "拓界机器人",
    identity: "已关联候选人",
    relation: "与周明远有共同论文及前同事关系",
    source: "论文、公开履历、Hunter 候选人档案",
    confidence: "已确认",
  },
  {
    id: "map-zhoumingyuan",
    name: "周明远",
    role: "具身智能算法总监",
    company: "穹顶智能",
    identity: "人物线索",
    relation: "曾与星澜机器人技术顾问共同申请专利",
    source: "专利、会议演讲与公司公开资料",
    confidence: "较高",
  },
  {
    id: "map-chenchuning",
    name: "陈楚宁",
    role: "VLA 算法负责人",
    company: "灵跃科技",
    identity: "已关联候选人",
    relation: "灵巧操作方向关键角色",
    source: "Hunter 候选人档案、GitHub 与论文",
    confidence: "已确认",
  },
  {
    id: "map-wangyi",
    name: "王奕（待确认）",
    role: "机器人学习研究员",
    company: "星澜机器人",
    identity: "身份需要确认",
    relation: "同名作者与公开职位信息可能属于同一人",
    source: "论文作者与公开招聘活动名单",
    confidence: "存在冲突",
  },
];

export const mappingRelationshipViews = [
  {
    id: "organization",
    label: "组织与方向",
    description: "公司、组织、方向、角色和人物的层级关系",
    summary: "当前聚焦星澜机器人 · 7 个对象 · 6 条关系",
    layout: "hierarchy",
    defaultSelection: { kind: "node", id: "org-vla-team" },
    nodes: [
      {
        id: "org-xinglan",
        label: "星澜机器人",
        meta: "正式公司",
        kind: "company",
        x: 36,
        y: 196,
        status: "已确认",
        tone: "success",
        summary: "本版图的核心目标公司，重点覆盖 VLA 与机器人学习。",
        facts: [
          ["版图作用", "核心目标公司"],
          ["观察时间", "今天 09:18"],
        ],
        evidence: ["公司官网", "融资公告", "用户确认范围"],
      },
      {
        id: "org-center",
        label: "具身智能中心",
        meta: "一级组织",
        kind: "organization",
        x: 246,
        y: 196,
        status: "已确认",
        tone: "success",
        summary: "负责具身算法、机器人学习和真机数据闭环。",
        facts: [
          ["所属公司", "星澜机器人"],
          ["观察时间", "今天 09:21"],
        ],
        evidence: ["官网团队介绍", "公开招聘页"],
      },
      {
        id: "org-vla-team",
        label: "VLA 算法组",
        meta: "方向团队 · 6 人",
        kind: "organization",
        x: 456,
        y: 92,
        status: "已确认",
        tone: "success",
        summary: "负责视觉语言动作模型、数据闭环和真机策略部署。",
        facts: [
          ["重点方向", "VLA、数据闭环"],
          ["关键角色", "负责人、研究员"],
        ],
        evidence: ["岗位页面", "团队论文", "会议分享"],
      },
      {
        id: "org-learning-team",
        label: "机器人学习组",
        meta: "方向团队 · 5 人",
        kind: "organization",
        x: 456,
        y: 300,
        status: "已确认",
        tone: "success",
        summary: "负责模仿学习、强化学习和仿真到真机迁移。",
        facts: [
          ["重点方向", "机器人学习"],
          ["关键角色", "负责人、算法工程师"],
        ],
        evidence: ["公开招聘页", "论文作者机构"],
      },
      {
        id: "org-zhaoxingyu",
        label: "赵星羽",
        meta: "VLA 算法负责人",
        kind: "person",
        x: 714,
        y: 52,
        status: "已关联候选人",
        tone: "success",
        summary: "目标人才，负责 VLA 算法与真机部署。",
        facts: [
          ["当前公司", "星澜机器人"],
          ["版图分类", "目标人才"],
        ],
        evidence: ["Hunter 候选人档案", "公开履历"],
      },
      {
        id: "org-wangyi",
        label: "王奕",
        meta: "机器人学习研究员",
        kind: "person",
        x: 714,
        y: 142,
        status: "身份待确认",
        tone: "warning",
        summary: "论文作者与公开活动名单可能属于同一人，单位时间线存在冲突。",
        facts: [
          ["版图分类", "人物线索"],
          ["冲突项", "2024 年单位信息"],
        ],
        evidence: ["论文作者信息", "公司公开活动名单"],
        decisionKey: "wangyi",
      },
      {
        id: "org-hejing",
        label: "何静",
        meta: "强化学习研究员",
        kind: "person",
        x: 714,
        y: 300,
        status: "人物线索",
        tone: "info",
        summary: "机器人学习方向人物线索，身份尚未达到正式候选人门槛。",
        facts: [
          ["版图分类", "目标人才"],
          ["待补充", "稳定公开身份"],
        ],
        evidence: ["团队论文", "开源项目贡献记录"],
      },
    ],
    edges: [
      {
        id: "org-e1",
        source: "org-xinglan",
        target: "org-center",
        label: "下属组织",
        status: "已确认",
        tone: "success",
        observedAt: "今天 09:21",
        evidence: ["官网团队介绍"],
      },
      {
        id: "org-e2",
        source: "org-center",
        target: "org-vla-team",
        label: "下属团队",
        status: "已确认",
        tone: "success",
        observedAt: "今天 09:22",
        evidence: ["公开招聘页", "会议分享"],
      },
      {
        id: "org-e3",
        source: "org-center",
        target: "org-learning-team",
        label: "下属团队",
        status: "已确认",
        tone: "success",
        observedAt: "今天 09:22",
        evidence: ["公开招聘页"],
      },
      {
        id: "org-e4",
        source: "org-vla-team",
        target: "org-zhaoxingyu",
        label: "负责",
        status: "已确认",
        tone: "success",
        observedAt: "今天 09:31",
        evidence: ["Hunter 候选人档案", "公开履历"],
      },
      {
        id: "org-e5",
        source: "org-vla-team",
        target: "org-wangyi",
        label: "疑似任职",
        status: "待确认",
        tone: "warning",
        observedAt: "今天 09:35",
        evidence: ["论文作者信息", "活动名单"],
        decisionKey: "wangyi",
      },
      {
        id: "org-e6",
        source: "org-learning-team",
        target: "org-hejing",
        label: "团队成员",
        status: "较高可信",
        tone: "info",
        observedAt: "今天 09:36",
        evidence: ["团队论文", "开源项目"],
      },
    ],
  },
  {
    id: "ecosystem",
    label: "公司生态",
    description: "目标公司之间的竞争、合作、上下游和人才流动",
    summary: "5 家公司或机构 · 7 条生态关系 · 2 条待核验",
    layout: "network",
    defaultSelection: { kind: "edge", id: "eco-e2" },
    nodes: [
      {
        id: "eco-xinglan",
        label: "星澜机器人",
        meta: "VLA / 机器人学习",
        kind: "company",
        x: 372,
        y: 192,
        status: "核心公司",
        tone: "success",
        summary: "当前版图核心公司。",
        facts: [
          ["关键人物", "11 位"],
          ["方向", "VLA、机器人学习"],
        ],
        evidence: ["人才版图范围"],
      },
      {
        id: "eco-tuojie",
        label: "拓界机器人",
        meta: "操作策略 / 真机部署",
        kind: "company",
        x: 82,
        y: 76,
        status: "目标公司",
        tone: "info",
        summary: "操作策略和真机部署方向目标公司。",
        facts: [
          ["关键人物", "8 位"],
          ["当前缺口", "技术负责人"],
        ],
        evidence: ["官网", "公开招聘页"],
      },
      {
        id: "eco-qiongding",
        label: "穹顶智能",
        meta: "多模态决策",
        kind: "company",
        x: 86,
        y: 324,
        status: "关系待确认",
        tone: "warning",
        summary: "具身算法平台已确认，具体汇报和生态关系待核验。",
        facts: [
          ["关键人物", "6 位"],
          ["当前缺口", "组织上下级"],
        ],
        evidence: ["会议资料", "招聘页面"],
        decisionKey: "qiongding",
      },
      {
        id: "eco-lingyue",
        label: "灵跃科技",
        meta: "灵巧操作",
        kind: "company",
        x: 684,
        y: 76,
        status: "目标公司",
        tone: "success",
        summary: "灵巧操作与模仿学习方向目标公司。",
        facts: [
          ["关键人物", "5 位"],
          ["方向", "灵巧操作"],
        ],
        evidence: ["官网", "专利"],
      },
      {
        id: "eco-shlab",
        label: "上海人工智能实验室",
        meta: "研究机构",
        kind: "organization",
        x: 674,
        y: 324,
        status: "合作机构",
        tone: "info",
        summary: "与多家目标公司存在论文和人才合作。",
        facts: [
          ["关系作用", "研究合作与人才来源"],
          ["观察时间", "本月"],
        ],
        evidence: ["论文作者机构", "联合项目公告"],
      },
    ],
    edges: [
      {
        id: "eco-e1",
        source: "eco-tuojie",
        target: "eco-xinglan",
        label: "人才流向",
        status: "系统归纳",
        tone: "info",
        observedAt: "近 24 个月",
        evidence: ["6 份公开履历"],
      },
      {
        id: "eco-e2",
        source: "eco-xinglan",
        target: "eco-lingyue",
        label: "竞争 · VLA",
        status: "已确认",
        tone: "success",
        observedAt: "本季度",
        evidence: ["产品方向", "招聘岗位", "用户确认"],
      },
      {
        id: "eco-e3",
        source: "eco-qiongding",
        target: "eco-xinglan",
        label: "技术路线相近",
        status: "待确认",
        tone: "warning",
        observedAt: "本月",
        evidence: ["公开演讲", "岗位描述"],
        decisionKey: "qiongding",
      },
      {
        id: "eco-e4",
        source: "eco-shlab",
        target: "eco-xinglan",
        label: "联合研究",
        status: "已确认",
        tone: "success",
        observedAt: "2025 至今",
        evidence: ["联合论文 4 篇"],
      },
      {
        id: "eco-e5",
        source: "eco-shlab",
        target: "eco-lingyue",
        label: "人才来源",
        status: "较高可信",
        tone: "info",
        observedAt: "近 36 个月",
        evidence: ["公开履历 3 份"],
      },
      {
        id: "eco-e6",
        source: "eco-tuojie",
        target: "eco-qiongding",
        label: "竞争 · 操作策略",
        status: "较高可信",
        tone: "info",
        observedAt: "本季度",
        evidence: ["招聘岗位", "产品发布"],
      },
      {
        id: "eco-e7",
        source: "eco-lingyue",
        target: "eco-xinglan",
        label: "硬件合作线索",
        status: "待核验",
        tone: "warning",
        observedAt: "3 个月前",
        evidence: ["行业关系备注"],
      },
    ],
  },
  {
    id: "direction-role",
    label: "方向与角色",
    description: "横向比较不同公司覆盖的技术方向、关键角色和当前缺口",
    summary: "4 个方向 · 3 类关键角色 · 2 个明确缺口",
    layout: "layered",
    defaultSelection: { kind: "node", id: "matrix-vla" },
    nodes: [
      {
        id: "matrix-xinglan",
        label: "星澜机器人",
        meta: "目标公司 · 11 位人物",
        kind: "company",
        x: 42,
        y: 62,
        status: "已确认",
        tone: "success",
        summary: "重点覆盖 VLA 和机器人学习。",
        facts: [
          ["已知组织", "具身智能中心"],
          ["当前缺口", "数据闭环负责人"],
        ],
        evidence: ["公司组织资料", "人才版图人物"],
      },
      {
        id: "matrix-tuojie",
        label: "拓界机器人",
        meta: "目标公司 · 8 位人物",
        kind: "company",
        x: 42,
        y: 202,
        status: "已确认",
        tone: "success",
        summary: "重点覆盖操作策略和真机部署。",
        facts: [
          ["已知组织", "智能操作中心"],
          ["当前缺口", "技术负责人"],
        ],
        evidence: ["招聘页面", "公开履历"],
      },
      {
        id: "matrix-lingyue",
        label: "灵跃科技",
        meta: "目标公司 · 5 位人物",
        kind: "company",
        x: 42,
        y: 342,
        status: "已确认",
        tone: "success",
        summary: "重点覆盖灵巧操作和模仿学习。",
        facts: [
          ["已知组织", "灵巧操作实验室"],
          ["当前缺口", "数据工程负责人"],
        ],
        evidence: ["官网", "论文与专利"],
      },
      {
        id: "matrix-vla",
        label: "VLA",
        meta: "技术方向 · 3 家覆盖",
        kind: "organization",
        x: 362,
        y: 38,
        status: "核心方向",
        tone: "info",
        summary: "三家公司均有布局，但职责边界和成熟度不同。",
        facts: [
          ["已知人物", "赵星羽、陈楚宁等 7 位"],
          ["招聘热度", "较高"],
        ],
        evidence: ["组织资料", "招聘岗位", "代表成果"],
      },
      {
        id: "matrix-policy",
        label: "操作策略",
        meta: "技术方向 · 2 家覆盖",
        kind: "organization",
        x: 362,
        y: 154,
        status: "核心方向",
        tone: "info",
        summary: "拓界和穹顶的重点技术方向。",
        facts: [
          ["已知人物", "林昊、周明远等 6 位"],
          ["招聘热度", "较高"],
        ],
        evidence: ["招聘岗位", "技术分享"],
      },
      {
        id: "matrix-learning",
        label: "机器人学习",
        meta: "技术方向 · 3 家覆盖",
        kind: "organization",
        x: 362,
        y: 270,
        status: "核心方向",
        tone: "info",
        summary: "覆盖模仿学习、强化学习和仿真迁移。",
        facts: [
          ["已知人物", "9 位"],
          ["招聘热度", "稳定"],
        ],
        evidence: ["论文", "公开履历"],
      },
      {
        id: "matrix-dexterity",
        label: "灵巧操作",
        meta: "技术方向 · 1 家重点",
        kind: "organization",
        x: 362,
        y: 382,
        status: "重点方向",
        tone: "info",
        summary: "灵跃科技的差异化方向。",
        facts: [
          ["已知人物", "陈楚宁等 4 位"],
          ["当前缺口", "数据工程负责人"],
        ],
        evidence: ["专利", "产品发布"],
      },
      {
        id: "matrix-head",
        label: "方向负责人",
        meta: "关键角色",
        kind: "person",
        x: 710,
        y: 58,
        status: "覆盖 3 / 4",
        tone: "warning",
        summary: "操作策略方向负责人仍缺少稳定身份。",
        facts: [
          ["已确认", "3 位"],
          ["待补充", "拓界技术负责人"],
        ],
        evidence: ["人物身份与组织关系"],
      },
      {
        id: "matrix-researcher",
        label: "核心研究员",
        meta: "关键角色",
        kind: "person",
        x: 710,
        y: 198,
        status: "覆盖 12 位",
        tone: "success",
        summary: "已形成可按方向和公司复用的人物池。",
        facts: [
          ["正式候选人", "7 位"],
          ["人物线索", "5 位"],
        ],
        evidence: ["候选人档案", "论文作者", "专利发明人"],
      },
      {
        id: "matrix-data",
        label: "数据闭环负责人",
        meta: "关键角色",
        kind: "person",
        x: 710,
        y: 338,
        status: "缺口明显",
        tone: "warning",
        summary: "三家公司均缺少可以确认的数据闭环负责人。",
        facts: [
          ["稳定身份", "0 位"],
          ["建议动作", "从岗位、论文与开源项目继续探索"],
        ],
        evidence: ["组织角色缺口"],
      },
    ],
    edges: [
      {
        id: "matrix-e1",
        source: "matrix-xinglan",
        target: "matrix-vla",
        label: "重点布局",
        status: "已确认",
        tone: "success",
        observedAt: "当前",
        evidence: ["组织资料", "招聘岗位"],
      },
      {
        id: "matrix-e2",
        source: "matrix-xinglan",
        target: "matrix-learning",
        label: "团队方向",
        status: "已确认",
        tone: "success",
        observedAt: "当前",
        evidence: ["组织资料"],
      },
      {
        id: "matrix-e3",
        source: "matrix-tuojie",
        target: "matrix-policy",
        label: "重点布局",
        status: "已确认",
        tone: "success",
        observedAt: "当前",
        evidence: ["招聘岗位", "技术分享"],
      },
      {
        id: "matrix-e4",
        source: "matrix-tuojie",
        target: "matrix-learning",
        label: "团队方向",
        status: "较高可信",
        tone: "info",
        observedAt: "当前",
        evidence: ["公开履历"],
      },
      {
        id: "matrix-e5",
        source: "matrix-lingyue",
        target: "matrix-vla",
        label: "产品方向",
        status: "已确认",
        tone: "success",
        observedAt: "当前",
        evidence: ["产品发布"],
      },
      {
        id: "matrix-e6",
        source: "matrix-lingyue",
        target: "matrix-dexterity",
        label: "重点布局",
        status: "已确认",
        tone: "success",
        observedAt: "当前",
        evidence: ["专利", "招聘岗位"],
      },
      {
        id: "matrix-e7",
        source: "matrix-vla",
        target: "matrix-head",
        label: "需要角色",
        status: "已确认",
        tone: "success",
        observedAt: "当前",
        evidence: ["组织角色"],
      },
      {
        id: "matrix-e8",
        source: "matrix-learning",
        target: "matrix-researcher",
        label: "核心人才",
        status: "已确认",
        tone: "success",
        observedAt: "当前",
        evidence: ["人物与方向关系"],
      },
      {
        id: "matrix-e9",
        source: "matrix-dexterity",
        target: "matrix-data",
        label: "招聘缺口",
        status: "待补充",
        tone: "warning",
        observedAt: "当前",
        evidence: ["组织角色缺口"],
      },
    ],
  },
  {
    id: "people",
    label: "人物关系",
    description: "围绕目标人物查看任职、合作、师生和已有关系",
    summary: "当前聚焦 6 / 30 位人物 · 7 条关系",
    layout: "network",
    defaultSelection: { kind: "node", id: "people-linhao" },
    nodes: [
      {
        id: "people-linhao",
        label: "林昊",
        meta: "拓界 · 机器人学习负责人",
        kind: "person",
        x: 374,
        y: 188,
        status: "已关联候选人",
        tone: "success",
        summary: "目标人才，在 Hunter 中已有完整候选人档案。",
        facts: [
          ["版图分类", "目标人才"],
          ["可联系", "已有手机和微信沟通记录"],
        ],
        evidence: ["Hunter 候选人档案", "公开履历"],
      },
      {
        id: "people-zhou",
        label: "周明远",
        meta: "穹顶 · 算法总监",
        kind: "person",
        x: 88,
        y: 76,
        status: "人物线索",
        tone: "info",
        summary: "关系人物兼目标人才线索。",
        facts: [
          ["版图分类", "目标人才"],
          ["待补充", "稳定公开身份"],
        ],
        evidence: ["专利", "会议演讲"],
      },
      {
        id: "people-zhao",
        label: "赵星羽",
        meta: "星澜 · VLA 负责人",
        kind: "person",
        x: 672,
        y: 70,
        status: "已关联候选人",
        tone: "success",
        summary: "星澜 VLA 算法关键负责人。",
        facts: [
          ["版图分类", "目标人才"],
          ["可联系", "可通过陈雨或刘健"],
        ],
        evidence: ["候选人档案", "公开履历"],
      },
      {
        id: "people-chen",
        label: "陈楚宁",
        meta: "灵跃 · VLA 负责人",
        kind: "person",
        x: 686,
        y: 318,
        status: "已关联候选人",
        tone: "success",
        summary: "灵巧操作方向关键人物。",
        facts: [
          ["版图分类", "目标人才"],
          ["可联系", "已有邮箱"],
        ],
        evidence: ["候选人档案", "GitHub", "论文"],
      },
      {
        id: "people-wang",
        label: "王奕",
        meta: "星澜 · 研究员",
        kind: "person",
        x: 382,
        y: 350,
        status: "身份待确认",
        tone: "warning",
        summary: "存在同名与任职时间冲突。",
        facts: [
          ["版图分类", "人物线索"],
          ["冲突", "2024 年任职单位"],
        ],
        evidence: ["论文作者", "活动名单"],
        decisionKey: "wangyi",
      },
      {
        id: "people-liujian",
        label: "刘健",
        meta: "启程资本 · 投资经理",
        kind: "person",
        x: 74,
        y: 322,
        status: "用户确认关系",
        tone: "success",
        summary: "猎头已有联系人，可作为星澜机器人的引荐路径。",
        facts: [
          ["版图分类", "关系人物"],
          ["联系方式", "保存于联系人档案"],
        ],
        evidence: ["用户确认"],
      },
    ],
    edges: [
      {
        id: "people-e1",
        source: "people-linhao",
        target: "people-zhou",
        label: "前同事",
        status: "已确认",
        tone: "success",
        observedAt: "2019 至 2022",
        evidence: ["两人公开履历"],
      },
      {
        id: "people-e2",
        source: "people-linhao",
        target: "people-zhao",
        label: "共同作者",
        status: "已确认",
        tone: "success",
        observedAt: "2023",
        evidence: ["共同论文 2 篇"],
      },
      {
        id: "people-e3",
        source: "people-linhao",
        target: "people-chen",
        label: "开源协作",
        status: "较高可信",
        tone: "info",
        observedAt: "2024",
        evidence: ["GitHub 项目贡献"],
      },
      {
        id: "people-e4",
        source: "people-wang",
        target: "people-zhao",
        label: "疑似同团队",
        status: "待确认",
        tone: "warning",
        observedAt: "2024",
        evidence: ["活动名单", "论文机构"],
        decisionKey: "wangyi",
      },
      {
        id: "people-e5",
        source: "people-liujian",
        target: "people-zhao",
        label: "可引荐",
        status: "用户确认",
        tone: "success",
        observedAt: "今天",
        evidence: ["用户关系备注"],
      },
      {
        id: "people-e6",
        source: "people-zhou",
        target: "people-wang",
        label: "共同发明人",
        status: "已确认",
        tone: "success",
        observedAt: "2022",
        evidence: ["专利 CN2022…1781"],
      },
      {
        id: "people-e7",
        source: "people-zhao",
        target: "people-chen",
        label: "同方向同行",
        status: "系统归纳",
        tone: "info",
        observedAt: "当前",
        evidence: ["研究方向与代表成果"],
      },
    ],
  },
  {
    id: "talent-flow",
    label: "人才流动",
    description: "按公开履历汇总目标公司和研究机构之间的人才流向",
    summary: "近 24 个月 · 18 条可核验流动记录 · 4 条主要流向",
    layout: "flow",
    defaultSelection: { kind: "edge", id: "flow-e1" },
    nodes: [
      {
        id: "flow-shlab",
        label: "上海人工智能实验室",
        meta: "流出 7 人",
        kind: "organization",
        x: 56,
        y: 58,
        status: "来源机构",
        tone: "info",
        summary: "目标公司较重要的研究人才来源。",
        facts: [
          ["流出样本", "7 人"],
          ["主要方向", "VLA、机器人学习"],
        ],
        evidence: ["公开履历", "论文机构"],
      },
      {
        id: "flow-tuoji",
        label: "拓界机器人",
        meta: "流出 6 人",
        kind: "company",
        x: 56,
        y: 198,
        status: "人才来源",
        tone: "info",
        summary: "近两年有多位算法人才流向同行。",
        facts: [
          ["流出样本", "6 人"],
          ["主要方向", "操作策略"],
        ],
        evidence: ["公开履历"],
      },
      {
        id: "flow-university",
        label: "清华 / 上交实验室",
        meta: "流出 5 人",
        kind: "organization",
        x: 56,
        y: 338,
        status: "人才来源",
        tone: "info",
        summary: "应届博士和研究员的主要学术来源。",
        facts: [
          ["流出样本", "5 人"],
          ["主要方向", "多模态、控制"],
        ],
        evidence: ["论文履历", "公开个人主页"],
      },
      {
        id: "flow-xinglan",
        label: "星澜机器人",
        meta: "流入 9 人",
        kind: "company",
        x: 716,
        y: 58,
        status: "主要流入",
        tone: "success",
        summary: "近两年在 VLA 和机器人学习方向持续吸引人才。",
        facts: [
          ["流入样本", "9 人"],
          ["主要来源", "上海 AI Lab、拓界"],
        ],
        evidence: ["9 份公开履历"],
      },
      {
        id: "flow-lingyue",
        label: "灵跃科技",
        meta: "流入 5 人",
        kind: "company",
        x: 716,
        y: 198,
        status: "主要流入",
        tone: "success",
        summary: "灵巧操作团队扩张明显。",
        facts: [
          ["流入样本", "5 人"],
          ["主要来源", "高校实验室、星澜"],
        ],
        evidence: ["5 份公开履历"],
      },
      {
        id: "flow-qiongding",
        label: "穹顶智能",
        meta: "流入 4 人",
        kind: "company",
        x: 716,
        y: 338,
        status: "稳定流入",
        tone: "success",
        summary: "操作策略和多模态决策方向有稳定流入。",
        facts: [
          ["流入样本", "4 人"],
          ["主要来源", "拓界、高校"],
        ],
        evidence: ["4 份公开履历"],
      },
    ],
    edges: [
      {
        id: "flow-e1",
        source: "flow-shlab",
        target: "flow-xinglan",
        label: "6 人",
        status: "已核验履历",
        tone: "success",
        observedAt: "近 24 个月",
        evidence: ["6 份公开履历"],
        width: 9,
      },
      {
        id: "flow-e2",
        source: "flow-tuoji",
        target: "flow-xinglan",
        label: "3 人",
        status: "已核验履历",
        tone: "info",
        observedAt: "近 24 个月",
        evidence: ["3 份公开履历"],
        width: 6,
      },
      {
        id: "flow-e3",
        source: "flow-tuoji",
        target: "flow-qiongding",
        label: "3 人",
        status: "已核验履历",
        tone: "info",
        observedAt: "近 24 个月",
        evidence: ["3 份公开履历"],
        width: 6,
      },
      {
        id: "flow-e4",
        source: "flow-university",
        target: "flow-lingyue",
        label: "4 人",
        status: "已核验履历",
        tone: "success",
        observedAt: "近 24 个月",
        evidence: ["4 份公开履历"],
        width: 7,
      },
      {
        id: "flow-e5",
        source: "flow-shlab",
        target: "flow-lingyue",
        label: "1 人",
        status: "已核验履历",
        tone: "info",
        observedAt: "近 24 个月",
        evidence: ["1 份公开履历"],
        width: 3,
      },
      {
        id: "flow-e6",
        source: "flow-university",
        target: "flow-qiongding",
        label: "1 人",
        status: "已核验履历",
        tone: "info",
        observedAt: "近 24 个月",
        evidence: ["1 份公开履历"],
        width: 3,
      },
    ],
  },
  {
    id: "contact-path",
    label: "联系路径",
    description: "只显示到目标人物的可解释路径和每一段关系",
    summary: "赵星羽 · 2 条可用路径 · 最短 2 段",
    layout: "path",
    defaultSelection: { kind: "edge", id: "path-e2" },
    nodes: [
      {
        id: "path-user",
        label: "猎头于一凡",
        meta: "当前用户",
        kind: "user",
        x: 42,
        y: 188,
        status: "起点",
        tone: "info",
        summary: "当前联系路径的起点。",
        facts: [
          ["可用渠道", "电话、微信、邮件"],
          ["范围", "仅当前工作空间"],
        ],
        evidence: ["当前用户"],
      },
      {
        id: "path-liu",
        label: "刘健",
        meta: "已有联系人 · 投资经理",
        kind: "person",
        x: 266,
        y: 88,
        status: "关系已确认",
        tone: "success",
        summary: "用户已有联系人，可以请求引荐。",
        facts: [
          ["联系方式", "已保存"],
          ["最近核实", "今天"],
        ],
        evidence: ["用户确认"],
      },
      {
        id: "path-chenyu",
        label: "陈雨",
        meta: "星澜招聘负责人",
        kind: "person",
        x: 270,
        y: 314,
        status: "身份已确认",
        tone: "success",
        summary: "星澜招聘负责人，具备已核验手机和邮箱。",
        facts: [
          ["手机", "138 **** 6217"],
          ["邮箱", "yu.chen@xinglan-robotics.com"],
        ],
        evidence: ["官网", "公开职业资料"],
      },
      {
        id: "path-zhao",
        label: "赵星羽",
        meta: "目标人物 · VLA 负责人",
        kind: "person",
        x: 718,
        y: 188,
        status: "目标人才",
        tone: "success",
        summary: "当前联系路径的目标人物。",
        facts: [
          ["直接联系方式", "尚未掌握"],
          ["路径建议", "优先通过刘健引荐"],
        ],
        evidence: ["人才版图人物关系"],
      },
      {
        id: "path-founder",
        label: "星澜创始人",
        meta: "关系人物",
        kind: "person",
        x: 494,
        y: 76,
        status: "公开关系",
        tone: "info",
        summary: "刘健曾参与公司融资，可通过创始人形成间接引荐。",
        facts: [
          ["路径作用", "间接引荐"],
          ["关系时效", "2024 年融资后待核实"],
        ],
        evidence: ["融资公告", "用户关系备注"],
      },
      {
        id: "path-team",
        label: "具身智能中心",
        meta: "目标组织",
        kind: "organization",
        x: 504,
        y: 326,
        status: "组织已确认",
        tone: "success",
        summary: "陈雨负责该组织的招聘协作。",
        facts: [
          ["所属公司", "星澜机器人"],
          ["目标人物", "赵星羽"],
        ],
        evidence: ["招聘页面", "组织资料"],
      },
    ],
    edges: [
      {
        id: "path-e1",
        source: "path-user",
        target: "path-liu",
        label: "已有联系人",
        status: "用户确认",
        tone: "success",
        observedAt: "今天",
        evidence: ["联系人档案"],
      },
      {
        id: "path-e2",
        source: "path-liu",
        target: "path-founder",
        label: "投资关系",
        status: "已确认",
        tone: "success",
        observedAt: "2024",
        evidence: ["融资公告", "用户确认"],
      },
      {
        id: "path-e3",
        source: "path-founder",
        target: "path-zhao",
        label: "同公司引荐",
        status: "待联系",
        tone: "info",
        observedAt: "当前",
        evidence: ["公司与组织关系"],
      },
      {
        id: "path-e4",
        source: "path-user",
        target: "path-chenyu",
        label: "已有邮箱",
        status: "可直接联系",
        tone: "success",
        observedAt: "今天",
        evidence: ["联系人档案"],
      },
      {
        id: "path-e5",
        source: "path-chenyu",
        target: "path-team",
        label: "招聘协作",
        status: "已确认",
        tone: "success",
        observedAt: "当前",
        evidence: ["招聘页面"],
      },
      {
        id: "path-e6",
        source: "path-team",
        target: "path-zhao",
        label: "组织内关系",
        status: "已确认",
        tone: "success",
        observedAt: "当前",
        evidence: ["组织资料", "公开履历"],
      },
    ],
  },
  {
    id: "academic",
    label: "学术脉络",
    description: "机构、人物、论文和专利之间的原始成果关系",
    summary: "聚焦 3 位人物 · 2 项成果 · 1 家研究机构",
    layout: "layered",
    defaultSelection: { kind: "node", id: "academic-paper" },
    nodes: [
      {
        id: "academic-shlab",
        label: "上海人工智能实验室",
        meta: "研究机构",
        kind: "organization",
        x: 44,
        y: 188,
        status: "机构已确认",
        tone: "success",
        summary: "具身智能方向的重要研究机构。",
        facts: [
          ["相关成果", "8 篇论文"],
          ["相关人物", "12 位"],
        ],
        evidence: ["OpenAlex 机构身份", "论文署名"],
      },
      {
        id: "academic-paper",
        label: "Embodied VLA for…",
        meta: "论文 · 2025",
        kind: "paper",
        x: 296,
        y: 82,
        status: "已入库论文",
        tone: "info",
        summary: "讨论 VLA 在真机操作中的数据闭环和泛化。",
        facts: [
          ["作者", "赵星羽、林昊等 5 人"],
          ["机构", "上海 AI Lab、星澜机器人"],
        ],
        evidence: ["OpenAlex", "论文 PDF"],
      },
      {
        id: "academic-patent",
        label: "机器人策略迁移方法",
        meta: "专利 · CN2022…1781",
        kind: "patent",
        x: 296,
        y: 316,
        status: "已入库专利",
        tone: "info",
        summary: "涉及机器人策略从仿真到真机的迁移方法。",
        facts: [
          ["发明人", "周明远、王奕等 4 人"],
          ["申请人", "穹顶智能"],
        ],
        evidence: ["国家知识产权公开数据"],
      },
      {
        id: "academic-zhao",
        label: "赵星羽",
        meta: "论文作者",
        kind: "person",
        x: 604,
        y: 52,
        status: "身份已确认",
        tone: "success",
        summary: "论文作者身份已与正式候选人关联。",
        facts: [
          ["成果关系", "论文作者"],
          ["当前公司", "星澜机器人"],
        ],
        evidence: ["稳定作者身份", "候选人档案"],
      },
      {
        id: "academic-lin",
        label: "林昊",
        meta: "论文作者",
        kind: "person",
        x: 604,
        y: 166,
        status: "身份已确认",
        tone: "success",
        summary: "论文作者身份已与正式候选人关联。",
        facts: [
          ["成果关系", "论文作者"],
          ["当前公司", "拓界机器人"],
        ],
        evidence: ["ORCID", "候选人档案"],
      },
      {
        id: "academic-zhou",
        label: "周明远",
        meta: "专利发明人",
        kind: "person",
        x: 604,
        y: 292,
        status: "人物线索",
        tone: "info",
        summary: "发明人身份尚未转为正式候选人。",
        facts: [
          ["成果关系", "专利发明人"],
          ["当前公司", "穹顶智能"],
        ],
        evidence: ["专利发明人信息", "会议资料"],
      },
      {
        id: "academic-wang",
        label: "王奕",
        meta: "专利发明人",
        kind: "person",
        x: 604,
        y: 394,
        status: "身份待确认",
        tone: "warning",
        summary: "同名身份与论文单位时间线存在冲突。",
        facts: [
          ["成果关系", "专利发明人"],
          ["待确认", "是否为星澜王奕"],
        ],
        evidence: ["专利", "论文作者信息"],
        decisionKey: "wangyi",
      },
      {
        id: "academic-xinglan",
        label: "星澜机器人",
        meta: "作者当前公司",
        kind: "company",
        x: 790,
        y: 104,
        status: "公司已确认",
        tone: "success",
        summary: "赵星羽当前任职公司。",
        facts: [
          ["关系来源", "候选人工作经历"],
          ["观察时间", "当前"],
        ],
        evidence: ["候选人档案"],
      },
    ],
    edges: [
      {
        id: "academic-e1",
        source: "academic-shlab",
        target: "academic-paper",
        label: "署名机构",
        status: "已确认",
        tone: "success",
        observedAt: "2025",
        evidence: ["论文署名"],
      },
      {
        id: "academic-e2",
        source: "academic-paper",
        target: "academic-zhao",
        label: "作者",
        status: "已确认",
        tone: "success",
        observedAt: "2025",
        evidence: ["稳定作者身份"],
      },
      {
        id: "academic-e3",
        source: "academic-paper",
        target: "academic-lin",
        label: "作者",
        status: "已确认",
        tone: "success",
        observedAt: "2025",
        evidence: ["ORCID"],
      },
      {
        id: "academic-e4",
        source: "academic-patent",
        target: "academic-zhou",
        label: "发明人",
        status: "已确认",
        tone: "success",
        observedAt: "2022",
        evidence: ["专利公开数据"],
      },
      {
        id: "academic-e5",
        source: "academic-patent",
        target: "academic-wang",
        label: "发明人",
        status: "待确认",
        tone: "warning",
        observedAt: "2022",
        evidence: ["专利公开数据"],
        decisionKey: "wangyi",
      },
      {
        id: "academic-zhao-company",
        source: "academic-zhao",
        target: "academic-xinglan",
        label: "当前任职",
        status: "已确认",
        tone: "success",
        observedAt: "当前",
        evidence: ["候选人档案"],
      },
    ],
  },
];

export const careerMatches = [
  {
    id: "match-xinglan-vla",
    title: "具身智能 VLA 算法负责人",
    company: "星澜机器人",
    location: "北京",
    status: "招聘中",
    score: 92,
    recommendation: "优先沟通",
    tone: "success",
    reason: "VLA 产品落地、机器人学习和 8 人团队管理经历与岗位高度重合。",
    risk: "林昊当前总包可能高于岗位已知区间，且尚未确认北京长期意愿。",
    gaps: "需核实到岗时间、薪酬预期和是否接受从平台团队转入业务团队。",
    talkingPoint:
      "先确认其下一阶段是否希望继续带团队，再介绍星澜的真机数据闭环和团队空间。",
  },
  {
    id: "match-tuoji-policy",
    title: "机器人策略学习技术总监",
    company: "拓界机器人",
    location: "上海",
    status: "招聘中",
    score: 84,
    recommendation: "可以了解",
    tone: "info",
    reason: "策略学习与仿真到真机经验匹配，且熟悉现有团队技术栈。",
    risk: "岗位更偏跨团队平台建设，管理范围和决策权尚未完全确认。",
    gaps: "需确认异地意愿和岗位是否允许北京办公。",
    talkingPoint: "可先询问他对平台型岗位和上海工作安排的接受度。",
  },
  {
    id: "match-lingyue-head",
    title: "灵巧操作算法负责人",
    company: "灵跃科技",
    location: "深圳",
    status: "已暂停",
    score: 77,
    recommendation: "暂不优先",
    tone: "warning",
    reason: "机器人学习能力可迁移，但灵巧手专项经历不是其最强方向。",
    risk: "岗位目前暂停，且地点与候选人已知偏好差异较大。",
    gaps: "等待岗位恢复并补充团队职责后再判断。",
    talkingPoint: "不建议本轮主动推荐，只可作为后续备选方向。",
  },
];

export const businessScenarios = {
  "client-xinglan": {
    id: "client-xinglan",
    type: "客户开发",
    title: "星澜机器人招聘合作",
    object: "星澜机器人 · 具身智能与机器人研发",
    prompt:
      "星澜机器人刚完成新一轮融资，最近也在扩机器人团队。帮我判断这家公司值不值得跟进，找到合适的招聘负责人和可用联系方式；如果确实有招聘需求，先整理成招聘机会，不要直接创建岗位。",
    autoStopPhase: 3,
    maxPhase: 6,
    defaultAuth: "confirm",
    plan: [
      {
        id: "verify",
        title: "核验公司与招聘信号",
        detail: "交叉检查融资、招聘变化、组织扩张和反向证据。",
        requirement: "先判断是否值得开发，不把融资新闻直接当成招聘需求。",
        doneAt: 2,
      },
      {
        id: "contacts",
        title: "查找联系人与可用联系路径",
        detail: "识别招聘负责人、HRBP 和已有关系，并核验手机或邮箱。",
        requirement:
          "必须说明联系人数量、具备手机或邮箱的人数、首选对象和待补充信息。",
        doneAt: 3,
      },
      {
        id: "assets",
        title: "确认公司与联系人结果",
        detail: "用户审核后才形成正式公司和联系人资产。",
        requirement: "联系人业务确认与对外联系授权分开。",
        doneAt: 4,
        waitAt: 3,
      },
      {
        id: "outreach",
        title: "联系并等待外部回复",
        detail: "发送前检查对象、身份、渠道和正文；等待期间不持续运行。",
        requirement: "产生外部影响前必须得到本次授权。",
        doneAt: 6,
        waitAt: 4,
        externalAt: 5,
      },
      {
        id: "opportunity",
        title: "形成招聘机会与后续工作",
        detail: "收到回复后整理需求；完整 JD 先形成岗位草稿。",
        requirement: "信息不完整时不能伪造正式岗位。",
        doneAt: 7,
      },
    ],
    tasks: [
      {
        id: "client-company",
        title: "公司与融资信号核验",
        status: "完成",
        tone: "success",
        action: "3 类来源相互印证，仍有猎头预算待确认",
        duration: "1 分 18 秒",
      },
      {
        id: "client-contacts",
        title: "联系人与联系方式核验",
        status: "等待用户",
        tone: "warning",
        action: "2 位正式联系人、1 条身份线索和 1 条引荐路径待审核",
        duration: "3 分 42 秒",
      },
      {
        id: "client-outreach",
        title: "客户联系与回复跟进",
        status: "未开始",
        tone: "neutral",
        action: "等待联系人审核和对外联系授权",
        duration: "—",
      },
    ],
  },
  "mapping-embodied": {
    id: "mapping-embodied",
    type: "人才摸排",
    title: "具身智能核心人才版图",
    object: "VLA、机器人学习与灵巧操作",
    prompt:
      "把国内具身智能方向做一次人才摸排，先覆盖 VLA、机器人学习和灵巧操作。重点看星澜、拓界、穹顶和灵跃四家公司，整理组织方向、关键角色、人物关系和能够联系到人的路径。",
    autoStopPhase: 4,
    maxPhase: 5,
    defaultAuth: "confirm",
    plan: [
      {
        id: "scope",
        title: "确认摸排目标与范围清单",
        detail: "拆分公司、方向、角色和关系目标，保留未知项。",
        requirement: "围绕四家公司和三个方向，不计算未知市场覆盖率。",
        doneAt: 2,
      },
      {
        id: "ecosystem",
        title: "梳理公司、组织与方向",
        detail: "形成公司生态、组织结构和关键方向的第一批结果。",
        requirement: "组织关系必须有来源和观察时间。",
        doneAt: 3,
      },
      {
        id: "people",
        title: "定位人物、角色与联系路径",
        detail: "结合候选人、论文、专利和公开资料识别人和关系。",
        requirement: "身份与关系不确定时进入待确认，不允许猜测。",
        doneAt: 4,
      },
      {
        id: "update",
        title: "审核并增量更新人才版图",
        detail: "按批次写入通过门禁的结果，冲突内容等待用户判断。",
        requirement: "每批更新说明新增、冲突、缺口和下一步动作。",
        doneAt: 5,
        waitAt: 4,
      },
      {
        id: "gaps",
        title: "确认待补充信息与下一步",
        detail: "明确还缺什么、能做什么和执行后的预期结果。",
        requirement: "不使用无法指导行动的抽象完成百分比。",
        doneAt: 6,
      },
    ],
    tasks: [
      {
        id: "mapping-org",
        title: "公司与组织方向研究",
        status: "完成",
        tone: "success",
        action: "4 家公司、7 个团队方向已形成可核验结构",
        duration: "4 分 26 秒",
      },
      {
        id: "mapping-people",
        title: "关键人物与身份检查",
        status: "完成",
        tone: "success",
        action: "30 位人物中 18 位已确认，11 位为线索，1 位身份冲突",
        duration: "6 分 11 秒",
      },
      {
        id: "mapping-relations",
        title: "人物关系与联系路径",
        status: "等待用户",
        tone: "warning",
        action: "9 条关系可写入，1 条冲突需要审核",
        duration: "2 分 48 秒",
      },
    ],
  },
  "career-linhao": {
    id: "career-linhao",
    type: "候选人求职",
    title: "林昊职业机会",
    object: "林昊 · 机器人学习负责人",
    prompt:
      "我确认要跟进林昊最近可能看机会这条信号。先看看他和系统里哪些岗位匹配，告诉我联系时应该重点确认什么；不要替我发消息，我会自己通过微信联系。",
    autoStopPhase: 3,
    maxPhase: 6,
    defaultAuth: "analysis",
    plan: [
      {
        id: "signal",
        title: "核验动向信号与资料新鲜度",
        detail: "说明触发依据、证据强弱、联系方式和待核实信息。",
        requirement: "信号只说明可能性，不把公开动态当成求职事实。",
        doneAt: 2,
      },
      {
        id: "match",
        title: "匹配系统内有效岗位",
        detail: "使用候选人和岗位最新版本执行角色门禁与匹配。",
        requirement: "不搜索公开市场职位，只判断 Hunter 中的有效岗位。",
        doneAt: 3,
      },
      {
        id: "review",
        title: "查看岗位建议与联系要点",
        detail: "比较分数、理由、风险、缺口和建议沟通重点。",
        requirement: "Hunter 不自动联系候选人。",
        doneAt: 4,
        waitAt: 3,
      },
      {
        id: "contact",
        title: "记录猎头联系结果",
        detail: "用户通过微信、电话或已有关系联系后补充结果。",
        requirement: "文字、文件和新简历均可作为补充信息。",
        doneAt: 6,
        waitAt: 4,
        externalAt: 5,
      },
      {
        id: "rematch",
        title: "更新档案并局部重新匹配",
        detail: "先显示档案变化与合并摘要，再重做受影响岗位。",
        requirement: "有合适岗位时由用户确认交给岗位招聘主线。",
        doneAt: 7,
      },
    ],
    tasks: [
      {
        id: "career-signal",
        title: "候选人动向信号核验",
        status: "完成",
        tone: "success",
        action: "2 条中等证据，求职意愿仍需猎头本人核实",
        duration: "36 秒",
      },
      {
        id: "career-match",
        title: "系统内岗位增量匹配",
        status: "完成",
        tone: "success",
        action: "7 个有效岗位中 3 个值得查看",
        duration: "1 分 22 秒",
      },
      {
        id: "career-contact",
        title: "等待猎头补充联系结果",
        status: "等待用户",
        tone: "warning",
        action: "Hunter 不自动发送消息，等待用户记录微信或电话结果",
        duration: "—",
      },
    ],
  },
};
