export const workstreamHistory = [
  {
    id: "position-vla",
    type: "岗位招聘",
    title: "具身智能 VLA 算法负责人",
    object: "星澜机器人",
    status: "等待用户",
    tone: "warning",
    time: "刚刚",
    pinned: true,
  },
  {
    id: "client-xinglan",
    type: "客户开发",
    title: "星澜机器人招聘合作",
    object: "星澜机器人",
    status: "等待外部",
    tone: "neutral",
    time: "12 分钟前",
    pinned: true,
  },
  {
    id: "mapping-embodied",
    type: "人才摸排",
    title: "具身智能核心人才版图",
    object: "VLA、机器人学习与灵巧操作",
    status: "推进中",
    tone: "info",
    time: "今天 08:40",
  },
  {
    id: "career-linhao",
    type: "候选人求职",
    title: "林昊职业机会",
    object: "林昊 · 机器人算法负责人",
    status: "等待外部",
    tone: "neutral",
    time: "昨天 18:26",
  },
];

export const planSteps = [
  {
    id: "scope",
    title: "确认岗位边界与找人范围",
    detail: "复用已解析岗位，校验硬要求、可放宽条件和本轮数量上限。",
    requirement:
      "VLA 算法负责人；机器人学习或多模态策略；产品落地与团队管理需要单独检查。",
  },
  {
    id: "recall",
    title: "并行召回候选人与人物线索",
    detail: "系统候选人、人才平台、论文与专利来源并行处理。",
    requirement: "多渠道找人；北京优先，异地人选保留地点意愿风险。",
  },
  {
    id: "enrich",
    title: "补全、查重并执行匹配门禁",
    detail: "保留来源证据，跳过明确不满足硬门槛的人选。",
    requirement: "只保留角色、能力和经历满足岗位边界的人选。",
  },
  {
    id: "review",
    title: "交付候选人审核结果",
    detail: "等待用户决定联系、储备、观察或排除范围。",
    requirement: "本轮交付不超过 20 位值得判断的人选。",
  },
  {
    id: "followup",
    title: "按决定继续后续动作",
    detail: "外部联系前再次检查授权、对象和渠道范围。",
    requirement: "先交付审核结果，不直接联系候选人。",
  },
];

export const internalTasks = [
  {
    id: "internal-system",
    title: "检索系统候选人",
    status: "完成",
    tone: "success",
    action: "找到 6 位已有候选人，其中 3 位进入本轮审核",
    duration: "18 秒",
  },
  {
    id: "internal-platforms",
    title: "人才平台并行寻访",
    status: "完成",
    tone: "success",
    action: "猎聘与脉脉共形成 12 位不重复候选人",
    duration: "8 分 42 秒",
  },
  {
    id: "internal-research",
    title: "研究来源补充人物线索",
    status: "完成",
    tone: "success",
    action: "从论文与专利补充 3 位候选人",
    duration: "2 分 16 秒",
  },
  {
    id: "internal-enrichment",
    title: "补全、查重与匹配",
    status: "等待用户",
    tone: "warning",
    action: "18 位候选人已通过门禁，等待审核",
    duration: "4 分 09 秒",
  },
];

export const evidenceRows = [
  {
    source: "岗位资料",
    finding: "要求 8 年以上机器人学习或多模态算法经验，并具备团队管理经历",
    freshness: "今天核验",
    confidence: "已确认",
  },
  {
    source: "星澜机器人官网",
    finding: "北京团队近期新增 VLA、具身智能和机器人学习相关岗位",
    freshness: "2 天前",
    confidence: "高可信",
  },
  {
    source: "猎头补充",
    finding: "可接受高级 IC 转管理，但不考虑纯学术且无产品落地经历的人选",
    freshness: "今天补充",
    confidence: "已确认",
  },
];

const candidateBase = [
  [
    "林昊",
    "拓界机器人",
    "机器人学习负责人",
    "北京",
    92,
    "强烈建议",
    "VLA 产品落地与团队管理经历完整",
    "薪资可能高于当前区间",
  ],
  [
    "周明远",
    "穹顶智能",
    "具身智能算法总监",
    "上海",
    89,
    "建议联系",
    "多模态策略学习与量产机器人经验匹配",
    "到岗时间尚未核实",
  ],
  [
    "赵星羽",
    "高校联合实验室",
    "副研究员",
    "北京",
    88,
    "谨慎评估",
    "论文与技术方向高度匹配",
    "缺少明确商业产品和团队管理证据",
  ],
  [
    "陈楚宁",
    "灵跃科技",
    "VLA 算法负责人",
    "深圳",
    87,
    "建议联系",
    "从 0 到 1 搭建 VLA 团队并完成真机部署",
    "异地意愿未知",
  ],
  [
    "顾言川",
    "智行未来",
    "机器人基础模型专家",
    "北京",
    86,
    "建议联系",
    "基础模型、视觉语言与控制策略经验均衡",
    "管理规模偏小",
  ],
  [
    "许若航",
    "星河自动化",
    "机器人算法经理",
    "杭州",
    84,
    "加入储备",
    "工程化能力强，带领 8 人算法团队",
    "VLA 经验只有一年",
  ],
  [
    "沈亦辰",
    "启元动力",
    "强化学习负责人",
    "上海",
    83,
    "加入储备",
    "强化学习与 sim-to-real 经验突出",
    "多模态模型经验不足",
  ],
  [
    "唐可欣",
    "深境智能",
    "多模态算法 Lead",
    "北京",
    82,
    "加入储备",
    "多模态理解与端侧部署经验完整",
    "机器人控制经验需核实",
  ],
  [
    "陆知行",
    "矩阵机器人",
    "具身智能高级工程师",
    "苏州",
    80,
    "保留观察",
    "技术深度符合，近期负责操作策略",
    "缺少正式管理经验",
  ],
  [
    "叶晨风",
    "开源机器人社区",
    "核心维护者",
    "上海",
    79,
    "保留观察",
    "开源影响力和系统能力突出",
    "当前任职与求职状态不完整",
  ],
  [
    "韩思源",
    "澜舟具身",
    "机器人感知负责人",
    "北京",
    78,
    "保留观察",
    "感知和三维场景理解能力强",
    "策略学习不是主要方向",
  ],
  [
    "方知远",
    "云端智造",
    "算法平台主管",
    "杭州",
    77,
    "保留观察",
    "团队管理经验充分",
    "具身智能项目证据较少",
  ],
  [
    "罗一川",
    "灵工科技",
    "机器人学习专家",
    "深圳",
    76,
    "加入储备",
    "模仿学习和数据闭环经验清晰",
    "工作年限略低于要求",
  ],
  [
    "蒋舒扬",
    "联合创新中心",
    "研究科学家",
    "北京",
    74,
    "谨慎评估",
    "研究方向匹配且有真机实验",
    "身份和商业经历需要消歧",
  ],
  [
    "伍清禾",
    "未来工场",
    "控制算法负责人",
    "广州",
    72,
    "保留观察",
    "控制系统工程经验扎实",
    "多模态方向匹配有限",
  ],
  [
    "宋怀瑾",
    "云枢机器人",
    "高级算法工程师",
    "南京",
    69,
    "不建议",
    "有移动机器人量产经验",
    "角色层级和 VLA 方向均不足",
  ],
  [
    "贺嘉言",
    "知行实验室",
    "博士后",
    "上海",
    66,
    "不建议",
    "论文质量高且方向接近",
    "缺少企业经历和团队管理",
  ],
  [
    "孟予安",
    "前沿智能研究院",
    "研究员",
    "北京",
    62,
    "不建议",
    "具身智能研究经历明确",
    "岗位角色与落地要求差距明显",
  ],
];

export const candidates = candidateBase.map(
  (
    [name, company, role, city, score, recommendation, strength, risk],
    index,
  ) => ({
    id: `candidate-${index + 1}`,
    name,
    company,
    role,
    city,
    score,
    recommendation,
    strength,
    risk,
    years: 8 + (index % 6),
    education: index % 4 === 0 ? "博士" : "硕士",
    source: ["系统候选人", "猎聘", "脉脉", "论文线索"][index % 4],
    skills: ["VLA", "机器人学习", "多模态模型"].slice(0, 2 + (index % 2)),
  }),
);

export const sideTaskRows = [
  [
    "task-hand-team",
    "核验灵巧手团队负责人",
    "人物身份核验",
    "星澜机器人人才版图",
    "等待用户",
    "warning",
    "16 分钟前",
  ],
  [
    "task-shlab",
    "补充上海人工智能实验室具身智能团队",
    "公开资料调研",
    "具身智能核心人才版图",
    "运行中",
    "info",
    "已运行 24 分钟",
  ],
  [
    "task-zhaoxingyu",
    "消歧赵星羽的论文与任职身份",
    "人物消歧",
    "VLA 候选人审核",
    "失败",
    "danger",
    "7 分钟前",
  ],
  [
    "task-li-auto",
    "核验理想汽车机器人团队招聘信号",
    "公司信号核验",
    "客户开发",
    "完成",
    "success",
    "今天 08:12",
  ],
  [
    "task-patent",
    "整理灵巧手结构专利共同发明人",
    "专利关系探索",
    "灵巧手人才版图",
    "完成",
    "success",
    "昨天 19:40",
  ],
  [
    "task-cloudchip",
    "查找云脉芯能团队联系人",
    "联系人探索",
    "云脉芯能公司资料",
    "已暂停",
    "neutral",
    "昨天 17:22",
  ],
  [
    "task-role",
    "确认启元动力算法负责人任职变化",
    "任职核验",
    "候选人沈亦辰",
    "等待外部",
    "neutral",
    "昨天 14:09",
  ],
];

export const sideTasks = sideTaskRows.map(
  ([id, title, type, object, status, tone, time], index) => ({
    id,
    title,
    type,
    object,
    status,
    tone,
    time,
    owner: "沈岚",
    summary:
      index === 0
        ? "公开来源中出现两位同名负责人，需要核验身份、任职和团队关系。"
        : "该任务具有独立目标和明确交付，结果将回流关联业务对象。",
  }),
);

export const signals = [
  {
    id: "signal-cloudchip",
    type: "公司变化",
    title: "云脉芯能正在组建机器人芯片团队",
    object: "云脉芯能",
    priority: "高优先级",
    status: "待处理",
    tone: "warning",
    time: "今天 09:12",
    evidence: 4,
    summary: "招聘页面、公众号和两位团队成员公开资料均出现机器人芯片方向变化。",
    sources: ["公司招聘页面", "公司公众号", "团队成员公开资料", "行业活动议程"],
    changes: [
      "新增机器人芯片算法岗位",
      "一位芯片架构负责人公开加入",
      "上海办公室开始招聘",
    ],
  },
  {
    id: "signal-tuoji",
    type: "招聘动态",
    title: "拓界智驾新增感知与规划团队招聘页面",
    object: "拓界智驾",
    priority: "建议关注",
    status: "观察中",
    tone: "info",
    time: "今天 08:36",
    evidence: 3,
    summary: "新增岗位与近期融资消息相互印证，但尚未确认是否开放猎头合作。",
    sources: ["公司招聘页面", "融资新闻", "员工公开动态"],
    changes: ["新增感知算法负责人", "北京与上海同时扩招"],
  },
  {
    id: "signal-chensong",
    type: "候选人动向",
    title: "陈松的公开任职信息发生变化",
    object: "陈松 · 自动驾驶技术经理",
    priority: "建议关注",
    status: "待处理",
    tone: "info",
    time: "昨天 17:20",
    evidence: 2,
    summary: "公开主页移除了原公司职位，最近一周出现多次求职相关活动。",
    sources: ["个人公开主页", "行业活动报名信息"],
    changes: ["移除原公司职位", "更新技术方向说明"],
  },
  {
    id: "signal-xinglan",
    type: "招聘动态",
    title: "星澜机器人 VLA 团队扩招信息已转化",
    object: "星澜机器人",
    priority: "已处理",
    status: "已转化",
    tone: "success",
    time: "8 月 18 日",
    evidence: 5,
    summary: "已转化为岗位招聘主线“具身智能 VLA 算法负责人”。",
    sources: ["客户沟通", "岗位 JD", "公司招聘页", "团队成员动态", "猎头补充"],
    changes: ["已创建正式岗位", "已启动岗位招聘主线"],
  },
  {
    id: "signal-expired",
    type: "公司变化",
    title: "旧招聘页面中的机器人岗位已下线",
    object: "远航智能",
    priority: "已失效",
    status: "已失效",
    tone: "neutral",
    time: "8 月 15 日",
    evidence: 2,
    summary: "连续三次检查未发现招聘页面，原信号不再具有行动价值。",
    sources: ["历史招聘页", "官网复查"],
    changes: ["招聘页面下线"],
  },
];
