export const workstreamHistory = [
  {
    id: "position-vla",
    type: "岗位招聘",
    title: "具身智能 VLA 算法负责人",
    object: "星澜机器人",
    status: "推进中",
    tone: "info",
    time: "刚刚",
    pinned: true,
    summary:
      "系统候选人、知识图谱、公开资料和用户上传简历正在持续合并，18 位候选人等待审核。",
  },
  {
    id: "client-xinglan",
    type: "客户开发",
    title: "星澜机器人招聘合作",
    object: "星澜机器人",
    status: "等待用户",
    tone: "warning",
    time: "12 分钟前",
    pinned: true,
    summary: "两条招聘信号已经核验，等待确认优先联系人和后续联系内容。",
  },
  {
    id: "mapping-embodied",
    type: "人才摸排",
    title: "具身智能 VLA 人才摸排",
    object: "VLA、机器人学习与灵巧操作",
    status: "进行中",
    tone: "success",
    time: "今天 08:40",
    summary: "已覆盖八家公司和三十七位确认人物，正在补充五个关键角色。",
  },
  {
    id: "career-linhao",
    type: "候选人求职",
    title: "林昊职业机会",
    object: "林昊 · 机器人算法负责人",
    status: "等待外部",
    tone: "neutral",
    time: "昨天 18:26",
    summary: "已完成系统岗位匹配，等待猎头回填候选人的联系结果。",
  },
];

export const periodicSignalScans = [
  {
    id: "scan-embodied-startups",
    title: "具身智能新公司与融资动态",
    description:
      "持续发现中国大陆新成立、获得早期融资或开始建设核心团队的具身智能公司。",
    status: "运行中",
    tone: "success",
    frequency: "每周一 09:00",
    nextRun: "9 月 1 日 09:00",
    lastRun: "8 月 25 日 09:00",
    lastDuration: "12 分 36 秒",
    newSignals: 7,
    pendingSignals: 3,
    scope: "中国大陆 · 具身智能 · 新成立至 B 轮",
    industries: ["具身智能", "机器人"],
    regions: ["中国大陆"],
    stages: ["新成立", "天使轮", "A 轮", "B 轮"],
    keywords: ["具身智能", "VLA", "灵巧手", "机器人学习"],
    exclusions: ["工业设备经销", "教育机器人代理"],
    limit: "每轮最多核验 80 家公司",
    runs: [
      {
        id: "run-0825",
        startedAt: "8 月 25 日 09:00",
        duration: "12 分 36 秒",
        status: "完成",
        scope: "核验 73 家公司，合并 19 条重复线索",
        result: "产生 7 条新信号，其中 3 条待你决定",
      },
      {
        id: "run-0818",
        startedAt: "8 月 18 日 09:00",
        duration: "10 分 48 秒",
        status: "完成",
        scope: "核验 65 家公司，合并 14 条重复线索",
        result: "产生 5 条新信号，其中 2 条已处理",
      },
      {
        id: "run-0811",
        startedAt: "8 月 11 日 09:00",
        duration: "8 分 21 秒",
        status: "完成",
        scope: "核验 48 家公司，合并 9 条重复线索",
        result: "产生 4 条新信号，其中 1 条已处理",
      },
    ],
    generatedSignals: [
      {
        title: "维拓智能完成数千万元天使轮融资",
        object: "维拓智能",
        status: "待你决定",
        tone: "warning",
        time: "8 月 25 日 09:08",
      },
      {
        title: "原力灵巧手新增算法负责人岗位",
        object: "原力机器人",
        status: "观察中",
        tone: "info",
        time: "8 月 25 日 09:06",
      },
      {
        title: "星澜机器人北京团队扩充 VLA 方向",
        object: "星澜机器人",
        status: "已处理",
        tone: "success",
        time: "8 月 25 日 09:04",
      },
    ],
  },
  {
    id: "scan-ai-hiring",
    title: "AI 创业公司核心岗位招聘",
    description: "跟踪已确认的 AI 创业公司是否新增算法、产品与商业化核心岗位。",
    status: "运行中",
    tone: "success",
    frequency: "每 3 天 10:00",
    nextRun: "8 月 31 日 10:00",
    lastRun: "8 月 28 日 10:00",
    lastDuration: "9 分 14 秒",
    newSignals: 11,
    pendingSignals: 5,
    scope: "已关注的 46 家 AI 创业公司 · 核心岗位",
    industries: ["人工智能", "企业服务"],
    regions: ["北京", "上海", "深圳", "杭州"],
    stages: ["招聘中"],
    keywords: ["算法负责人", "首席科学家", "产品负责人", "商业化负责人"],
    exclusions: ["实习岗位", "外包岗位"],
    limit: "每轮最多核验 120 个岗位",
    runs: [
      {
        id: "run-0828",
        startedAt: "8 月 28 日 10:00",
        duration: "9 分 14 秒",
        status: "完成",
        scope: "核验 46 家公司和 108 个公开岗位",
        result: "产生 11 条新信号，其中 5 条待你决定",
      },
      {
        id: "run-0825-ai",
        startedAt: "8 月 25 日 10:00",
        duration: "8 分 52 秒",
        status: "完成",
        scope: "核验 46 家公司和 101 个公开岗位",
        result: "产生 8 条新信号，其中 3 条已处理",
      },
    ],
    generatedSignals: [
      {
        title: "矩阵智算新增大模型平台负责人岗位",
        object: "矩阵智算",
        status: "待你决定",
        tone: "warning",
        time: "昨天 10:09",
      },
      {
        title: "澄心科技开始招聘商业化负责人",
        object: "澄心科技",
        status: "观察中",
        tone: "info",
        time: "昨天 10:05",
      },
    ],
  },
  {
    id: "scan-career-signals",
    title: "重点候选人职业变化",
    description:
      "观察收藏夹内重点候选人的公开履历、成果和任职变化，只提示值得人工核实的变化。",
    status: "已暂停",
    tone: "neutral",
    frequency: "每两周周五 17:00",
    nextRun: "已暂停",
    lastRun: "8 月 15 日 17:00",
    lastDuration: "18 分 03 秒",
    newSignals: 2,
    pendingSignals: 0,
    scope: "重点候选人收藏夹 · 128 人",
    industries: ["人工智能", "机器人", "自动驾驶"],
    regions: ["不限"],
    stages: ["重点关注"],
    keywords: ["任职变化", "公开成果", "团队变化", "求职信号"],
    exclusions: ["未经交叉核验的社交媒体传言"],
    limit: "每轮最多核验 128 位候选人",
    runs: [
      {
        id: "run-0815-career",
        startedAt: "8 月 15 日 17:00",
        duration: "18 分 03 秒",
        status: "完成",
        scope: "核验 128 位候选人，发现 9 条可能变化",
        result: "产生 2 条新信号，均已处理",
      },
      {
        id: "run-0801-career",
        startedAt: "8 月 1 日 17:00",
        duration: "17 分 26 秒",
        status: "部分完成",
        scope: "核验 128 位候选人，17 个来源暂不可用",
        result: "产生 1 条新信号，已加入观察",
      },
    ],
    generatedSignals: [
      {
        title: "林昊公开资料显示职责范围扩大",
        object: "林昊",
        status: "已处理",
        tone: "success",
        time: "8 月 15 日 17:12",
      },
      {
        title: "周明远近期连续发布具身智能招聘信息",
        object: "周明远",
        status: "已忽略",
        tone: "neutral",
        time: "8 月 15 日 17:09",
      },
    ],
  },
  {
    id: "scan-autonomous-hiring",
    title: "自动驾驶核心团队变化",
    description:
      "跟踪自动驾驶公司核心团队、业务方向和公开招聘变化，出现可核验变化时生成信号。",
    status: "异常",
    tone: "warning",
    frequency: "每周一 09:00",
    nextRun: "等待问题处理",
    lastRun: "8 月 25 日 09:00",
    lastDuration: "3 分 42 秒",
    newSignals: 0,
    pendingSignals: 0,
    scope: "自动驾驶 · 北京、上海、深圳 · 核心团队",
    industries: ["自动驾驶"],
    regions: ["北京", "上海", "深圳"],
    stages: ["团队变化", "业务调整", "招聘变化"],
    keywords: ["自动驾驶", "感知", "规划控制", "端到端"],
    exclusions: ["普通销售岗位", "未经核验的传言"],
    limit: "每轮最多核验 60 家公司",
    runs: [
      {
        id: "run-0825-auto",
        startedAt: "8 月 25 日 09:00",
        duration: "3 分 42 秒",
        status: "部分完成",
        scope: "完成 18 家公司核验，公开搜索服务暂时不可用",
        result: "本轮没有产生可确认的新信号",
      },
      {
        id: "run-0818-auto",
        startedAt: "8 月 18 日 09:00",
        duration: "11 分 17 秒",
        status: "完成",
        scope: "核验 54 家公司，合并 12 条重复线索",
        result: "产生 3 条新信号，均已处理",
      },
    ],
    generatedSignals: [],
  },
];

export const planSteps = [
  {
    id: "scope",
    title: "确认岗位边界与找人范围",
    detail: "复用已解析岗位，校验硬要求、可放宽条件和本轮数量上限。",
    requirement:
      "VLA 算法负责人；机器人学习或多模态策略；产品落地与团队管理需要单独检查。",
  },
  {
    id: "recall",
    title: "并行检索并接收补充资料",
    detail:
      "检索系统候选人、知识图谱、公开网络和论文专利，并接收用户上传的简历。",
    requirement: "多渠道找人；北京优先，异地人选保留地点意愿风险。",
  },
  {
    id: "enrich",
    title: "持续合并并执行匹配门禁",
    detail: "每批结果到达后立即补全、查重、合并和匹配。",
    requirement: "只保留角色、能力和经历满足岗位边界的人选。",
  },
  {
    id: "review",
    title: "交付候选人审核结果",
    detail: "等待用户决定联系、储备、观察或排除范围。",
    requirement: "本轮交付不超过 20 位值得判断的人选。",
  },
  {
    id: "followup",
    title: "按决定继续后续动作",
    detail: "邮件发送前逐次确认收件人、主题、正文和附件。",
    requirement: "先交付审核结果；没有用户确认时不发送邮件。",
  },
];

export const internalTasks = [
  {
    id: "internal-system",
    title: "检索系统候选人",
    status: "完成",
    tone: "success",
    action: "找到 6 位已有候选人，其中 3 位进入本轮审核",
    duration: "18 秒",
  },
  {
    id: "internal-resume-import",
    title: "读取用户上传的候选人资料",
    status: "完成",
    tone: "success",
    action: "12 份简历已解析并进入身份判断、查重与匹配门禁",
    duration: "2 分 18 秒",
  },
  {
    id: "internal-research",
    title: "研究来源补充人物线索",
    status: "完成",
    tone: "success",
    action: "从论文与专利补充 3 位候选人",
    duration: "2 分 16 秒",
  },
  {
    id: "internal-enrichment",
    title: "补全、查重与匹配",
    status: "等待用户",
    tone: "warning",
    action: "18 位候选人已通过门禁，等待审核",
    duration: "4 分 09 秒",
  },
];

export const evidenceRows = [
  {
    source: "岗位资料",
    finding: "要求 8 年以上机器人学习或多模态算法经验，并具备团队管理经历",
    freshness: "今天核验",
    confidence: "已确认",
  },
  {
    source: "星澜机器人官网",
    finding: "北京团队近期新增 VLA、具身智能和机器人学习相关岗位",
    freshness: "2 天前",
    confidence: "高可信",
  },
  {
    source: "猎头补充",
    finding: "可接受高级 IC 转管理，但不考虑纯学术且无产品落地经历的人选",
    freshness: "今天补充",
    confidence: "已确认",
  },
];

const candidateBase = [
  [
    "林昊",
    "拓界机器人",
    "机器人学习负责人",
    "上海",
    94,
    "强烈建议",
    "VLA 产品落地与团队管理经历完整",
    "薪资可能高于当前区间",
  ],
  [
    "周明远",
    "穹顶智能",
    "具身智能算法总监",
    "上海",
    86,
    "建议联系",
    "多模态策略学习与量产机器人经验匹配",
    "到岗时间尚未核实",
  ],
  [
    "赵星羽",
    "星澜机器人",
    "VLA 算法负责人",
    "北京",
    91,
    "强烈建议",
    "VLA 技术方向高度匹配，已承担算法负责人职责",
    "需要核实最近两年真机部署的个人贡献",
  ],
  [
    "陈楚宁",
    "灵跃科技",
    "灵巧操作算法负责人",
    "深圳",
    89,
    "建议联系",
    "从 0 到 1 搭建 VLA 团队并完成真机部署",
    "异地意愿未知",
  ],
  [
    "顾言川",
    "智行未来",
    "机器人基础模型专家",
    "北京",
    86,
    "建议联系",
    "基础模型、视觉语言与控制策略经验均衡",
    "管理规模偏小",
  ],
  [
    "许若航",
    "星河自动化",
    "机器人算法经理",
    "杭州",
    84,
    "加入储备",
    "工程化能力强，带领 8 人算法团队",
    "VLA 经验只有一年",
  ],
  [
    "沈亦辰",
    "启元动力",
    "强化学习负责人",
    "上海",
    83,
    "加入储备",
    "强化学习与 sim-to-real 经验突出",
    "多模态模型经验不足",
  ],
  [
    "唐可欣",
    "深境智能",
    "多模态算法 Lead",
    "北京",
    82,
    "加入储备",
    "多模态理解与端侧部署经验完整",
    "机器人控制经验需核实",
  ],
  [
    "陆知行",
    "矩阵机器人",
    "具身智能高级工程师",
    "苏州",
    80,
    "保留观察",
    "技术深度符合，近期负责操作策略",
    "缺少正式管理经验",
  ],
  [
    "叶晨风",
    "开源机器人社区",
    "核心维护者",
    "上海",
    79,
    "保留观察",
    "开源影响力和系统能力突出",
    "当前任职与求职状态不完整",
  ],
  [
    "韩思源",
    "澜舟具身",
    "机器人感知负责人",
    "北京",
    78,
    "保留观察",
    "感知和三维场景理解能力强",
    "策略学习不是主要方向",
  ],
  [
    "方知远",
    "云端智造",
    "算法平台主管",
    "杭州",
    77,
    "保留观察",
    "团队管理经验充分",
    "具身智能项目证据较少",
  ],
  [
    "罗一川",
    "灵工科技",
    "机器人学习专家",
    "深圳",
    76,
    "加入储备",
    "模仿学习和数据闭环经验清晰",
    "工作年限略低于要求",
  ],
  [
    "蒋舒扬",
    "联合创新中心",
    "研究科学家",
    "北京",
    74,
    "谨慎评估",
    "研究方向匹配且有真机实验",
    "身份和商业经历需要消歧",
  ],
  [
    "伍清禾",
    "未来工场",
    "控制算法负责人",
    "广州",
    72,
    "保留观察",
    "控制系统工程经验扎实",
    "多模态方向匹配有限",
  ],
  [
    "宋怀瑾",
    "云枢机器人",
    "高级算法工程师",
    "南京",
    69,
    "不建议",
    "有移动机器人量产经验",
    "角色层级和 VLA 方向均不足",
  ],
  [
    "贺嘉言",
    "知行实验室",
    "博士后",
    "上海",
    66,
    "不建议",
    "论文质量高且方向接近",
    "缺少企业经历和团队管理",
  ],
  [
    "孟予安",
    "前沿智能研究院",
    "研究员",
    "北京",
    62,
    "不建议",
    "具身智能研究经历明确",
    "岗位角色与落地要求差距明显",
  ],
];

export const candidates = candidateBase.map(
  (
    [name, company, role, city, score, recommendation, strength, risk],
    index,
  ) => ({
    id: `candidate-${index + 1}`,
    name,
    company,
    role,
    city,
    score,
    recommendation,
    strength,
    risk,
    years: 8 + (index % 6),
    education: index % 4 === 0 ? "博士" : "硕士",
    source: ["系统候选人", "用户上传简历", "公开职业资料", "论文线索"][
      index % 4
    ],
    skills: ["VLA", "机器人学习", "多模态模型"].slice(0, 2 + (index % 2)),
  }),
);

export const sideTaskRows = [
  [
    "task-recommend-linhao",
    "为林昊生成客户推荐报告",
    "候选人推荐报告",
    "具身智能 VLA 算法负责人",
    "等待用户",
    "warning",
    "刚刚",
  ],
  [
    "task-hand-team",
    "核验灵巧手团队负责人",
    "人物身份核验",
    "星澜机器人知识图谱",
    "等待用户",
    "warning",
    "16 分钟前",
  ],
  [
    "task-shlab",
    "补充上海人工智能实验室具身智能团队",
    "公开资料调研",
    "VLA 核心候选人关系知识图谱",
    "运行中",
    "info",
    "已运行 24 分钟",
  ],
  [
    "task-zhaoxingyu",
    "消歧赵星羽的论文与任职身份",
    "人物消歧",
    "VLA 候选人审核",
    "失败",
    "danger",
    "7 分钟前",
  ],
  [
    "task-li-auto",
    "核验理想汽车机器人团队招聘信号",
    "公司信号核验",
    "客户开发",
    "完成",
    "success",
    "今天 08:12",
  ],
  [
    "task-patent",
    "整理灵巧手结构专利共同发明人",
    "专利关系探索",
    "灵巧手知识图谱",
    "完成",
    "success",
    "昨天 19:40",
  ],
  [
    "task-cloudchip",
    "查找云脉芯能团队联系人",
    "联系人探索",
    "云脉芯能公司资料",
    "已暂停",
    "neutral",
    "昨天 17:22",
  ],
  [
    "task-role",
    "确认启元动力算法负责人任职变化",
    "任职核验",
    "候选人沈亦辰",
    "等待外部",
    "neutral",
    "昨天 14:09",
  ],
];

export const sideTasks = sideTaskRows.map(
  ([id, title, type, object, status, tone, time]) => ({
    id,
    title,
    type,
    object,
    status,
    tone,
    time,
    owner: "沈岚",
    summary:
      id === "task-recommend-linhao"
        ? "基于岗位、候选人和匹配证据生成客户推荐报告，并等待用户提出修改要求。"
        : id === "task-hand-team"
          ? "公开来源中出现两位同名负责人，需要核验身份、任职和团队关系。"
          : "该任务具有独立目标和明确交付，结果将回流关联业务对象。",
  }),
);

const sideTaskBusinessScenarios = {
  "task-recommend-linhao": "岗位招聘",
  "task-hand-team": "人才摸排",
  "task-shlab": "人才摸排",
  "task-zhaoxingyu": "岗位招聘",
  "task-li-auto": "客户开发",
  "task-patent": "人才摸排",
  "task-cloudchip": "客户开发",
  "task-role": "候选人求职",
};

export const workItems = [
  ...workstreamHistory.map((item) => ({
    ...item,
    category: item.type,
    scenario: item.type,
    scenarios:
      item.id === "position-vla"
        ? ["岗位招聘", "人才摸排"]
        : item.id === "client-xinglan"
          ? ["客户开发", "招聘机会"]
          : item.id === "mapping-embodied"
            ? ["人才摸排", "知识图谱"]
            : ["候选人求职", "人岗匹配"],
  })),
  {
    ...sideTasks.find((item) => item.id === "task-hand-team"),
    category: "身份核验",
    scenario: sideTaskBusinessScenarios["task-hand-team"],
    scenarios: ["候选人", "身份核验"],
  },
  {
    id: "task-interview-summary",
    title: "整理林昊的面试反馈",
    type: "信息整理",
    object: "候选人林昊",
    status: "可继续",
    tone: "info",
    time: "今天 09:31",
    owner: "沈岚",
    category: "信息整理",
    scenario: "岗位招聘",
    scenarios: ["岗位招聘", "信息整理"],
    summary: "已整理三条面试反馈，可以继续补充信息或要求 Hunter 调整摘要。",
  },
];

export const signals = [
  {
    id: "signal-graph-sync",
    kind: "洞察",
    type: "关系变化",
    title: "星澜机器人组织与人才流动关系发生变化",
    object: "星澜机器人组织知识图谱",
    priority: "需要确认",
    status: "待你决定",
    tone: "warning",
    time: "今天 09:24",
    evidence: 5,
    summary:
      "2 条可靠变化已自动同步，另有 1 条人物流动关系证据不足，需要在图谱审核中判断。",
    nextLabel: "需要确认：1 条人物流动关系",
    validity: "建议在 9 月 6 日前处理",
    decision: {
      question: "是否将周明远的任职变化写入知识图谱？",
      recommendation: "先查看两份存在时间差的任职证据，再决定是否更新关系。",
      impact:
        "暂不处理不会覆盖现有图谱，但相关人才流动分析会继续使用上一份已确认关系。",
    },
    sources: [
      "候选人最新简历",
      "公司公开资料",
      "论文作者机构",
      "用户补充",
      "历史组织图",
    ],
    changes: [
      "王奕已加入 VLA 算法组",
      "林昊的学术合作关系新增 2 条",
      "周明远的任职变化仍待确认",
    ],
    graphPath: "/mappings/mapping-embodied?tab=reviews",
    taskContext: {
      title: "每月更新机器人行业知识图谱",
      route: "/tasks/mapping-embodied",
      status: "等待用户",
      tone: "warning",
    },
    history: [
      {
        time: "今天 09:24",
        title: "进入待你决定",
        detail: "两条可靠关系已同步，一条人物流动关系需要人工判断。",
        tone: "warning",
      },
      {
        time: "今天 09:21",
        title: "合并 2 个新增来源",
        detail: "候选人最新简历与公司公开资料对任职时间存在差异。",
        tone: "info",
      },
      {
        time: "今天 09:18",
        title: "发现关系变化",
        detail: "每月更新机器人行业知识图谱运行发现 3 条关系变化。",
        tone: "neutral",
      },
    ],
  },
  {
    id: "signal-cloudchip",
    kind: "信号",
    type: "公司变化",
    title: "云脉芯能正在组建机器人芯片团队",
    object: "云脉芯能",
    priority: "高优先级",
    status: "待你决定",
    tone: "warning",
    time: "今天 09:12",
    evidence: 4,
    summary: "招聘页面、公众号和两位团队成员公开资料均出现机器人芯片方向变化。",
    nextLabel: "需要确认：是否开展客户开发",
    validity: "建议在 9 月 5 日前处理",
    decision: {
      question: "是否围绕云脉芯能启动一次客户开发任务？",
      recommendation: "建议先核验招聘负责人和猎头合作意愿，再决定是否联系。",
      impact:
        "若暂不处理，Hunter 会在有效期结束前重新核验；公开招聘窗口可能缩短。",
    },
    sources: ["公司招聘页面", "公司公众号", "团队成员公开资料", "行业活动议程"],
    changes: [
      "新增机器人芯片算法岗位",
      "一位芯片架构负责人公开加入",
      "上海办公室开始招聘",
    ],
    sourceRun: {
      label: "每周发现具身智能创业公司与招聘机会 · 今天 09:00",
      route: "/tasks/periodic?view=runs&run=run-startups-success",
      status: "可继续",
      tone: "success",
    },
    history: [
      {
        time: "今天 09:12",
        title: "进入待你决定",
        detail: "四个来源相互印证，已经具备明确的客户开发价值。",
        tone: "warning",
      },
      {
        time: "今天 09:09",
        title: "完成交叉核验",
        detail: "招聘页面、公众号与团队成员资料指向同一业务方向。",
        tone: "success",
      },
      {
        time: "今天 09:04",
        title: "周期运行首次发现",
        detail: "新增招聘岗位与上海办公室扩张同时出现。",
        tone: "neutral",
      },
    ],
  },
  {
    id: "signal-tuoji",
    kind: "信号",
    type: "招聘动态",
    title: "拓界智驾新增感知与规划团队招聘页面",
    object: "拓界智驾",
    priority: "持续观察",
    status: "观察中",
    tone: "info",
    time: "今天 08:36",
    evidence: 3,
    summary: "新增岗位与近期融资消息相互印证，但尚未确认是否开放猎头合作。",
    nextLabel: "下次检查：9 月 7 日 09:00",
    observation: {
      objective:
        "确认新增岗位是否持续开放，以及是否出现招聘负责人或猎头合作信息。",
      nextCheck: "9 月 7 日 09:00",
      trigger: "招聘岗位连续开放、团队扩招规模增加或出现招聘负责人信息",
      expiresAt: "9 月 30 日；届时仍无实质变化则自动失效",
      lastChecked: "今天 08:36",
      lastResult: "新增岗位与融资消息相互印证，但暂不足以建议开展客户开发。",
    },
    sources: ["公司招聘页面", "融资新闻", "员工公开动态"],
    changes: ["新增感知算法负责人", "北京与上海同时扩招"],
    sourceRun: {
      label: "每周发现具身智能创业公司与招聘机会 · 今天 09:00",
      route: "/tasks/periodic?view=runs&run=run-startups-success",
      status: "可继续",
      tone: "success",
    },
    history: [
      {
        time: "今天 08:36",
        title: "进入观察中",
        detail: "已建立观察计划，下次检查为 9 月 7 日 09:00。",
        tone: "info",
      },
      {
        time: "今天 08:31",
        title: "合并融资与招聘来源",
        detail: "证据能够说明团队扩招，但无法确认猎头合作意愿。",
        tone: "neutral",
      },
    ],
  },
  {
    id: "signal-chensong",
    kind: "洞察",
    type: "候选人动向",
    title: "陈松的公开任职信息发生变化",
    object: "陈松 · 自动驾驶技术经理",
    priority: "建议关注",
    status: "待你决定",
    tone: "warning",
    time: "昨天 17:20",
    evidence: 2,
    summary: "公开主页移除了原公司职位，最近一周出现多次求职相关活动。",
    nextLabel: "需要确认：是否联系候选人核实意愿",
    validity: "建议在 3 天内处理",
    decision: {
      question: "是否联系陈松，核实其近期是否愿意了解新机会？",
      recommendation:
        "公开动态只能说明可能性，建议由猎头本人通过已有手机号核实。",
      impact:
        "不处理不会更改候选人求职状态；Hunter 会在 3 天后重新检查公开信息。",
    },
    sources: ["个人公开主页", "行业活动报名信息"],
    changes: ["移除原公司职位", "更新技术方向说明"],
    history: [
      {
        time: "昨天 17:20",
        title: "进入待你决定",
        detail: "候选人已有手机号，但求职意愿仍需猎头本人核实。",
        tone: "warning",
      },
      {
        time: "昨天 17:16",
        title: "发现公开资料变化",
        detail: "个人主页移除原公司职位，活动资料更新技术方向。",
        tone: "neutral",
      },
    ],
  },
  {
    id: "signal-verifying",
    kind: "信号",
    type: "公司变化",
    title: "沐光机器人核心算法团队负责人信息出现冲突",
    object: "沐光机器人",
    priority: "正在核验",
    status: "核验中",
    tone: "info",
    time: "6 分钟前",
    evidence: 5,
    summary:
      "公司官网与近期活动议程中的负责人姓名不一致，Hunter 正在补充时间信息。",
    nextLabel: "正在核验：3 / 5 个来源",
    taskContext: {
      title: "每周发现具身智能创业公司与招聘机会 · 本轮运行",
      route: "/tasks/periodic?view=runs&run=run-startups-active",
      status: "正在运行",
      tone: "info",
    },
    verification: {
      progress: 60,
      activity: [
        {
          state: "done",
          label: "已完成",
          text: "已读取当前洞察和历史核验记录",
        },
        {
          state: "done",
          label: "已完成",
          text: "已核对公司官网、活动议程和两条公开报道",
        },
        {
          state: "done",
          label: "已完成",
          text: "已确认不同来源中的负责人姓名确实存在冲突",
        },
        {
          state: "current",
          label: "进行中",
          text: "正在核验任职时间和近期团队公开动态",
        },
        {
          state: "queued",
          label: "待执行",
          text: "随后检查关联公司、联系人和已有任务，避免重复处理",
        },
      ],
      outcome: "核验完成后将自动进入待你决定、观察中或已失效，无需停留等待。",
    },
    sources: [
      "公司官网",
      "行业活动议程",
      "公开报道",
      "团队成员公开资料",
      "历史组织图",
    ],
    changes: ["官网负责人姓名更新", "活动议程仍显示原负责人"],
    history: [
      {
        time: "6 分钟前",
        title: "开始补充核验",
        detail: "正在区分页面更新时间差异与真实任职变化。",
        tone: "info",
      },
      {
        time: "9 分钟前",
        title: "发现来源冲突",
        detail: "公司官网与近期行业活动议程显示不同负责人。",
        tone: "warning",
      },
    ],
  },
  {
    id: "signal-xinglan",
    kind: "信号",
    type: "招聘动态",
    title: "星澜机器人 VLA 团队扩招信息已处理",
    object: "星澜机器人",
    priority: "已处理",
    status: "已处理",
    tone: "success",
    time: "8 月 18 日",
    evidence: 5,
    summary:
      "已创建岗位招聘任务“具身智能 VLA 算法负责人”，后续进展从关联任务继续查看。",
    nextLabel: "去向：具身智能 VLA 算法负责人",
    sources: ["客户沟通", "岗位 JD", "公司招聘页", "团队成员动态", "猎头补充"],
    changes: ["已创建正式岗位", "已启动岗位招聘任务"],
    outcome: {
      type: "创建任务",
      title: "具身智能 VLA 算法负责人",
      detail: "任务正在推进候选人召回、身份合并和人岗匹配。",
      route: "/tasks/position-vla",
      taskStatus: "推进中",
      taskTone: "info",
    },
    history: [
      {
        time: "8 月 18 日 10:14",
        title: "完成处理",
        detail: "用户确认创建正式岗位并启动岗位招聘任务。",
        tone: "success",
      },
      {
        time: "8 月 18 日 09:42",
        title: "完成需求核验",
        detail: "客户沟通、岗位 JD 与公开招聘信息相互印证。",
        tone: "info",
      },
    ],
  },
  {
    id: "signal-ignored",
    kind: "信号",
    type: "招聘动态",
    title: "周明远近期连续转发具身智能招聘内容",
    object: "周明远 · 星澜机器人",
    priority: "已忽略",
    status: "已忽略",
    tone: "neutral",
    time: "8 月 17 日",
    evidence: 2,
    summary: "用户确认这些内容属于常规行业分享，不作为新的招聘或求职变化处理。",
    nextLabel: "同一事件不再提醒",
    ignoredReason: "常规行业内容分享，不能说明其团队正在招聘或本人正在求职。",
    sources: ["个人公开主页", "行业社群公开内容"],
    changes: ["连续转发 4 条具身智能招聘信息"],
    history: [
      {
        time: "8 月 17 日 18:06",
        title: "用户选择忽略",
        detail: "同一事件的重复来源继续合并，但不再主动提醒。",
        tone: "neutral",
      },
      {
        time: "8 月 17 日 17:42",
        title: "发现招聘内容变化",
        detail: "公开主页连续转发多条行业招聘信息。",
        tone: "info",
      },
    ],
  },
  {
    id: "signal-expired",
    kind: "信号",
    type: "公司变化",
    title: "旧招聘页面中的机器人岗位已下线",
    object: "远航智能",
    priority: "已失效",
    status: "已失效",
    tone: "neutral",
    time: "8 月 15 日",
    evidence: 2,
    summary: "连续三次检查未发现招聘页面，原信号不再具有行动价值。",
    nextLabel: "已结束：连续三次复查无有效信息",
    invalidReason:
      "原招聘页面已下线，连续三次复查均未发现替代页面或新的招聘信息。",
    sources: ["历史招聘页", "官网复查"],
    changes: ["招聘页面下线"],
    history: [
      {
        time: "8 月 15 日 09:30",
        title: "自动判定失效",
        detail: "连续三次复查没有发现招聘页面或新的招聘证据。",
        tone: "neutral",
      },
      {
        time: "8 月 8 日 09:12",
        title: "第二次复查无变化",
        detail: "官网、招聘页面和公开岗位均未恢复。",
        tone: "neutral",
      },
      {
        time: "8 月 1 日 09:08",
        title: "招聘页面下线",
        detail: "信号由待你决定转入观察中。",
        tone: "info",
      },
    ],
  },
];
