export const workstreamHistory = [
  {
    id: "position-vla",
    type: "岗位招聘",
    title: "具身智能 VLA 算法负责人",
    object: "星澜机器人",
    status: "推进中",
    tone: "info",
    time: "刚刚",
    pinned: true,
    summary:
      "系统候选人、人才版图、公开资料和用户上传简历正在持续合并，18 位候选人等待审核。",
  },
  {
    id: "client-xinglan",
    type: "客户开发",
    title: "星澜机器人招聘合作",
    object: "星澜机器人",
    status: "等待用户",
    tone: "warning",
    time: "12 分钟前",
    pinned: true,
    summary: "两条招聘信号已经核验，等待确认优先联系人和后续联系内容。",
  },
  {
    id: "mapping-embodied",
    type: "人才摸排",
    title: "具身智能核心人才版图",
    object: "VLA、机器人学习与灵巧操作",
    status: "进行中",
    tone: "success",
    time: "今天 08:40",
    summary: "已覆盖八家公司和三十七位确认人物，正在补充五个关键角色。",
  },
  {
    id: "career-linhao",
    type: "候选人求职",
    title: "林昊职业机会",
    object: "林昊 · 机器人算法负责人",
    status: "等待外部",
    tone: "neutral",
    time: "昨天 18:26",
    summary: "已完成系统岗位匹配，等待猎头回填候选人的联系结果。",
  },
];

export const periodicSignalScans = [
  {
    id: "scan-embodied-startups",
    title: "具身智能新公司与融资动态",
    description:
      "持续发现中国大陆新成立、获得早期融资或开始建设核心团队的具身智能公司。",
    status: "运行中",
    tone: "success",
    frequency: "每周一 09:00",
    nextRun: "9 月 1 日 09:00",
    lastRun: "8 月 25 日 09:00",
    lastDuration: "12 分 36 秒",
    newSignals: 7,
    pendingSignals: 3,
    scope: "中国大陆 · 具身智能 · 新成立至 B 轮",
    industries: ["具身智能", "机器人"],
    regions: ["中国大陆"],
    stages: ["新成立", "天使轮", "A 轮", "B 轮"],
    keywords: ["具身智能", "VLA", "灵巧手", "机器人学习"],
    exclusions: ["工业设备经销", "教育机器人代理"],
    limit: "每轮最多核验 80 家公司",
    runs: [
      {
        id: "run-0825",
        startedAt: "8 月 25 日 09:00",
        duration: "12 分 36 秒",
        status: "完成",
        scope: "核验 73 家公司，合并 19 条重复线索",
        result: "产生 7 条新信号，其中 3 条待处理",
      },
      {
        id: "run-0818",
        startedAt: "8 月 18 日 09:00",
        duration: "10 分 48 秒",
        status: "完成",
        scope: "核验 65 家公司，合并 14 条重复线索",
        result: "产生 5 条新信号，其中 2 条已转化",
      },
      {
        id: "run-0811",
        startedAt: "8 月 11 日 09:00",
        duration: "8 分 21 秒",
        status: "完成",
        scope: "核验 48 家公司，合并 9 条重复线索",
        result: "产生 4 条新信号，其中 1 条已转化",
      },
    ],
    generatedSignals: [
      {
        title: "维拓智能完成数千万元天使轮融资",
        object: "维拓智能",
        status: "待处理",
        tone: "warning",
        time: "8 月 25 日 09:08",
      },
      {
        title: "原力灵巧手新增算法负责人岗位",
        object: "原力机器人",
        status: "观察中",
        tone: "info",
        time: "8 月 25 日 09:06",
      },
      {
        title: "星澜机器人北京团队扩充 VLA 方向",
        object: "星澜机器人",
        status: "已转化",
        tone: "success",
        time: "8 月 25 日 09:04",
      },
    ],
  },
  {
    id: "scan-ai-hiring",
    title: "AI 创业公司核心岗位招聘",
    description: "跟踪已确认的 AI 创业公司是否新增算法、产品与商业化核心岗位。",
    status: "运行中",
    tone: "success",
    frequency: "每 3 天 10:00",
    nextRun: "8 月 31 日 10:00",
    lastRun: "8 月 28 日 10:00",
    lastDuration: "9 分 14 秒",
    newSignals: 11,
    pendingSignals: 5,
    scope: "已关注的 46 家 AI 创业公司 · 核心岗位",
    industries: ["人工智能", "企业服务"],
    regions: ["北京", "上海", "深圳", "杭州"],
    stages: ["招聘中"],
    keywords: ["算法负责人", "首席科学家", "产品负责人", "商业化负责人"],
    exclusions: ["实习岗位", "外包岗位"],
    limit: "每轮最多核验 120 个岗位",
    runs: [
      {
        id: "run-0828",
        startedAt: "8 月 28 日 10:00",
        duration: "9 分 14 秒",
        status: "完成",
        scope: "核验 46 家公司和 108 个公开岗位",
        result: "产生 11 条新信号，其中 5 条待处理",
      },
      {
        id: "run-0825-ai",
        startedAt: "8 月 25 日 10:00",
        duration: "8 分 52 秒",
        status: "完成",
        scope: "核验 46 家公司和 101 个公开岗位",
        result: "产生 8 条新信号，其中 3 条已转化",
      },
    ],
    generatedSignals: [
      {
        title: "矩阵智算新增大模型平台负责人岗位",
        object: "矩阵智算",
        status: "待处理",
        tone: "warning",
        time: "昨天 10:09",
      },
      {
        title: "澄心科技开始招聘商业化负责人",
        object: "澄心科技",
        status: "观察中",
        tone: "info",
        time: "昨天 10:05",
      },
    ],
  },
  {
    id: "scan-career-signals",
    title: "重点候选人职业变化",
    description:
      "观察收藏夹内重点候选人的公开履历、成果和任职变化，只提示值得人工核实的变化。",
    status: "已暂停",
    tone: "neutral",
    frequency: "每两周周五 17:00",
    nextRun: "已暂停",
    lastRun: "8 月 15 日 17:00",
    lastDuration: "18 分 03 秒",
    newSignals: 2,
    pendingSignals: 0,
    scope: "重点候选人收藏夹 · 128 人",
    industries: ["人工智能", "机器人", "自动驾驶"],
    regions: ["不限"],
    stages: ["重点关注"],
    keywords: ["任职变化", "公开成果", "团队变化", "求职信号"],
    exclusions: ["未经交叉核验的社交媒体传言"],
    limit: "每轮最多核验 128 位候选人",
    runs: [
      {
        id: "run-0815-career",
        startedAt: "8 月 15 日 17:00",
        duration: "18 分 03 秒",
        status: "完成",
        scope: "核验 128 位候选人，发现 9 条可能变化",
        result: "产生 2 条新信号，均已处理",
      },
      {
        id: "run-0801-career",
        startedAt: "8 月 1 日 17:00",
        duration: "17 分 26 秒",
        status: "部分完成",
        scope: "核验 128 位候选人，17 个来源暂不可用",
        result: "产生 1 条新信号，已加入观察",
      },
    ],
    generatedSignals: [
      {
        title: "林昊公开资料显示职责范围扩大",
        object: "林昊",
        status: "已转化",
        tone: "success",
        time: "8 月 15 日 17:12",
      },
      {
        title: "周明远近期连续发布具身智能招聘信息",
        object: "周明远",
        status: "已忽略",
        tone: "neutral",
        time: "8 月 15 日 17:09",
      },
    ],
  },
  {
    id: "scan-autonomous-hiring",
    title: "自动驾驶核心团队变化",
    description:
      "跟踪自动驾驶公司核心团队、业务方向和公开招聘变化，出现可核验变化时生成信号。",
    status: "异常",
    tone: "warning",
    frequency: "每周一 09:00",
    nextRun: "等待问题处理",
    lastRun: "8 月 25 日 09:00",
    lastDuration: "3 分 42 秒",
    newSignals: 0,
    pendingSignals: 0,
    scope: "自动驾驶 · 北京、上海、深圳 · 核心团队",
    industries: ["自动驾驶"],
    regions: ["北京", "上海", "深圳"],
    stages: ["团队变化", "业务调整", "招聘变化"],
    keywords: ["自动驾驶", "感知", "规划控制", "端到端"],
    exclusions: ["普通销售岗位", "未经核验的传言"],
    limit: "每轮最多核验 60 家公司",
    runs: [
      {
        id: "run-0825-auto",
        startedAt: "8 月 25 日 09:00",
        duration: "3 分 42 秒",
        status: "部分完成",
        scope: "完成 18 家公司核验，公开搜索服务暂时不可用",
        result: "本轮没有产生可确认的新信号",
      },
      {
        id: "run-0818-auto",
        startedAt: "8 月 18 日 09:00",
        duration: "11 分 17 秒",
        status: "完成",
        scope: "核验 54 家公司，合并 12 条重复线索",
        result: "产生 3 条新信号，均已处理",
      },
    ],
    generatedSignals: [],
  },
];

export const planSteps = [
  {
    id: "scope",
    title: "确认岗位边界与找人范围",
    detail: "复用已解析岗位，校验硬要求、可放宽条件和本轮数量上限。",
    requirement:
      "VLA 算法负责人；机器人学习或多模态策略；产品落地与团队管理需要单独检查。",
  },
  {
    id: "recall",
    title: "并行检索并接收补充资料",
    detail:
      "检索系统候选人、人才版图、公开网络和论文专利，并接收用户上传的简历。",
    requirement: "多渠道找人；北京优先，异地人选保留地点意愿风险。",
  },
  {
    id: "enrich",
    title: "持续合并并执行匹配门禁",
    detail: "每批结果到达后立即补全、查重、合并和匹配。",
    requirement: "只保留角色、能力和经历满足岗位边界的人选。",
  },
  {
    id: "review",
    title: "交付候选人审核结果",
    detail: "等待用户决定联系、储备、观察或排除范围。",
    requirement: "本轮交付不超过 20 位值得判断的人选。",
  },
  {
    id: "followup",
    title: "按决定继续后续动作",
    detail: "邮件发送前逐次确认收件人、主题、正文和附件。",
    requirement: "先交付审核结果；没有用户确认时不发送邮件。",
  },
];

export const internalTasks = [
  {
    id: "internal-system",
    title: "检索系统候选人",
    status: "完成",
    tone: "success",
    action: "找到 6 位已有候选人，其中 3 位进入本轮审核",
    duration: "18 秒",
  },
  {
    id: "internal-resume-import",
    title: "读取用户上传的候选人资料",
    status: "完成",
    tone: "success",
    action: "12 份简历已解析并进入身份判断、查重与匹配门禁",
    duration: "2 分 18 秒",
  },
  {
    id: "internal-research",
    title: "研究来源补充人物线索",
    status: "完成",
    tone: "success",
    action: "从论文与专利补充 3 位候选人",
    duration: "2 分 16 秒",
  },
  {
    id: "internal-enrichment",
    title: "补全、查重与匹配",
    status: "等待用户",
    tone: "warning",
    action: "18 位候选人已通过门禁，等待审核",
    duration: "4 分 09 秒",
  },
];

export const evidenceRows = [
  {
    source: "岗位资料",
    finding: "要求 8 年以上机器人学习或多模态算法经验，并具备团队管理经历",
    freshness: "今天核验",
    confidence: "已确认",
  },
  {
    source: "星澜机器人官网",
    finding: "北京团队近期新增 VLA、具身智能和机器人学习相关岗位",
    freshness: "2 天前",
    confidence: "高可信",
  },
  {
    source: "猎头补充",
    finding: "可接受高级 IC 转管理，但不考虑纯学术且无产品落地经历的人选",
    freshness: "今天补充",
    confidence: "已确认",
  },
];

const candidateBase = [
  [
    "林昊",
    "拓界机器人",
    "机器人学习负责人",
    "上海",
    94,
    "强烈建议",
    "VLA 产品落地与团队管理经历完整",
    "薪资可能高于当前区间",
  ],
  [
    "周明远",
    "穹顶智能",
    "具身智能算法总监",
    "上海",
    86,
    "建议联系",
    "多模态策略学习与量产机器人经验匹配",
    "到岗时间尚未核实",
  ],
  [
    "赵星羽",
    "星澜机器人",
    "VLA 算法负责人",
    "北京",
    91,
    "强烈建议",
    "VLA 技术方向高度匹配，已承担算法负责人职责",
    "需要核实最近两年真机部署的个人贡献",
  ],
  [
    "陈楚宁",
    "灵跃科技",
    "灵巧操作算法负责人",
    "深圳",
    89,
    "建议联系",
    "从 0 到 1 搭建 VLA 团队并完成真机部署",
    "异地意愿未知",
  ],
  [
    "顾言川",
    "智行未来",
    "机器人基础模型专家",
    "北京",
    86,
    "建议联系",
    "基础模型、视觉语言与控制策略经验均衡",
    "管理规模偏小",
  ],
  [
    "许若航",
    "星河自动化",
    "机器人算法经理",
    "杭州",
    84,
    "加入储备",
    "工程化能力强，带领 8 人算法团队",
    "VLA 经验只有一年",
  ],
  [
    "沈亦辰",
    "启元动力",
    "强化学习负责人",
    "上海",
    83,
    "加入储备",
    "强化学习与 sim-to-real 经验突出",
    "多模态模型经验不足",
  ],
  [
    "唐可欣",
    "深境智能",
    "多模态算法 Lead",
    "北京",
    82,
    "加入储备",
    "多模态理解与端侧部署经验完整",
    "机器人控制经验需核实",
  ],
  [
    "陆知行",
    "矩阵机器人",
    "具身智能高级工程师",
    "苏州",
    80,
    "保留观察",
    "技术深度符合，近期负责操作策略",
    "缺少正式管理经验",
  ],
  [
    "叶晨风",
    "开源机器人社区",
    "核心维护者",
    "上海",
    79,
    "保留观察",
    "开源影响力和系统能力突出",
    "当前任职与求职状态不完整",
  ],
  [
    "韩思源",
    "澜舟具身",
    "机器人感知负责人",
    "北京",
    78,
    "保留观察",
    "感知和三维场景理解能力强",
    "策略学习不是主要方向",
  ],
  [
    "方知远",
    "云端智造",
    "算法平台主管",
    "杭州",
    77,
    "保留观察",
    "团队管理经验充分",
    "具身智能项目证据较少",
  ],
  [
    "罗一川",
    "灵工科技",
    "机器人学习专家",
    "深圳",
    76,
    "加入储备",
    "模仿学习和数据闭环经验清晰",
    "工作年限略低于要求",
  ],
  [
    "蒋舒扬",
    "联合创新中心",
    "研究科学家",
    "北京",
    74,
    "谨慎评估",
    "研究方向匹配且有真机实验",
    "身份和商业经历需要消歧",
  ],
  [
    "伍清禾",
    "未来工场",
    "控制算法负责人",
    "广州",
    72,
    "保留观察",
    "控制系统工程经验扎实",
    "多模态方向匹配有限",
  ],
  [
    "宋怀瑾",
    "云枢机器人",
    "高级算法工程师",
    "南京",
    69,
    "不建议",
    "有移动机器人量产经验",
    "角色层级和 VLA 方向均不足",
  ],
  [
    "贺嘉言",
    "知行实验室",
    "博士后",
    "上海",
    66,
    "不建议",
    "论文质量高且方向接近",
    "缺少企业经历和团队管理",
  ],
  [
    "孟予安",
    "前沿智能研究院",
    "研究员",
    "北京",
    62,
    "不建议",
    "具身智能研究经历明确",
    "岗位角色与落地要求差距明显",
  ],
];

export const candidates = candidateBase.map(
  (
    [name, company, role, city, score, recommendation, strength, risk],
    index,
  ) => ({
    id: `candidate-${index + 1}`,
    name,
    company,
    role,
    city,
    score,
    recommendation,
    strength,
    risk,
    years: 8 + (index % 6),
    education: index % 4 === 0 ? "博士" : "硕士",
    source: ["系统候选人", "用户上传简历", "公开职业资料", "论文线索"][
      index % 4
    ],
    skills: ["VLA", "机器人学习", "多模态模型"].slice(0, 2 + (index % 2)),
  }),
);

export const sideTaskRows = [
  [
    "task-recommend-linhao",
    "为林昊生成客户推荐报告",
    "候选人推荐报告",
    "具身智能 VLA 算法负责人",
    "等待用户",
    "warning",
    "刚刚",
  ],
  [
    "task-hand-team",
    "核验灵巧手团队负责人",
    "人物身份核验",
    "星澜机器人人才版图",
    "等待用户",
    "warning",
    "16 分钟前",
  ],
  [
    "task-shlab",
    "补充上海人工智能实验室具身智能团队",
    "公开资料调研",
    "具身智能核心人才版图",
    "运行中",
    "info",
    "已运行 24 分钟",
  ],
  [
    "task-zhaoxingyu",
    "消歧赵星羽的论文与任职身份",
    "人物消歧",
    "VLA 候选人审核",
    "失败",
    "danger",
    "7 分钟前",
  ],
  [
    "task-li-auto",
    "核验理想汽车机器人团队招聘信号",
    "公司信号核验",
    "客户开发",
    "完成",
    "success",
    "今天 08:12",
  ],
  [
    "task-patent",
    "整理灵巧手结构专利共同发明人",
    "专利关系探索",
    "灵巧手人才版图",
    "完成",
    "success",
    "昨天 19:40",
  ],
  [
    "task-cloudchip",
    "查找云脉芯能团队联系人",
    "联系人探索",
    "云脉芯能公司资料",
    "已暂停",
    "neutral",
    "昨天 17:22",
  ],
  [
    "task-role",
    "确认启元动力算法负责人任职变化",
    "任职核验",
    "候选人沈亦辰",
    "等待外部",
    "neutral",
    "昨天 14:09",
  ],
];

export const sideTasks = sideTaskRows.map(
  ([id, title, type, object, status, tone, time]) => ({
    id,
    title,
    type,
    object,
    status,
    tone,
    time,
    owner: "沈岚",
    summary:
      id === "task-recommend-linhao"
        ? "基于岗位、候选人和匹配证据生成客户推荐报告，并等待用户提出修改要求。"
        : id === "task-hand-team"
          ? "公开来源中出现两位同名负责人，需要核验身份、任职和团队关系。"
          : "该任务具有独立目标和明确交付，结果将回流关联业务对象。",
  }),
);

const sideTaskBusinessScenarios = {
  "task-recommend-linhao": "岗位招聘",
  "task-hand-team": "人才摸排",
  "task-shlab": "人才摸排",
  "task-zhaoxingyu": "岗位招聘",
  "task-li-auto": "客户开发",
  "task-patent": "人才摸排",
  "task-cloudchip": "客户开发",
  "task-role": "候选人求职",
};

export const workItems = [
  ...workstreamHistory.map((item) => ({
    ...item,
    category: item.type,
    scenario: item.type,
  })),
  {
    ...sideTasks.find((item) => item.id === "task-hand-team"),
    category: "身份核验",
    scenario: sideTaskBusinessScenarios["task-hand-team"],
  },
  {
    id: "task-interview-summary",
    title: "整理林昊的面试反馈",
    type: "信息整理",
    object: "候选人林昊",
    status: "可继续",
    tone: "info",
    time: "今天 09:31",
    owner: "沈岚",
    category: "信息整理",
    scenario: "岗位招聘",
    summary: "已整理三条面试反馈，可以继续补充信息或要求 Hunter 调整摘要。",
  },
];

export const signals = [
  {
    id: "signal-cloudchip",
    type: "公司变化",
    title: "云脉芯能正在组建机器人芯片团队",
    object: "云脉芯能",
    priority: "高优先级",
    status: "待处理",
    tone: "warning",
    time: "今天 09:12",
    evidence: 4,
    summary: "招聘页面、公众号和两位团队成员公开资料均出现机器人芯片方向变化。",
    sources: ["公司招聘页面", "公司公众号", "团队成员公开资料", "行业活动议程"],
    changes: [
      "新增机器人芯片算法岗位",
      "一位芯片架构负责人公开加入",
      "上海办公室开始招聘",
    ],
  },
  {
    id: "signal-tuoji",
    type: "招聘动态",
    title: "拓界智驾新增感知与规划团队招聘页面",
    object: "拓界智驾",
    priority: "建议关注",
    status: "观察中",
    tone: "info",
    time: "今天 08:36",
    evidence: 3,
    summary: "新增岗位与近期融资消息相互印证，但尚未确认是否开放猎头合作。",
    sources: ["公司招聘页面", "融资新闻", "员工公开动态"],
    changes: ["新增感知算法负责人", "北京与上海同时扩招"],
  },
  {
    id: "signal-chensong",
    type: "候选人动向",
    title: "陈松的公开任职信息发生变化",
    object: "陈松 · 自动驾驶技术经理",
    priority: "建议关注",
    status: "待处理",
    tone: "info",
    time: "昨天 17:20",
    evidence: 2,
    summary: "公开主页移除了原公司职位，最近一周出现多次求职相关活动。",
    sources: ["个人公开主页", "行业活动报名信息"],
    changes: ["移除原公司职位", "更新技术方向说明"],
  },
  {
    id: "signal-xinglan",
    type: "招聘动态",
    title: "星澜机器人 VLA 团队扩招信息已转化",
    object: "星澜机器人",
    priority: "已处理",
    status: "已转化",
    tone: "success",
    time: "8 月 18 日",
    evidence: 5,
    summary: "已转化为岗位招聘任务“具身智能 VLA 算法负责人”。",
    sources: ["客户沟通", "岗位 JD", "公司招聘页", "团队成员动态", "猎头补充"],
    changes: ["已创建正式岗位", "已启动岗位招聘任务"],
  },
  {
    id: "signal-expired",
    type: "公司变化",
    title: "旧招聘页面中的机器人岗位已下线",
    object: "远航智能",
    priority: "已失效",
    status: "已失效",
    tone: "neutral",
    time: "8 月 15 日",
    evidence: 2,
    summary: "连续三次检查未发现招聘页面，原信号不再具有行动价值。",
    sources: ["历史招聘页", "官网复查"],
    changes: ["招聘页面下线"],
  },
];
