import { waitForOpportunityDraft, replyToAsset } from "./opportunity-helpers";
import { test, expect } from "@playwright/test";
import { mkdir } from "node:fs/promises";
import * as XLSX from "xlsx";
import JSZip from "jszip";
import { expectNoHorizontalOverflow, trackConsoleErrors } from "../stage1/helpers";
import { confirmClientOpportunity } from "../stage3/client-helpers";
import { createOpportunitySeed } from "../../src/stage4/opportunity-seed.js";
test.use({ actionTimeout: 10000 });

const storeKey = "hunter-opportunity-lifecycle-v1";
const snapshot = (page) => page.evaluate((key) => JSON.parse(localStorage.getItem(key)), storeKey);
const field = (page, label) => page.locator(".s4-form-field").filter({ has: page.locator("span", { hasText: new RegExp("^" + label + "\\*?$") }) }).locator("input,textarea");
const button = (page, name) => page.getByRole("button", { name, exact: true });
const heading = (page, name) => page.getByRole("heading", { name, exact: true });
const jd = "岗位职责\n负责工业视觉算法研发、部署与评测。\n任职要求\n熟悉 Python 与计算机视觉，有真实业务落地经验。";

async function createCompany(page, name) {
  await page.goto("#/companies/new?name=" + encodeURIComponent(name));
  await button(page, "创建公司").click();
  await expect(heading(page, name)).toBeVisible();
  return page.url().split("/companies/")[1].split("?")[0];
}
async function createOpportunity(page, companyId, title) {
  await page.goto("#/opportunities/new?companyId=" + companyId);
  await field(page, "机会名称").fill(title);
  await field(page, "招聘需求摘要").fill("招聘负责人确认需要算法和平台两个招聘方向。");
  await field(page, "发现依据").fill("2026-09-08 客户电话确认真实需求；合作服务预算不是候选人薪酬。");
  await button(page, "创建招聘机会").click();
  await expect(heading(page, title)).toBeVisible();
  return page.url().split("/opportunities/")[1].split("?")[0];
}
async function addDirection(page, name) {
  await page.getByRole("tab", { name: /^招聘方向/ }).click();
  await button(page, "添加方向").click();
  await field(page, "方向名称").fill(name);
  await field(page, "需求摘要").fill("客户确认本方向需要独立招聘。");
  await field(page, "已取得的岗位 JD").fill(jd);
  await button(page, "保存方向").click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
}
async function futureTime(page, label) {
  await page.locator(".s4-form-field").filter({ has: page.locator("span", { hasText: label }) }).locator(".s4-date-picker > button").click();
  await button(page, "下个月").click();
  await button(page, "下个月").click();
  await page.locator(".s4-day-grid").getByRole("button", { name: "17", exact: true }).click();
  await page.getByRole("textbox", { name: "小时", exact: true }).fill("10");
  await page.getByRole("textbox", { name: "分钟", exact: true }).fill("17");
  await page.locator(".s4-date-time-inputs").getByRole("button", { name: "确定", exact: true }).click();
}
async function capture(page, name) {
  await mkdir("artifacts/opportunity-lifecycle", { recursive: true });
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 960 });
    await expectNoHorizontalOverflow(page);
    await page.screenshot({ path: "artifacts/opportunity-lifecycle/" + name + "-" + width + ".png", fullPage: true, animations: "disabled" });
  }
  await page.setViewportSize({ width: 1440, height: 960 });
}

for (const company of ["澄岳机器人", "临川自动化"]) {
  test(company + "：新公司、机会、跟进提醒、手工与 AI 岗位、候选人审核和交接完整持久化", async ({ page }) => {
    test.setTimeout(120000);
    const errors = trackConsoleErrors(page);
    const companyId = await createCompany(page, company);
    const title = company + "研发团队补强";
    const id = await createOpportunity(page, companyId, title);
    await expect(page.getByText("未关联联系人", { exact: true })).toBeVisible();
    await button(page, "记录跟进").click();
    await field(page, "跟进内容").fill("客户已确认两个招聘方向，薪酬和具体人数还未确定。");
    await button(page, "保存记录").click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await button(page, "安排下次跟进").click();
    await field(page, "下次跟进事项").fill("确认岗位职责与预算边界");
    await futureTime(page, "下次跟进时间");
    await button(page, "保存安排").click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await page.reload();
    expect((await snapshot(page)).followups.find((item) => item.opportunityId === id).dueAt).toContain(":17:");
    await page.goto("#/demo/opportunities");
    await button(page, "目标招聘机会").click();
    await button(page, title).click();
    await button(page, "推进到跟进到期").click();
    const stateDue = await snapshot(page);
    expect(stateDue.notifications.filter((item) => item.opportunityId === id)).toHaveLength(1);
    await page.goto("#/opportunities/" + id);
    await expect(page.getByText("待跟进", { exact: true })).toBeVisible();
    await button(page, "记录跟进").click();
    await field(page, "跟进内容").fill("客户补充完整 JD，确认需求交接；薪酬仍需独立确认。");
    await page.getByRole("checkbox", { name: "完成当前事项：确认岗位职责与预算边界" }).click();
    await button(page, "保存并完成本次跟进").click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await addDirection(page, "工业视觉算法工程师");
    await addDirection(page, "视觉平台工程师");
    const row = page.locator(".s4-direction-list article").filter({ hasText: "工业视觉算法工程师" });
    await row.getByRole("button", { name: "形成岗位", exact: true }).click();
    await expect(field(page, "薪资范围")).toHaveValue("");
    await button(page, "确认创建并关联").click();
    await expect(heading(page, "岗位已形成")).toBeVisible();
    const firstState = await snapshot(page);
    const first = firstState.positions.find((item) => item.managed && item.companyId === companyId);
    expect(first.pipeline).toEqual([]);
    expect(first.processing).toEqual([]);
    expect(firstState.tasks).toEqual([]);
    await button(page, "返回招聘方向").click();
    await page.locator(".s4-direction-list article").filter({ hasText: "视觉平台工程师" }).getByRole("button", { name: "形成岗位", exact: true }).click();
    await button(page, "AI 整理岗位").click();
    await expect(heading(page, "待确认的岗位")).toBeVisible();
    expect((await snapshot(page)).tasks.at(-1).draft.patch.name).toBe("视觉平台工程师");
    await replyToAsset(page, "公司：星澜机器人");
    await replyToAsset(page, "是");
    await expect(page.getByText(/不能在本次岗位写入中改为其他公司/).first()).toBeVisible();
    expect((await snapshot(page)).positions).toHaveLength(firstState.positions.length);
    await replyToAsset(page, "公司：" + company);
    await replyToAsset(page, "是");
    await expect(page.getByRole("link", { name: "查看岗位详情", exact: true })).toBeVisible();
    const createdVersion = (await snapshot(page)).positions.at(-1).version;
    await replyToAsset(page, "公司：星澜机器人");
    await replyToAsset(page, "工作地点：上海");
    await replyToAsset(page, "是");
    expect((await snapshot(page)).positions.at(-1).version).toBe(createdVersion);
    await expect(page.getByText(/不能在本次岗位写入中改为其他公司/).first()).toBeVisible();
    await replyToAsset(page, "公司：" + company);
    await replyToAsset(page, "是");
    expect((await snapshot(page)).positions.at(-1).company).toBe(company);
    expect((await snapshot(page)).positions.at(-1).location).toBe("上海");
    await page.getByRole("link", { name: "查看岗位详情", exact: true }).last().click();
    await expect(heading(page, "视觉平台工程师")).toBeVisible();
    await button(page, "开始找人").click();
    await button(page, "创建招聘任务").click();
    await expect(heading(page, "候选人审核")).toBeVisible();
    await page.getByRole("checkbox", { name: /选择.*林昊/ }).click();
    await button(page, "将所选候选人加入岗位储备").click();
    await expect(page.getByText(/已将 林昊 加入岗位储备/)).toBeVisible();
    const final = await snapshot(page);
    const second = final.positions.find((item) => item.name === "视觉平台工程师" && item.companyId === companyId);
    expect(second.pipeline).toHaveLength(1);
    expect(second.pipeline[0].stage).toBe("reserve");
    expect(final.tasks.find((item) => item.kind === "recruiting").positionId).toBe(second.id);
    await page.goto("#/positions/" + second.id + "?tab=pipeline");
    if (company === "澄岳机器人") await capture(page, "position-pipeline");
    await page.goto("#/opportunities/" + id);
    await button(page, "完成机会").click();
    await page.getByRole("dialog").getByRole("button", { name: "确认", exact: true }).click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await page.reload();
    expect((await snapshot(page)).opportunities.find((item) => item.id === id).status).toBe("已完成");
    if (company === "澄岳机器人") await capture(page, "opportunity-complete");
    await errors();
  });
}

test("任务输入、草稿必填、确认写入和后续更新使用实际数据", async ({ page }) => {
  const errors = trackConsoleErrors(page);
  const prompt = "公司：星澜机器人\n机会名称：增量强化学习团队\n招聘需求摘要：客户确认扩建强化学习研发团队\n需求依据：2026-09-08 邮件确认";
  await page.goto("#/new?kind=opportunity&prompt=" + encodeURIComponent(prompt));
  await page.getByRole("button", { name: "发送", exact: true }).click();
  await waitForOpportunityDraft(page);
  await expect(heading(page, "待确认的招聘机会")).toBeVisible();
  expect((await snapshot(page)).opportunities).toHaveLength(4);
  await replyToAsset(page, "发现依据：");
  await replyToAsset(page, "是");
  await expect(page.getByText(/请说明发现依据/).first()).toBeVisible();
  await replyToAsset(page, "发现依据：原始邮件明确确认了需求");
  await replyToAsset(page, "是");
  await expect(page.getByRole("link", { name: "查看招聘机会", exact: true })).toBeVisible();
  const first = await snapshot(page);
  expect(first.opportunities).toHaveLength(5);
  const taskId = first.tasks[0].id;
  const id = first.opportunities.at(-1).id;
  await page.reload();
  await expect(page.getByRole("link", { name: "查看招聘机会", exact: true })).toBeVisible();
  await page.locator(".s2-composer textarea").fill("招聘需求摘要：客户确认改为强化学习与真机部署两个方向\n需求依据：第二次电话补充确认");
  await button(page, "发送").click();
  await waitForOpportunityDraft(page);
  await expect(heading(page, "待确认的招聘机会")).toBeVisible();
  await replyToAsset(page, "是");
  await expect(heading(page, "待确认的招聘机会")).toHaveCount(0);
  const updated = await snapshot(page);
  expect(updated.opportunities).toHaveLength(5);
  expect(updated.opportunities.find((item) => item.id === id).summary).toContain("真机部署");
  expect(updated.tasks.find((item) => item.id === taskId).results).toHaveLength(2);
  await errors();
});

test("机会导入旧链接不误开其他向导，新建类型已移除", async ({ page }) => {
  const errors = trackConsoleErrors(page);
  await page.goto("#/data/imports?type=opportunities");
  await expect(page).toHaveURL(/#\/data\/imports$/);
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await button(page, "新建导入").click();
  await page.getByRole("dialog").getByRole("button", { name: "资产类型*", exact: true }).click();
  await expect(page.locator(".s4-select-panel").getByRole("button", { name: "招聘机会", exact: true })).toHaveCount(0);
  await expect(page.locator(".s4-select-panel").getByRole("button", { name: "岗位", exact: true })).toBeVisible();
  await page.goto("#/demo/opportunities");
  await expect(button(page, "统一导入")).toHaveCount(0);
  await expect(button(page, "下载 CSV 模板")).toHaveCount(0);
  await errors();
});

test("关联已有岗位、解除关系、方向拆分和回收恢复不删除独立岗位", async ({ page }) => {
  const errors = trackConsoleErrors(page);
  await page.goto("#/positions/new");
  await field(page, "岗位名称").fill("独立创建的算法岗位");
  await page.getByRole("button", { name: "招聘公司*", exact: true }).click();
  await button(page, "星澜机器人").click();
  await field(page, "完整岗位 JD").fill(jd);
  await button(page, "创建岗位").click();
  await expect(heading(page, "独立创建的算法岗位")).toBeVisible();
  const positionId = (await snapshot(page)).positions.at(-1).id;
  const id = await createOpportunity(page, "company-xinglan", "混合方向需求");
  await addDirection(page, "算法方向");
  await page.getByRole("button", { name: "形成岗位", exact: true }).click();
  await page.getByRole("tab", { name: "关联已有岗位" }).click();
  await page.getByRole("button", { name: "选择已有岗位*", exact: true }).click();
  await button(page, "独立创建的算法岗位 · 招聘中").click();
  await expect(page.getByText(jd, { exact: true })).toBeVisible();
  await button(page, "确认关联岗位").click();
  await expect(heading(page, "岗位已形成")).toBeVisible();
  expect((await snapshot(page)).positions).toHaveLength(6);
  await button(page, "返回招聘方向").click();
  await button(page, "管理关联").click();
  await page.getByRole("dialog").getByRole("button", { name: "确认", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  expect((await snapshot(page)).positions.find((item) => item.id === positionId).origin.opportunityId).toBe("");
  await button(page, "拆分").click();
  await field(page, "方向 1").fill("算法研究");
  await field(page, "方向 2").fill("算法部署");
  await button(page, "确认拆分").click();
  await expect(page.locator(".s4-direction-list article")).toHaveCount(2);
  await page.locator(".s4-direction-list article").filter({ hasText: "算法部署" }).getByRole("button", { name: "不再推进", exact: true }).click();
  await field(page, "不再推进原因").fill("客户决定该方向暂缓招聘");
  await page.getByRole("dialog").getByRole("button", { name: "确认", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await button(page, "完成机会").click();
  await page.getByRole("dialog").getByRole("button", { name: "确认", exact: true }).click();
  await expect(page.getByText(/请先形成至少一个岗位/)).toBeVisible();
  await page.getByRole("dialog").getByRole("button", { name: "取消", exact: true }).click();
  await button(page, "删除").click();
  await button(page, "移入回收站").click();
  await expect(page).toHaveURL(/#\/opportunities$/);
  await page.goto("#/recycle-bin");
  await page.locator(".s4-recycle-table article").filter({ hasText: "混合方向需求" }).getByRole("button", { name: "恢复", exact: true }).click();
  await button(page, "确认恢复").click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.goto("#/opportunities/" + id + "?tab=directions");
  await expect(page.locator(".s4-direction-list article")).toHaveCount(2);
  expect((await snapshot(page)).positions.find((item) => item.id === positionId).deletedAt).toBe(null);
  await page.locator(".s4-direction-list article").filter({ hasText: "算法研究" }).getByRole("button", { name: "形成岗位", exact: true }).click();
  await page.getByRole("tab", { name: "关联已有岗位" }).click();
  await page.getByRole("button", { name: "选择已有岗位*", exact: true }).click();
  await button(page, "独立创建的算法岗位 · 招聘中").click();
  await button(page, "确认关联岗位").click();
  await button(page, "返回招聘方向").click();
  await addDirection(page, "新平台方向");
  await page.locator(".s4-direction-list article").filter({ hasText: "新平台方向" }).getByRole("button", { name: "形成岗位", exact: true }).click();
  await button(page, "确认创建并关联").click();
  await button(page, "返回招聘方向").click();
  await button(page, "完成机会").click();
  await page.getByRole("dialog").getByRole("button", { name: "确认", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  const final = await snapshot(page);
  expect(final.opportunities.find((item) => item.id === id).status).toBe("已完成");
  expect(final.positions).toHaveLength(7);
  expect(final.positions.find((item) => item.id === positionId).jd).toBe(jd);
  await errors();
});

test("仅分析、自动授权、取消草稿与写入失败重试", async ({ page }) => {
  const errors = trackConsoleErrors(page);
  const prompt = "公司：星澜机器人\n机会名称：授权测试独立需求\n招聘需求摘要：客户确认补充平台团队\n需求依据：负责人电话确认";
  await page.goto("#/new?kind=opportunity&prompt=" + encodeURIComponent(prompt));
  await button(page, "执行前确认").click();
  await page.getByRole("option", { name: /^仅分析/ }).click();
  await button(page, "发送").click();
  await waitForOpportunityDraft(page);
  await expect(heading(page, "待确认的招聘机会")).toBeVisible();
  await replyToAsset(page, "是");
  await expect(page.getByText(/未获得正式写入授权/).first()).toBeVisible();
  await replyToAsset(page, "否");
  await expect(page.getByText("草稿已保留，未写入正式资料", { exact: true })).toBeVisible();
  await button(page, "仅分析").click();
  await page.getByRole("option", { name: /^执行前确认/ }).click();
  const taskUrl = page.url();
  await page.goto("#/demo/opportunities");
  await page.getByRole("button", { name: "故障操作", exact: true }).click();
  await page.goto(taskUrl);
  await page.locator(".s2-composer textarea").fill("是");
  await button(page, "发送").click();
  await expect(page.getByText(/模拟失败：资料和输入已保留，请重试/).first()).toBeVisible();
  await expect(page.locator(".s2-composer textarea")).toHaveValue("是");
  expect((await snapshot(page)).opportunities).toHaveLength(4);
  expect((await snapshot(page)).tasks.at(-1).draft.patch.title).toBe("授权测试独立需求");
  await replyToAsset(page, "是");
  await expect(page.getByRole("link", { name: "查看招聘机会", exact: true })).toBeVisible();
  await page.goto("#/new?kind=opportunity&prompt=" + encodeURIComponent(prompt.replace("授权测试独立需求", "自动授权独立需求").replace("平台团队", "部署团队")));
  await button(page, "执行前确认").click();
  await page.getByRole("option", { name: /^自动执行/ }).click();
  await button(page, "发送").click();
  await waitForOpportunityDraft(page);
  await expect(heading(page, "待确认的招聘机会")).toBeVisible();
  expect((await snapshot(page)).opportunities).toHaveLength(5);
  await replyToAsset(page, "是");
  await expect(page.getByRole("link", { name: "查看招聘机会", exact: true })).toBeVisible();
  expect((await snapshot(page)).opportunities).toHaveLength(6);
  expect((await snapshot(page)).notifications.filter((item) => item.kind === "asset-write")).toHaveLength(0);
  await page.getByPlaceholder("补充需求、客户回复或新的依据").fill("招聘需求摘要：部署团队需求已更新，预算仍待核实");
  await button(page, "发送").click();
  await expect(heading(page, "待确认的招聘机会")).toBeVisible();
  expect((await snapshot(page)).opportunities.at(-1).summary).not.toContain("预算仍待核实");
  await replyToAsset(page, "是");
  expect((await snapshot(page)).opportunities.at(-1).summary).toContain("预算仍待核实");
  expect((await snapshot(page)).notifications.filter((item) => item.kind === "asset-write")).toHaveLength(0);
  await errors();
});

test("通知已读不完成跟进、改期去重、无任务工作台和只读边界", async ({ page }) => {
  const errors = trackConsoleErrors(page);
  const id = await createOpportunity(page, "company-xinglan", "提醒边界需求");
  await button(page, "安排下次跟进").click();
  await field(page, "下次跟进事项").fill("独立机会待跟进事项");
  await futureTime(page, "下次跟进时间");
  await button(page, "保存安排").click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.goto("#/demo/opportunities");
  await button(page, "目标招聘机会").click();
  await button(page, "提醒边界需求").click();
  await button(page, "失败范围").click();
  await button(page, "下一次提醒派发").click();
  await button(page, "故障操作").click();
  await button(page, "推进到跟进到期").click();
  await expect(page.getByText("模拟失败：资料和输入已保留，请重试。", { exact: true })).toBeVisible();
  expect((await snapshot(page)).notifications).toHaveLength(0);
  await button(page, "推进到跟进到期").click();
  await button(page, "推进到跟进到期").click();
  expect((await snapshot(page)).notifications).toHaveLength(1);
  await page.goto("#/home?state=empty");
  await page.getByRole("button", { name: /^行动队列/ }).click();
  await expect(page.getByText("独立机会待跟进事项", { exact: true })).toBeVisible();
  await button(page, "打开通知").click();
  await page.getByRole("button", { name: /提醒边界需求：独立机会待跟进事项/ }).click();
  await expect(page).toHaveURL(new RegExp("opportunities/" + id));
  const state = await snapshot(page);
  expect(state.notifications[0].read).toBe(true);
  expect(state.followups[0].status).toBe("due");
  await button(page, "记录跟进").click();
  await field(page, "跟进内容").fill("客户暂未回复，保持当前待跟进事项");
  await button(page, "保存记录").click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  expect((await snapshot(page)).followups[0].status).toBe("due");
  await button(page, "修改下次跟进").click();
  await futureTime(page, "下次跟进时间");
  await button(page, "保存安排").click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  expect((await snapshot(page)).followups).toHaveLength(1);
  expect((await snapshot(page)).notifications[0].resolved).toBe(true);
  await page.goto("#/demo/opportunities");
  await page.getByRole("checkbox", { name: "模拟无修改权限" }).click();
  await page.goto("#/opportunities/" + id);
  await expect(button(page, "编辑资料")).toBeDisabled();
  await expect(button(page, "安排下次跟进")).toHaveCount(0);
  await expect(button(page, "修改下次跟进")).toBeDisabled();
  await capture(page, "opportunity-readonly");
  await errors();
});

test("客户开发回复保留原文、联系人、任务来源和唯一跟进归属", async ({ page }) => {
  test.setTimeout(70000);
  const errors = trackConsoleErrors(page);
  await page.goto("#/tasks/client-xinglan");
  await confirmClientOpportunity(page);
  await expect(page.getByText("公司与联系人结果可以审核")).toBeVisible({ timeout: 15000 });
  await button(page, "打开公司与联系人审核").click();
  await button(page, "保存审核结果").click();
  await button(page, "确认并发送").click();
  await expect(page.getByText("等待陈雨回复招聘合作邮件")).toBeVisible();
  const reply = "公司：星澜机器人\n机会名称：邮件确认的算法团队\n招聘需求摘要：客户确认新增两个算法研发方向\n需求依据：陈雨邮件明确确认需要猎头协助，薪酬尚未明确";
  await page.getByPlaceholder("输入补充信息、决定或新的要求").fill(reply);
  await button(page, "发送").click();
  await waitForOpportunityDraft(page);
  await expect(heading(page, "待确认的招聘机会")).toBeVisible();
  await replyToAsset(page, "是");
  await expect(heading(page, "待确认的招聘机会")).toHaveCount(0);
  await expect(page.getByRole("link", { name: "查看招聘机会", exact: true })).toBeVisible();
  let state = await snapshot(page);
  expect(state.opportunities).toHaveLength(5);
  const opportunity = state.opportunities.at(-1);
  expect(opportunity.contactId).toBe("contact-chenyu");
  expect(opportunity.sources.at(-1).content).toContain(reply);
  expect(opportunity.sources.at(-1).taskId).toBe("client-xinglan");
  expect(opportunity.sources.at(-1).kind).toBe("reply");
  await button(page, "安排下次跟进").click();
  await field(page, "下次跟进事项").fill("确认邮件需求的完整职责");
  await futureTime(page, "下次跟进时间");
  await button(page, "保存安排").click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("link", { name: "查看招聘机会", exact: true }).click();
  await expect(button(page, "返回原任务处理")).toBeVisible();
  await expect(button(page, "安排下次跟进")).toHaveCount(0);
  await page.reload();
  state = await snapshot(page);
  expect(state.followups).toHaveLength(1);
  expect(state.followups[0].ownerTaskId).toBe("client-xinglan");
  await button(page, "返回原任务处理").click();
  await expect(page.getByRole("link", { name: "查看招聘机会", exact: true })).toBeVisible();
  await page.goto("#/opportunities/" + opportunity.id);
  await button(page, "关闭机会").click();
  await field(page, "关闭原因").fill("本轮暂停，但原任务继续沟通下一轮安排");
  await page.getByRole("dialog").getByRole("button", { name: "确认", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await button(page, "删除").click();
  await button(page, "移入回收站").click();
  await expect(page).toHaveURL(/#\/opportunities$/);
  await page.goto("#/tasks/client-xinglan");
  await expect(page.getByText("来源机会已进入回收站，任务跟进仍然保留", { exact: true })).toBeVisible();
  await button(page, "记录跟进").click();
  await field(page, "跟进内容").fill("客户约定下轮再联系，原任务完成当前事项。");
  await page.getByRole("checkbox", { name: /^完成当前事项/ }).click();
  await button(page, "保存并完成本次跟进").click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  expect((await snapshot(page)).followups[0].status).toBe("done");
  await errors();
});

test("新建机会可同时记录首次跟进并安排未来事项，失败整体不写入", async ({ page }) => {
  await page.goto("#/companies/company-xinglan?tab=recruiting");
  await button(page, "新建招聘机会").click();
  await expect(page).toHaveURL(/opportunities\/new\?companyId=company-xinglan/);
  await expect(field(page, "所属公司")).toBeDisabled();
  await button(page, "取消").click();
  await expect(page).toHaveURL(/companies\/company-xinglan\?tab=recruiting/);
  await button(page, "新建招聘机会").click();
  await field(page, "机会名称").fill("带首次跟进的研发需求");
  await field(page, "招聘需求摘要").fill("客户确认新增测试工程方向");
  await field(page, "发现依据").fill("电话确认实际需求");
  await button(page, "相关联系人").click();
  await button(page, "陈雨 · 招聘负责人").click();
  await page.getByRole("checkbox", { name: "同时记录首次跟进" }).click();
  await field(page, "跟进内容").fill("已取得客户对需求存在的确认");
  await page.getByRole("checkbox", { name: "同时安排下次跟进" }).click();
  await button(page, "创建招聘机会").click();
  await expect(page.getByText("请输入下次跟进事项。", { exact: true })).toBeVisible();
  const before = await snapshot(page);
  expect(before?.opportunities.length || 4).toBe(4);
  await field(page, "下次跟进事项").fill("收取岗位职责");
  await futureTime(page, "下次跟进时间");
  await button(page, "创建招聘机会").click();
  await expect(heading(page, "带首次跟进的研发需求")).toBeVisible();
  await page.reload();
  const state = await snapshot(page);
  expect(state.opportunities.at(-1).records).toHaveLength(1);
  expect(state.opportunities.at(-1).contactId).toBe("contact-chenyu");
  expect(state.followups[0].opportunityId).toBe(state.opportunities.at(-1).id);
});

test("洞察只创建核验任务，加入原任务后再确认正式机会", async ({ page }) => {
  const errors = trackConsoleErrors(page);
  await page.goto("#/signals?signal=signal-cloudchip");
  await button(page, "处理洞察").click();
  await page.getByRole("dialog").getByRole("button", { name: "创建任务", exact: true }).click();
  await waitForOpportunityDraft(page);
  await expect(heading(page, "待确认的招聘机会")).toBeVisible();
  let state = await snapshot(page);
  expect(state.opportunities).toHaveLength(4);
  expect(state.tasks).toHaveLength(1);
  const taskId = state.tasks[0].id;
  await page.getByRole("link", { name: "查看来源洞察", exact: true }).click();
  await expect(page).toHaveURL(/signal=signal-cloudchip/);
  await page.reload();
  await expect(page.getByText("来源与证据已保存在该任务。", { exact: true })).toBeVisible();
  await page.goto("#/signals?signal=signal-tuoji");
  await button(page, "立即复查").click();
  await button(page, "处理洞察").click();
  await page.getByRole("radio", { name: /^加入已有任务/ }).click();
  await page.getByRole("radiogroup", { name: "已有任务" }).getByRole("radio").click();
  await button(page, "加入所选任务").click();
  await expect(page).toHaveURL(new RegExp("tasks/" + taskId));
  await waitForOpportunityDraft(page);
  await expect(heading(page, "待确认的招聘机会")).toBeVisible();
  state = await snapshot(page);
  expect(state.tasks).toHaveLength(1);
  expect(state.tasks[0].sourceSignals).toHaveLength(2);
  expect(state.opportunities).toHaveLength(4);
  await replyToAsset(page, "公司：拓界机器人\n机会名称：洞察核验后的新招聘需求\n招聘需求摘要：已与公司核实，确实需要平台工程师\n发现依据：后续电话核实，不以招聘网页变化代替确认");
  await replyToAsset(page, "是");
  await expect(page.getByRole("link", { name: "查看招聘机会", exact: true })).toBeVisible();
  expect((await snapshot(page)).opportunities.at(-1).sources[0].content).toContain("拓界智驾新增感知");
  await errors();
});

async function docxFixture(content) {
  const zip = new JSZip();
  zip.file("[Content_Types].xml", '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');
  zip.file("_rels/.rels", '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');
  zip.file("word/document.xml", '<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>' + content.split("\n").map((line) => "<w:p><w:r><w:t>" + line + "</w:t></w:r></w:p>").join("") + "</w:body></w:document>");
  return zip.generateAsync({ type: "nodebuffer" });
}
function pdfFixture() {
  const stream = "BT /F1 12 Tf 72 720 Td (Confirmed robotics hiring requirement) Tj ET";
  const objects = ["<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>", "<< /Length " + stream.length + " >>\nstream\n" + stream + "\nendstream", "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"];
  let content = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => { offsets.push(Buffer.byteLength(content)); content += index + 1 + " 0 obj\n" + object + "\nendobj\n"; });
  const offset = Buffer.byteLength(content);
  content += "xref\n0 6\n0000000000 65535 f \n" + offsets.slice(1).map((value) => String(value).padStart(10, "0") + " 00000 n \n").join("") + "trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n" + offset + "\n%%EOF";
  return Buffer.from(content);
}

async function taskFileFixtures() {
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([["需求记录", "已确认"], ["平台团队补强", "客户电话确认"]]), "客户资料");
  return [
    { name: "需求.txt", mimeType: "text/plain", buffer: Buffer.from("客户原始 TXT 需求：已确认平台团队补强"), expected: "客户原始 TXT 需求" },
    { name: "需求.docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", buffer: await docxFixture("客户原始 DOCX 需求\n确认平台与算法两个方向"), expected: "客户原始 DOCX 需求" },
    { name: "需求.pdf", mimeType: "application/pdf", buffer: pdfFixture(), expected: "Confirmed robotics hiring requirement" },
    { name: "需求.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: XLSX.write(wb, { type: "buffer", bookType: "xlsx" }), expected: "平台团队补强" },
    { name: "需求.csv", mimeType: "text/csv", buffer: Buffer.from("需求记录,已确认\n客户 CSV 原始需求,客户电话确认"), expected: "客户 CSV 原始需求" },
    { name: "需求.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jTz8AAAAASUVORK5CYII=", "base64"), expected: "未实际完成的 OCR" },
  ];
}

test("真实 TXT、DOCX、PDF、表格、截图和链接均保留来源与可审核输入", async ({ page }) => {
  test.setTimeout(100000);
  const errors = trackConsoleErrors(page);
  const fixtures = await taskFileFixtures();
  for (const fixture of fixtures) {
    const prompt = "公司：星澜机器人\n机会名称：" + fixture.name + "独立需求\n招聘需求摘要：本次" + fixture.name + "确认的新研发需求\n需求依据：客户文字确认；附件作为补充来源";
    await page.goto("#/new?kind=opportunity&prompt=" + encodeURIComponent(prompt));
    await page.locator('.s2-composer input[type="file"]').setInputFiles({ name: fixture.name, mimeType: fixture.mimeType, buffer: fixture.buffer });
    await button(page, "发送").click();
    await waitForOpportunityDraft(page);
    await expect(heading(page, "待确认的招聘机会")).toBeVisible();
    if (fixture.name.endsWith(".png")) await expect(page.getByText(new RegExp(fixture.expected)).first()).toBeVisible();
    if (!fixture.name.endsWith(".png")) expect((await snapshot(page)).tasks.at(-1).draft.source.content).toContain(fixture.expected);
    await page.getByRole("button", { name: new RegExp(fixture.name) }).click();
    await expect(heading(page, fixture.name)).toBeVisible();
    const download = page.waitForEvent("download");
    await page.getByRole("dialog").last().getByRole("button", { name: "下载", exact: true }).click();
    expect((await download).suggestedFilename()).toBe(fixture.name);
    await page.getByRole("dialog").last().getByRole("button", { name: "关闭", exact: true }).last().click();
    await replyToAsset(page, "是");
    await expect(page.getByRole("link", { name: "查看招聘机会", exact: true })).toBeVisible();
    const state = await snapshot(page);
    expect(state.opportunities.at(-1).sources[0].fileId).toBeTruthy();
    expect(state.files.find((file) => file.id === state.opportunities.at(-1).sources[0].fileId).name).toBe(fixture.name);
  }
  await page.goto("#/new?kind=opportunity&prompt=" + encodeURIComponent("来源链接：https://example.com/recruiting\n公司：星澜机器人\n机会名称：链接原文独立需求\n招聘需求摘要：用户粘贴原始职位需求\n需求依据：原文确认两个招聘需求，不自动抓取无法访问的链接"));
  await button(page, "发送").click();
  await waitForOpportunityDraft(page);
  await expect(heading(page, "待确认的招聘机会")).toBeVisible();
  await replyToAsset(page, "是");
  await expect(page.getByRole("link", { name: "查看招聘机会", exact: true })).toBeVisible();
  expect((await snapshot(page)).opportunities.at(-1).sources[0].url).toBe("https://example.com/recruiting");
  await capture(page, "task-results");
  await errors();
});

test("方向内岗位任务逐类读取实际文件和链接，经人工补齐审核后形成独立岗位", async ({ page }) => {
  test.setTimeout(130000);
  const errors = trackConsoleErrors(page);
  const opportunityId = await createOpportunity(page, "company-xinglan", "多类型岗位资料来源");
  const fixtures = await taskFileFixtures();
  fixtures.push({ name: "来源链接", expected: "客户后续提供的链接原文" });
  for (const fixture of fixtures) {
    await page.goto("#/opportunities/" + opportunityId + "?tab=directions");
    await addDirection(page, fixture.name + "岗位");
    await page.locator(".s4-direction-list article").filter({ hasText: fixture.name + "岗位" }).getByRole("button", { name: "形成岗位", exact: true }).click();
    await button(page, "AI 整理岗位").click();
    await expect(heading(page, "待确认的岗位")).toBeVisible();
    if (fixture.buffer) await page.locator('.s2-composer input[type="file"]').setInputFiles({ name: fixture.name, mimeType: fixture.mimeType, buffer: fixture.buffer });
    await page.locator(".s2-composer textarea").fill(fixture.buffer ? "补充本方向的原始岗位资料，等待核对。" :
      "来源链接：https://example.com/customer-jd\n来源原文：客户后续提供的链接原文\n岗位职责\n负责模型评测和测试平台。\n任职要求\n熟悉自动化测试。");
    await button(page, "发送").click();
    await expect(heading(page, "待确认的岗位")).toBeVisible();
    await expect(page.locator(".s2-user-message").getByText(new RegExp(fixture.expected)).last()).toBeVisible();
    await replyToAsset(page, jd + "\n本次需求：" + fixture.name + "资料由客户确认。");
    await replyToAsset(page, "是");
    await expect(page.getByRole("link", { name: "查看岗位详情", exact: true })).toBeVisible();
    const state = await snapshot(page);
    const position = state.positions.at(-1);
    const task = state.tasks.at(-1);
    expect(position.name).toBe(fixture.name + "岗位");
    expect(position.origin.opportunityId).toBe(opportunityId);
    expect(position.origin.taskId).toBe(task.id);
    expect(position.sources[0].content).toContain(fixture.expected);
    expect(task.messages.some((message) => message.fileIds?.length)).toBe(Boolean(fixture.buffer));
  }
  await errors();
});

test("机会新增查重、字段编辑、版本冲突以及刷新不丢失", async ({ page, context }) => {
  const errors = trackConsoleErrors(page);
  const title = "同名需求需核对";
  const id = await createOpportunity(page, "company-xinglan", title);
  await page.goto("#/opportunities/new?companyId=company-xinglan");
  await field(page, "机会名称").fill(title);
  await field(page, "招聘需求摘要").fill("这是另一轮数据团队需求");
  await field(page, "发现依据").fill("客户第二轮邮件确认");
  await button(page, "创建招聘机会").click();
  await expect(heading(page, "比较已有机会")).toBeVisible();
  expect((await snapshot(page)).opportunities).toHaveLength(5);
  await button(page, "选择更新此机会").click();
  await button(page, "更新所选机会").click();
  await expect(heading(page, title)).toBeVisible();
  expect((await snapshot(page)).opportunities).toHaveLength(5);
  await button(page, "编辑资料").click();
  await field(page, "预计人数").fill("2-3 人");
  const other = await context.newPage();
  await other.goto(page.url().split("?")[0]);
  await button(other, "编辑资料").click();
  await field(other, "机会名称").fill("其他页面已确认的新名称");
  await button(other, "保存修改").click();
  await expect(other.getByRole("dialog")).toHaveCount(0);
  await expect(heading(page, "其他页面已确认的新名称")).toBeVisible();
  await button(page, "保存修改").click();
  await expect(page.getByText("资料已被更新，请查看最新变化后重新确认。", { exact: true })).toBeVisible();
  await expect(field(page, "预计人数")).toHaveValue("2-3 人");
  expect((await snapshot(page)).opportunities.find((item) => item.id === id).title).toBe("其他页面已确认的新名称");
  await other.close();
  await capture(page, "stale-edit");
  await errors();
});

test("匹配独立运行、失败不回滚岗位、JD 更新需要招聘任务重新核对", async ({ page }) => {
  test.setTimeout(80000);
  const errors = trackConsoleErrors(page);
  await page.goto("#/positions/new");
  await field(page, "岗位名称").fill("后台处理验证岗位");
  await page.getByRole("button", { name: "招聘公司*", exact: true }).click();
  await button(page, "星澜机器人").click();
  await field(page, "完整岗位 JD").fill(jd);
  await button(page, "关键技能").click();
  await page.getByPlaceholder("输入关键技能后按 Enter 添加").fill("机器人学习");
  await page.getByPlaceholder("输入关键技能后按 Enter 添加").press("Enter");
  await page.keyboard.press("Escape");
  await page.getByRole("checkbox", { name: "创建后立即人岗匹配" }).click();
  await button(page, "创建岗位").click();
  await expect(heading(page, "后台处理验证岗位")).toBeVisible();
  const id = (await snapshot(page)).positions.at(-1).id;
  await page.goto("#/opportunities");
  await expect.poll(async () => (await snapshot(page)).positions.find((item) => item.id === id).processing[0].status).toBe("complete");
  await page.goto("#/demo/opportunities");
  await button(page, "失败范围").click();
  await button(page, "下一次匹配处理").click();
  await button(page, "故障操作").click();
  await page.goto("#/positions/" + id + "?tab=matching");
  await button(page, "重新匹配").click();
  await expect(page.getByText("本次匹配失败，岗位和既有结果未改变", { exact: true })).toBeVisible();
  expect((await snapshot(page)).positions.find((item) => item.id === id).deletedAt).toBe(null);
  await button(page, "开始找人").click();
  await button(page, "创建招聘任务").click();
  await expect(heading(page, "候选人审核")).toBeVisible();
  const taskUrl = page.url();
  await page.goto("#/positions/" + id);
  await button(page, "编辑 JD").click();
  await field(page, "完整岗位 JD").fill(jd + "\n新增要求：必须具备平台可观测性建设经验。");
  await button(page, "保存修改").click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.goto(taskUrl);
  await expect(button(page, "将所选候选人加入岗位储备")).toBeDisabled();
  await expect(page.getByText(/岗位已更新为 v2/)).toBeVisible();
  await button(page, "核对并采用当前 JD").click();
  await expect(button(page, "核对并采用当前 JD")).toHaveCount(0);
  await page.getByRole("checkbox", { name: /选择.*林昊/ }).click();
  await button(page, "将所选候选人加入岗位储备").click();
  await expect(page.getByText(/已将 林昊 加入岗位储备/)).toBeVisible();
  await page.goto("#/positions/" + id + "?tab=pipeline");
  await button(page, "变更阶段").click();
  await button(page, "目标阶段").click();
  await button(page, "已推荐").click();
  await field(page, "本次推进记录").fill("客户已确认推荐，未由系统发送外部联系");
  await button(page, "确认变更").click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.reload();
  expect((await snapshot(page)).positions.find((item) => item.id === id).pipeline[0].stage).toBe("recommended");
  await errors();
});

test("机会历史导入只读保留，坏文件仍能通过任务安全反馈", async ({ page }) => {
  const errors = trackConsoleErrors(page);
  await page.goto("#/opportunities");
  await page.evaluate((seed) => {
    const state = JSON.parse(localStorage.getItem("hunter-opportunity-lifecycle-v1")) || seed;
    state.imports.push({ id: "historical-import", name: "旧客户需求", type: "招聘机会", file: "旧客户需求.csv", createdAt: "2026-09-01T00:00:00Z", status: "需要处理", rows: [{ rowNo: 2, patch: { title: "旧需求草稿" }, status: "ready" }] });
    localStorage.setItem("hunter-opportunity-lifecycle-v1", JSON.stringify(state));
  }, createOpportunitySeed());
  await page.reload();
  await page.goto("#/data/imports");
  await page.locator(".s4-task-table article").filter({ hasText: "旧客户需求" }).getByRole("button", { name: "查看详情" }).click();
  await expect(page.getByText("历史导入记录", { exact: true })).toBeVisible();
  await expect(button(page, "继续处理未成功行")).toHaveCount(0);
  await page.goto("#/new?kind=opportunity");
  await page.locator('input[type="file"]').setInputFiles({ name: "合法名称.pdf", mimeType: "application/pdf", buffer: Buffer.from("这不是 PDF 内容") });
  await button(page, "发送").click();
  await waitForOpportunityDraft(page);
  await expect(heading(page, "待确认的招聘机会")).toBeVisible();
  await expect(page.getByText(/合法名称.pdf：/)).toBeVisible();
  expect((await snapshot(page)).opportunities).toHaveLength(4);
  await replyToAsset(page, "机会名称：失败后保留的手工草稿");
  await replyToAsset(page, "否");
  await page.reload();
  await waitForOpportunityDraft(page);
  expect((await snapshot(page)).tasks.at(-1).draft.patch.title).toBe("失败后保留的手工草稿");
  await errors();
});
