export const overviewMetrics = [
  {
    id: "active",
    label: "活跃工作空间",
    value: "128",
    delta: "+12.3%",
    tone: "success",
    note: "近 7 天至少完成一次有效操作",
    route: "/ops/users-workspaces?tab=workspaces",
    points: [28, 31, 29, 36, 41, 44, 49],
  },
  {
    id: "tasks",
    label: "自动化任务",
    value: "3,842",
    delta: "+8.6%",
    tone: "info",
    note: "已排除测试和取消任务",
    route: "/ops/tasks?tab=runs",
    points: [32, 40, 38, 43, 51, 48, 56],
  },
  {
    id: "adoption",
    label: "成果采纳率",
    value: "72.4%",
    delta: "+3.1%",
    tone: "success",
    note: "用户确认或自动确认的有效成果",
    route: "/ops/tasks?tab=runs&result=adopted",
    points: [48, 46, 51, 52, 54, 58, 60],
  },
  {
    id: "conversion",
    label: "订阅转化率",
    value: "18.7%",
    delta: "+1.8%",
    tone: "success",
    note: "试用结束后 14 天内完成订阅",
    route: "/ops/subscriptions?tab=subscriptions",
    points: [18, 22, 21, 25, 27, 29, 31],
  },
  {
    id: "cost",
    label: "单工作空间成本",
    value: "¥ 18.42",
    delta: "-6.2%",
    tone: "success",
    note: "模型、搜索、存储与通知的平均成本",
    route: "/ops/capabilities?tab=health",
    points: [55, 51, 52, 48, 47, 43, 40],
  },
];

export const workspaces = [
  {
    id: "ws-blue",
    name: "深蓝猎头工作室",
    owner: "沈岚",
    email: "shenlan@deepblue-talent.cn",
    account: "正常",
    plan: "专业版",
    subscription: "正常",
    quota: 68,
    storage: "6.8 GB",
    storageRisk: "正常",
    health: "需关注",
    lastActive: "今天 16:42",
    createdAt: "2026-05-18",
    region: "中国大陆",
    workspaceNo: "WS-20260518-0142",
    taskCount: 184,
    supportCount: 1,
  },
  {
    id: "ws-qichen",
    name: "启辰人才顾问",
    owner: "周予安",
    email: "zhouyuan@qichen-search.com",
    account: "正常",
    plan: "试用",
    subscription: "3 天后到期",
    quota: 91,
    storage: "2.4 GB",
    storageRisk: "正常",
    health: "正常",
    lastActive: "今天 15:18",
    createdAt: "2026-08-12",
    region: "中国大陆",
    workspaceNo: "WS-20260812-0287",
    taskCount: 43,
    supportCount: 0,
  },
  {
    id: "ws-yuanwang",
    name: "远望招聘咨询",
    owner: "林嘉昕",
    email: "jiaxin@farview-recruit.cn",
    account: "正常",
    plan: "专业版",
    subscription: "支付异常",
    quota: 47,
    storage: "8.9 GB",
    storageRisk: "接近上限",
    health: "需关注",
    lastActive: "今天 11:06",
    createdAt: "2026-04-03",
    region: "中国大陆",
    workspaceNo: "WS-20260403-0088",
    taskCount: 266,
    supportCount: 2,
  },
  {
    id: "ws-zhixing",
    name: "知行人才寻访",
    owner: "顾清越",
    email: "qingyue@zhixing-talent.com",
    account: "已停用",
    plan: "基础版",
    subscription: "已到期",
    quota: 100,
    storage: "3.1 GB",
    storageRisk: "正常",
    health: "无运行任务",
    lastActive: "8 月 17 日",
    createdAt: "2026-03-26",
    region: "中国大陆",
    workspaceNo: "WS-20260326-0061",
    taskCount: 72,
    supportCount: 1,
  },
  {
    id: "ws-lighthouse",
    name: "灯塔科技猎聘",
    owner: "陈屿川",
    email: "yuchuan@lighthouse-search.cn",
    account: "正常",
    plan: "专业版",
    subscription: "正常",
    quota: 34,
    storage: "4.2 GB",
    storageRisk: "正常",
    health: "正常",
    lastActive: "昨天 22:17",
    createdAt: "2026-06-21",
    region: "中国大陆",
    workspaceNo: "WS-20260621-0194",
    taskCount: 126,
    supportCount: 0,
  },
  {
    id: "ws-northstar",
    name: "北辰人才伙伴",
    owner: "许诺言",
    email: "nuoyan@northstar-hr.cn",
    account: "正常",
    plan: "基础版",
    subscription: "正常",
    quota: 83,
    storage: "1.9 GB",
    storageRisk: "正常",
    health: "正常",
    lastActive: "昨天 18:40",
    createdAt: "2026-07-08",
    region: "中国大陆",
    workspaceNo: "WS-20260708-0228",
    taskCount: 84,
    supportCount: 0,
  },
];

export const users = [
  {
    id: "usr-001",
    name: "沈岚",
    email: "shenlan@deepblue-talent.cn",
    verified: "已验证",
    security: "正常",
    workspace: "深蓝猎头工作室",
    lastLogin: "今天 16:42",
    status: "正常",
  },
  {
    id: "usr-002",
    name: "周予安",
    email: "zhouyuan@qichen-search.com",
    verified: "已验证",
    security: "正常",
    workspace: "启辰人才顾问",
    lastLogin: "今天 15:18",
    status: "正常",
  },
  {
    id: "usr-003",
    name: "林嘉昕",
    email: "jiaxin@farview-recruit.cn",
    verified: "已验证",
    security: "需要验证",
    workspace: "远望招聘咨询",
    lastLogin: "今天 11:06",
    status: "正常",
  },
  {
    id: "usr-004",
    name: "顾清越",
    email: "qingyue@zhixing-talent.com",
    verified: "已验证",
    security: "正常",
    workspace: "知行人才寻访",
    lastLogin: "8 月 17 日",
    status: "已停用",
  },
  {
    id: "usr-005",
    name: "陈屿川",
    email: "yuchuan@lighthouse-search.cn",
    verified: "已验证",
    security: "正常",
    workspace: "灯塔科技猎聘",
    lastLogin: "昨天 22:17",
    status: "正常",
  },
];

export const trialApplications = [
  {
    id: "TRIAL-260824-017",
    name: "宋知遥",
    email: "songzhiy@vision-partner.cn",
    experience: "8 年 · 科技与制造",
    scale: "每月约 120 个自动化任务",
    appliedAt: "今天 14:26",
    status: "待处理",
    note: "计划先由 2 位顾问试用",
  },
  {
    id: "TRIAL-260824-016",
    name: "罗远帆",
    email: "yuanfan@talentbridge.cn",
    experience: "5 年 · AI 与芯片",
    scale: "每月约 80 个自动化任务",
    appliedAt: "今天 10:18",
    status: "待处理",
    note: "希望试用人才摸排与学术搜索",
  },
  {
    id: "TRIAL-260823-012",
    name: "陆霁川",
    email: "jichuan@nova-search.cn",
    experience: "11 年 · 高端制造",
    scale: "每月约 200 个自动化任务",
    appliedAt: "昨天 17:40",
    status: "暂缓",
    note: "等待确认团队使用规模",
  },
  {
    id: "TRIAL-260822-008",
    name: "叶清晗",
    email: "qinghan@spring-search.cn",
    experience: "3 年 · 互联网产品",
    scale: "每月约 40 个自动化任务",
    appliedAt: "8 月 22 日",
    status: "已批准",
    note: "已创建账号与工作空间",
  },
];

export const tasks = [
  {
    id: "TASK-260824-019",
    workspaceId: "ws-blue",
    workspace: "深蓝猎头工作室",
    type: "学术搜索",
    status: "失败",
    phase: "结果整合",
    startedAt: "今天 15:54",
    duration: "38 分 12 秒",
    retries: 2,
    resource: "已释放",
    error: "SOURCE_RATE_LIMIT",
    checkpoint: "筛选完成",
    safe: true,
    safeReason: "业务结果尚未写入，可从筛选检查点继续。",
    usage: "模型 126k tokens · 搜索 892 次",
  },
  {
    id: "TASK-260824-018",
    workspaceId: "ws-blue",
    workspace: "深蓝猎头工作室",
    type: "公司调研",
    status: "运行中",
    phase: "公开资料核验",
    startedAt: "今天 15:37",
    duration: "47 分 06 秒",
    retries: 1,
    resource: "运行中",
    error: "—",
    checkpoint: "证据采集",
    safe: false,
    safeReason: "任务仍在持续写入检查点，当前不可重复入队。",
    usage: "模型 94k tokens · 搜索 218 次",
  },
  {
    id: "TASK-260824-015",
    workspaceId: "ws-yuanwang",
    workspace: "远望招聘咨询",
    type: "岗位解析",
    status: "需处理",
    phase: "结果门禁",
    startedAt: "今天 13:42",
    duration: "2 小时 06 分",
    retries: 3,
    resource: "资源未释放",
    error: "OUTPUT_SCHEMA_INVALID",
    checkpoint: "结构化结果",
    safe: true,
    safeReason: "非法结果未写入，可终止残留资源并重新入队。",
    usage: "模型 71k tokens",
  },
  {
    id: "TASK-260824-011",
    workspaceId: "ws-qichen",
    workspace: "启辰人才顾问",
    type: "候选人补全",
    status: "已完成",
    phase: "结果交付",
    startedAt: "今天 10:21",
    duration: "12 分 47 秒",
    retries: 0,
    resource: "已释放",
    error: "—",
    checkpoint: "完成",
    safe: false,
    safeReason: "任务已经完成，无需恢复。",
    usage: "模型 29k tokens · 搜索 43 次",
  },
  {
    id: "TASK-260823-204",
    workspaceId: "ws-lighthouse",
    workspace: "灯塔科技猎聘",
    type: "公司调研",
    status: "已完成",
    phase: "结果交付",
    startedAt: "昨天 21:04",
    duration: "24 分 18 秒",
    retries: 1,
    resource: "已释放",
    error: "—",
    checkpoint: "完成",
    safe: false,
    safeReason: "任务已经完成，无需恢复。",
    usage: "模型 63k tokens · 搜索 136 次",
  },
  {
    id: "TASK-260823-196",
    workspaceId: "ws-yuanwang",
    workspace: "远望招聘咨询",
    type: "学术搜索",
    status: "已取消",
    phase: "机构召回",
    startedAt: "昨天 18:26",
    duration: "8 分 35 秒",
    retries: 0,
    resource: "已释放",
    error: "USER_CANCELLED",
    checkpoint: "机构解析",
    safe: false,
    safeReason: "由用户主动取消，不应由运营恢复。",
    usage: "模型 14k tokens · 搜索 27 次",
  },
];

export const errorGroups = [
  {
    id: "ERR-SOURCE-RATE",
    code: "SOURCE_RATE_LIMIT",
    title: "外部数据源请求频率受限",
    count: 37,
    workspaces: 12,
    taskTypes: "学术搜索、公司调研",
    firstSeen: "8 月 22 日 09:14",
    lastSeen: "今天 16:08",
    status: "观察中",
    capability: "公开网络搜索",
  },
  {
    id: "ERR-SCHEMA",
    code: "OUTPUT_SCHEMA_INVALID",
    title: "结构化结果未通过门禁",
    count: 18,
    workspaces: 7,
    taskTypes: "岗位解析、候选人补全",
    firstSeen: "8 月 23 日 13:08",
    lastSeen: "今天 15:48",
    status: "处理中",
    capability: "大模型",
  },
  {
    id: "ERR-RESOURCE",
    code: "RESOURCE_RELEASE_TIMEOUT",
    title: "任务资源释放超时",
    count: 5,
    workspaces: 4,
    taskTypes: "公司调研、学术搜索",
    firstSeen: "今天 08:42",
    lastSeen: "今天 14:02",
    status: "需处理",
    capability: "任务执行",
  },
  {
    id: "ERR-MAIL",
    code: "MAIL_AUTH_REJECTED",
    title: "发件邮箱授权失效",
    count: 9,
    workspaces: 8,
    taskTypes: "邮件发送",
    firstSeen: "8 月 20 日 11:31",
    lastSeen: "今天 09:47",
    status: "用户处理",
    capability: "邮件",
  },
];

export const subscriptions = workspaces.map((workspace, index) => ({
  id: `SUB-${String(index + 61).padStart(4, "0")}`,
  workspaceId: workspace.id,
  workspace: workspace.name,
  plan: workspace.plan,
  status: workspace.subscription,
  renewal:
    workspace.plan === "试用"
      ? "不适用"
      : index === 2
        ? "自动续订失败"
        : "自动续订",
  period:
    workspace.plan === "试用"
      ? "2026-08-12 至 2026-08-27"
      : "2026-08-01 至 2026-08-31",
  quota: `${workspace.quota}%`,
  expiresAt: workspace.plan === "试用" ? "2026-08-27" : "2026-08-31",
  payment: index === 2 ? "待处理" : workspace.plan === "试用" ? "—" : "正常",
}));

export const orders = [
  {
    id: "ORD-20260824-0081",
    workspace: "远望招聘咨询",
    plan: "专业版月付",
    amount: "¥ 899.00",
    method: "微信支付",
    status: "扣款失败",
    createdAt: "今天 09:01",
    completedAt: "—",
  },
  {
    id: "ORD-20260823-0078",
    workspace: "深蓝猎头工作室",
    plan: "专业版月付",
    amount: "¥ 899.00",
    method: "支付宝",
    status: "已支付",
    createdAt: "昨天 08:46",
    completedAt: "昨天 08:47",
  },
  {
    id: "ORD-20260821-0069",
    workspace: "灯塔科技猎聘",
    plan: "专业版月付",
    amount: "¥ 899.00",
    method: "微信支付",
    status: "已支付",
    createdAt: "8 月 21 日",
    completedAt: "8 月 21 日",
  },
  {
    id: "ORD-20260818-0056",
    workspace: "北辰人才伙伴",
    plan: "基础版月付",
    amount: "¥ 299.00",
    method: "支付宝",
    status: "已退款",
    createdAt: "8 月 18 日",
    completedAt: "8 月 19 日",
  },
];

export const entitlementChanges = [
  {
    id: "ADJ-260824-012",
    workspace: "深蓝猎头工作室",
    type: "任务额度",
    before: "4,800",
    after: "4,920",
    reason: "补偿重复扣减额度",
    reference: "TASK-260824-019",
    operator: "许维 · 运营人员",
    createdAt: "今天 16:22",
  },
  {
    id: "ADJ-260823-009",
    workspace: "启辰人才顾问",
    type: "试用期限",
    before: "14 天",
    after: "21 天",
    reason: "试用范围扩展",
    reference: "SUP-20260823-014",
    operator: "许维 · 运营人员",
    createdAt: "昨天 17:05",
  },
  {
    id: "ADJ-260821-004",
    workspace: "远望招聘咨询",
    type: "并发上限",
    before: "2",
    after: "4",
    reason: "专业版权益调整",
    reference: "SUB-0063",
    operator: "程远 · 系统管理员",
    createdAt: "8 月 21 日",
  },
];

export const capabilities = [
  {
    id: "cap-model",
    name: "大模型",
    status: "正常",
    success: "99.1%",
    latency: "4.8 秒",
    capacity: "62%",
    cost: "¥ 1,842 / 日",
    fallback: "未启用",
    event: "今天 14:30 路由延迟短时升高",
    impact: "无用户影响",
    provider: "主路由 + 2 个兜底路由",
  },
  {
    id: "cap-search",
    name: "公开网络搜索",
    status: "降级",
    success: "91.4%",
    latency: "2.6 秒",
    capacity: "78%",
    cost: "¥ 616 / 日",
    fallback: "已启用",
    event: "今天 15:51 主数据源频率受限",
    impact: "12 个工作空间的任务延迟",
    provider: "主数据源受限，兜底路由生效",
  },
  {
    id: "cap-academic",
    name: "学术数据",
    status: "正常",
    success: "97.8%",
    latency: "3.2 秒",
    capacity: "48%",
    cost: "¥ 284 / 日",
    fallback: "部分启用",
    event: "昨天 20:17 公开接口恢复",
    impact: "无持续影响",
    provider: "3 个数据源并行召回",
  },
  {
    id: "cap-code",
    name: "代码与开源数据",
    status: "正常",
    success: "98.6%",
    latency: "2.1 秒",
    capacity: "34%",
    cost: "¥ 96 / 日",
    fallback: "未启用",
    event: "无未解决事件",
    impact: "无",
    provider: "认证接口 + 公开接口",
  },
  {
    id: "cap-mail",
    name: "邮件",
    status: "需关注",
    success: "94.2%",
    latency: "1.8 秒",
    capacity: "41%",
    cost: "¥ 52 / 日",
    fallback: "不适用",
    event: "8 个用户邮箱授权失效",
    impact: "仅影响对应用户发件",
    provider: "用户邮箱协议",
  },
  {
    id: "cap-file",
    name: "文件解析",
    status: "正常",
    success: "99.4%",
    latency: "8.7 秒",
    capacity: "55%",
    cost: "¥ 348 / 日",
    fallback: "已启用",
    event: "无未解决事件",
    impact: "无",
    provider: "文档解析 + 视觉理解",
  },
  {
    id: "cap-storage",
    name: "存储",
    status: "正常",
    success: "99.99%",
    latency: "86 毫秒",
    capacity: "67%",
    cost: "¥ 422 / 日",
    fallback: "跨区备份",
    event: "无未解决事件",
    impact: "无",
    provider: "对象存储 + 数据库",
  },
  {
    id: "cap-notify",
    name: "通知",
    status: "正常",
    success: "99.7%",
    latency: "430 毫秒",
    capacity: "28%",
    cost: "¥ 28 / 日",
    fallback: "重试队列",
    event: "无未解决事件",
    impact: "无",
    provider: "站内通知 + 邮件",
  },
];

export const capabilityConfigurations = [
  {
    id: "CFG-MODEL-014",
    capability: "大模型",
    activeVersion: "v14",
    route: "主模型 → 兜底模型 A → 兜底模型 B",
    quota: "日预算 ¥ 3,000",
    key: "sk-••••••••d81f",
    validatedAt: "今天 09:42",
    status: "已验证",
    updatedBy: "程远",
  },
  {
    id: "CFG-SEARCH-009",
    capability: "公开网络搜索",
    activeVersion: "v9",
    route: "主数据源 → 兜底公开搜索",
    quota: "日请求 240,000",
    key: "bce-••••••••87ae",
    validatedAt: "8 月 21 日",
    status: "已验证",
    updatedBy: "程远",
  },
  {
    id: "CFG-ACADEMIC-011",
    capability: "学术数据",
    activeVersion: "v11",
    route: "多数据源并行 + 去重",
    quota: "单任务不限制召回",
    key: "oa-••••••••c920",
    validatedAt: "8 月 20 日",
    status: "已验证",
    updatedBy: "程远",
  },
];

export const supportRecords = [
  {
    id: "SUP-20260824-017",
    workspace: "深蓝猎头工作室",
    category: "任务运行异常",
    summary: "用户报告任务长时间停留在结果整合阶段",
    diagnostic: "DIAG-260824-031",
    status: "处理中",
    createdAt: "今天 16:04",
    updatedAt: "今天 16:31",
    operator: "许维",
  },
  {
    id: "SUP-20260824-015",
    workspace: "远望招聘咨询",
    category: "支付问题",
    summary: "自动续订扣款失败，需要确认支付状态",
    diagnostic: "—",
    status: "等待用户",
    createdAt: "今天 09:18",
    updatedAt: "今天 10:06",
    operator: "许维",
  },
  {
    id: "SUP-20260823-014",
    workspace: "启辰人才顾问",
    category: "试用范围",
    summary: "申请延长试用以覆盖完整招聘周期",
    diagnostic: "—",
    status: "已解决",
    createdAt: "昨天 15:40",
    updatedAt: "昨天 17:05",
    operator: "许维",
  },
  {
    id: "SUP-20260821-009",
    workspace: "知行人才寻访",
    category: "账号使用",
    summary: "工作空间到期后确认数据查看与导出范围",
    diagnostic: "DIAG-260821-018",
    status: "已解决",
    createdAt: "8 月 21 日",
    updatedAt: "8 月 22 日",
    operator: "乔安",
  },
];

export const diagnostics = [
  {
    id: "DIAG-260824-031",
    workspace: "深蓝猎头工作室",
    version: "0.12.45",
    createdAt: "今天 16:02",
    expiresAt: "8 月 31 日",
    task: "TASK-260824-019",
    status: "已解析",
    environment: "macOS arm64 · 桌面端",
    checksum: "匹配",
  },
  {
    id: "DIAG-260824-026",
    workspace: "远望招聘咨询",
    version: "0.12.45",
    createdAt: "今天 12:18",
    expiresAt: "8 月 31 日",
    task: "TASK-260824-015",
    status: "已解析",
    environment: "Windows 11 x64 · Web",
    checksum: "匹配",
  },
  {
    id: "DIAG-260821-018",
    workspace: "知行人才寻访",
    version: "0.12.44",
    createdAt: "8 月 21 日",
    expiresAt: "已过期",
    task: "—",
    status: "已过期",
    environment: "Windows 10 x64 · Web",
    checksum: "匹配",
  },
  {
    id: "DIAG-260820-012",
    workspace: "北辰人才伙伴",
    version: "0.12.44",
    createdAt: "8 月 20 日",
    expiresAt: "8 月 27 日",
    task: "TASK-260820-071",
    status: "文件损坏",
    environment: "未识别",
    checksum: "不匹配",
  },
];

export const auditRecords = [
  {
    id: "AUD-260824-1092",
    actor: "许维",
    role: "运营人员",
    action: "退还重复任务额度",
    object: "深蓝猎头工作室",
    result: "成功",
    createdAt: "今天 16:22",
    reference: "ADJ-260824-012",
  },
  {
    id: "AUD-260824-1088",
    actor: "程远",
    role: "系统管理员",
    action: "终止异常资源占用",
    object: "TASK-260824-015",
    result: "成功",
    createdAt: "今天 15:53",
    reference: "TASK-260824-015",
  },
  {
    id: "AUD-260824-1084",
    actor: "许维",
    role: "运营人员",
    action: "查看用户诊断包",
    object: "DIAG-260824-031",
    result: "成功",
    createdAt: "今天 16:08",
    reference: "SUP-20260824-017",
  },
  {
    id: "AUD-260824-1071",
    actor: "程远",
    role: "系统管理员",
    action: "验证能力配置草稿",
    object: "CFG-SEARCH-010-draft",
    result: "失败",
    createdAt: "今天 14:37",
    reference: "SEC-260824-006",
  },
  {
    id: "AUD-260823-1042",
    actor: "许维",
    role: "运营人员",
    action: "批准试用申请",
    object: "叶清晗",
    result: "成功",
    createdAt: "昨天 11:24",
    reference: "TRIAL-260822-008",
  },
];

export const securityEvents = [
  {
    id: "SEC-260824-006",
    type: "密钥验证异常",
    severity: "高",
    summary: "公开网络搜索配置草稿连续 3 次验证失败",
    status: "调查中",
    firstSeen: "今天 14:31",
    lastSeen: "今天 14:37",
    scope: "未影响生效配置",
    owner: "程远",
  },
  {
    id: "SEC-260824-004",
    type: "异常成本",
    severity: "中",
    summary: "学术数据单小时调用成本超过近 7 日基线",
    status: "已确认",
    firstSeen: "今天 10:08",
    lastSeen: "今天 10:32",
    scope: "7 个工作空间",
    owner: "程远",
  },
  {
    id: "SEC-260823-011",
    type: "越权尝试",
    severity: "高",
    summary: "运营角色尝试访问系统能力配置写入接口",
    status: "已关闭",
    firstSeen: "昨天 18:22",
    lastSeen: "昨天 18:22",
    scope: "请求已拒绝，无数据变更",
    owner: "程远",
  },
];

export const riskItems = [
  {
    id: "risk-search",
    title: "公开网络搜索处于降级状态",
    meta: "12 个工作空间受影响 · 15:51 开始",
    tone: "warning",
    icon: "warning",
    route: "/ops/capabilities?tab=health&capability=cap-search",
  },
  {
    id: "risk-resource",
    title: "3 个任务资源释放超时",
    meta: "最长已持续 2 小时 06 分",
    tone: "danger",
    icon: "activity",
    route: "/ops/tasks?tab=runs&resource=leaked",
  },
  {
    id: "risk-cost",
    title: "学术数据成本高于 7 日基线",
    meta: "当前高出 28%，尚未达到自动停用阈值",
    tone: "warning",
    icon: "creditCard",
    route: "/ops/support?tab=security",
  },
];

export const operationsNav = [
  { label: "运营概况", icon: "home", to: "/ops/overview" },
  { label: "用户与工作空间", icon: "users", to: "/ops/users-workspaces" },
  { label: "订阅与额度", icon: "creditCard", to: "/ops/subscriptions" },
  { label: "任务与故障", icon: "activity", to: "/ops/tasks", badge: 3 },
  { label: "系统能力", icon: "database", to: "/ops/capabilities" },
  { label: "支持与审计", icon: "shield", to: "/ops/support" },
];
